### ISSUE TITLE
Bundlers and binary as static assets

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#119]
Binary is like a static asset for Photon. When bundling Photon with most of the bundlers, they copy over the code but do not copy over the binaries. Most bundlers have ways to copy over assets, we might need to create awareness around binary location and these measures. 

Webpack copy plugin: https://github.com/webpack-contrib/copy-webpack-plugin#copy-webpack-plugin

Parcel copy plugin: https://www.npmjs.com/package/parcel-plugin-static-files-copy

**Comment by nikolasburk** [comment]
I added lightweight docs that mentions the copy-plugins for bundlers via: https://github.com/prisma/prisma-client-js/issues/119

I think eventually the docs should be more exhaustive and provide an example for using these plugins, but that has lower prio right now.
