### ISSUE TITLE
Acquire free port in QueryEngine binary

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#122]
In the current workflow, 

Photon finds a free port by binding to port 0 with a light-weight TCP server (using node net -> createServer), this makes the OS allocate a random (albeit, pseudo serial) port to this server, then this server is closed and Photon saves the port in memory.

Photon then spawns the binary as a child process and provide it the environment variables including the detected port

This port is then provided to the binary as an environment variable and the binary starts an HTTP server on this port.

Getting a port like this is fairly reliable in a system with one process (like the light-weight TCP server in this case), but handing that over to binary for it to start an HTTP server can be slightly less reliable in an environment where a lot of ports (in parallel) are needed like running many services built with Photon in a test suite (`prisma-test-utils`) as the port might already be available to be required by another Photon connect call. 

To reproduce, request multiple (say 1000) Photon `connect` operations simultaneously in a dummy code scenario or in a dummy parallel test suite. 

An alternative can be that Photon signals the binary to start and binary uses the bind to port 0 method to more reliably acquire a free port and communicate that to Photon via an API or a TCP connection.

**Comment by timsuchanek** [comment]
I removed the bug labels, as the concept of acquiring a free port in Node itself is not wrong but needs to be more resilient.

If we want the binary to decide the port, we will have to solve how to communicate that back to TS, which creates new problems. Therefore it's not yet clear, if that the objectively better solution.

**Comment by timsuchanek** [comment]
This will be fixed, once we implemented https://github.com/prisma/prisma-client-js/issues/837

**Comment by pantharshit00** [comment]
Closing as UDS is now the default.
