### ISSUE TITLE
Explicit relation tables

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/prisma-client-js#142]
As far as I aware of, the following feature from Prisma:

```
type MyRelation @relationTable {
  user: User!
  profile: Profile!
}
```

is somehow implemented in Prisma2. But there is no documentation. How to use it?

**Comment by nikolasburk** [comment]
Hey Victor, thanks for opening this issue. This topic indeed lacks proper documentation at the moment. You can however learn about the intended behaviour in our spec [here](https://github.com/prisma/specs/tree/master/prisma-schema-language#explicit-many-to-many-mn-relationships).

In short: The `@relationTable` attribute is not needed any more. Instead you define a relation table in the same way you'd define any other model: 

```prisma
model MyRelation {
  user: User!
  profile: Profile!
}
```

**Comment by victordombrovskiy** [comment]
@nikolasburk will it be included in the today's release? Or when do you this will be fixed? Just want to plan further work based on availability of this feature.

**Comment by nikolasburk** [comment]
It won't be included in today's release and might take a few more weeks (possibly months) until it is available.

**Comment by divyenduz** [comment]
We dropped this for now but this will be picked up again in coming weeks. We have noted that community wants this feature. It is blocked on some internal refactoring around supporting multiple unique ids and would be picked up in a bigger epic.

**Comment by victordombrovskiy** [comment]
@divyenduz What is status of this? A lot of weeks passed :)

**Comment by divyenduz** [comment]
@victordombrovskiy If I understand it correctly, this feature is being worked on from the perspective of introspection https://github.com/prisma/prisma2/issues/1083 and is in the current milestone.

**Comment by mavilein** [comment]
@divyenduz : We are working on it right now. But it will take a few more weeks until this will be finished.

**Comment by janpio** [comment]
This is now implemented and can be used with the syntac @nikolasburk posted above 🚀
