### ISSUE TITLE
DateTime becomes string

### ISSUE THREAD

**Issue by newtack** [prisma/prisma-client-js#145]
The model
```groovy
model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

gets translated to
```ts
export declare type Post = {
    id: string;
    createdAt: string;
    updatedAt: string;
    published: boolean;
    title: string;
    content: string | null;
};
```

The point of Photon is type safety, yet the translator changes DateTime to string instead of Date. 

Please change the type to Date or at a minimum give me an option to generate a Date.

**Comment by timsuchanek** [comment]
Thanks for reporting! I just edited your issue comment to have syntax highlighting.
We'll tackle this this week!

**Comment by 19majkel94** [comment]
So this is considered as a bug? 

For now in runtime it's a string, so the types are correct but it would be more developer-friendly if the dates from db would be converted to JS `Date` instances.

**Comment by matthewmueller** [comment]
Sorry for the late reply on this issue! We should definitely make this change.

```diff
export declare type Post = {
    id: string;
-   createdAt: string;
+   createdAt: Date;
-   updatedAt: string;
+   updatedAt: Date;
    published: boolean;
    title: string;
    content: string | null;
};
```

@timsuchanek I think this lands on your plate 🍽

**Comment by divyenduz** [comment]
Internal note: to be discussed further in the photon spec issue

**Comment by divyenduz** [comment]
This is not reproducible anymore with `2.4.0-dev.13`. @newtack Please ping here if this issue still persists for you.
