### ISSUE TITLE
EPIC: Photon API improvements

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#167]
We're currently working on another major Photon iteration (**see the [updated API specification](https://github.com/prisma/specs/blob/photonjs-improvements/specs/PhotonJS.md)**) based on initial feedback and more feature requests. This will be a bigger (breaking) change to the current version of Photon which we want to think through carefully before implementing.

_Note: We're doing this breaking change now during the Prisma 2 preview period in order to avoid any other breaking changes once Prisma 2 GA is released._

## Related issues

- Add `findOrCreate` method #85
- DateTime becomes string #145 
- ...

**Comment by Akkuma** [comment]
One thing I'd like to see although a bit more foreign in JS is avoiding the use of `null` by using something like a Result/Option/Maybe type.

**Comment by schickling** [comment]
@Akkuma would you mind creating a separate issue for this with some code examples how you imagine the API to look like?
