### ISSUE TITLE
Any way to specify `tsconfig.json` used in `prisma2 generate`?

### ISSUE THREAD

**Issue by hoshikawa** [prisma/prisma-client-js#175]
Hi, I'm planning to use prisma2 in a project with ES Modules.
I think it would be useful if I can specify a typescript config file used in `prisma2 generate` since I have to get rid of CommonJS terms such as `exports`, `require`, and so on, which are [likely to be removed from Node.js when `--experimental-modules ` flag is enabled](https://nodejs.org/api/esm.html#esm_no_code_require_code_code_exports_code_code_module_exports_code_code_filename_code_code_dirname_code).

Thank you!

**Comment by schickling** [comment]
Thanks a lot for opening this issue @hoshikawa. That's a great point. We should definitely add support for this feature.

**Comment by timsuchanek** [comment]
Thanks for the report @hoshikawa!
We're thinking about adding support for this feature.
By default, the Photon generator will soon directly calculate the `.js` + `.d.ts`, but we can add an option to run the TypeScript compiler over that generated output.

Which concrete `tsconfig` options would you use in your case?

**Comment by hoshikawa** [comment]
Thanks @timsuchanek !
In my case, I write `tsconfig.json` like:
```js
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "ESNext",                       /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "outDir": "../dist/server/src",           /* Redirect output structure to the directory. */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */

    /* Module Resolution Options */
    "moduleResolution": "node",               /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
  },
  "references": [
    { "path": "../shared" }
  ]
}

```

Note that my project have three different `tsconfig.json` for server side codes, client side codes, and shared codes. The above is from the server side, which I think will interact with the generated Photon client.
My understanding is that `"module": "ESNext"` is the point. When set to `"ESNext"`, CommonJS terms would not be emitted.

Would this be fine? Thank you!

**Comment by timsuchanek** [comment]
That sounds good! In this case it looks like we can solve also without adding support for a custom `tsconfig.json`, by allowing the module ESNext.

As we'll soon probably get rid of TypeScript in the building pipeline, we could add that option manually.

In other words, it's very unlikely that we will allow customizing the `tsconfig.json`, but we can still cover your use-case.

**Comment by timsuchanek** [comment]
As we're now directly generating the resulting TypeScript client, we can't adjust the `tsconfig.json` used by the generation, anymore.
If you have a use-case please let us know!
