### ISSUE TITLE
Cross database Prisma Client

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#184]
In its current state, the generated Photon is differently generated for various database providers. However, a use case can be to use `sqlite` locally at the inception of a project (for ease of on-boarding amongst other reasons) but move to a DB capable of more heavy lifting. 

This issue persist thoughts around this feature. 

Here is a note from a user: 

> For right now today I can use the same DB everywhere, but once everything is getting closer to being production-ready I think allowing for multiple providers is a huge help for new devs learning the framework—they can use sqlite locally and get started without worrying about installing/configuring MySQL or Postgres, everything “just works”.  This is the approach that Rails kind of pioneered and it’s been great. I almost always start with sqlite locally and only go to MySQL if/when I end up needing to write some MySQL-specific SQL that sqlite doesn’t support

**Comment by Errorname** [comment]
I agree with the user for the need of this for on-boarding and local dev.

Another use case would be for a multi-tenancy application: You want to be able to dynamically connect to databases that could theoretically differ on the type (mysql, pgsql, sqlite, ..). We then need a single generated Photon that would be able to handle all db types.

**Comment by divyenduz** [comment]
An idea to support cross database photon can be to generate a Photon client based on the intersection of the DB feature. 

We are heavily mapping this out in the capabilities spec here (@matthewmueller is championing it): https://github.com/prisma/specs/issues/110

Happy to know your thoughts on this 🙌

**Comment by Errorname** [comment]
If Photon is generated based on the intersection, what would you need to do in order to use a specific DB feature? (Eg: postgres JSON fields)

**Comment by divyenduz** [comment]
In that case (just the current idea - might change), you will have to use same data source locally and in production. Because the intersection feature would allow type safety. If specific feature needs to be used however, that shield of type safety goes away.

An alternative can be to have a common shim for Json. 

@matthewmueller has more context :)

**Comment by janpio** [comment]
This will be implemented via https://github.com/prisma/prisma/issues/1487 🚀
