### ISSUE TITLE
Results should always include foreign key columns

### ISSUE THREAD

**Issue by cannikin** [prisma/prisma-client-js#188]
I would like to propose that when returning records from a table, any foreign key columns are automatically included. For example:

```
model User {
  id    Int   @id @unique
  name  String
  posts Post[]
}

model Post {
  id   Int @id @unique
  text String
  user User
}
```

Returning all posts with `photon.posts.findMany()` today results in:

```json
[
  {
    "id": 1,
    "text": "Hello, world"
  },
  { 
    "id": 2,
    "text": "Foobar"
  }
]
```

I'm proposing that it return the following instead:

```json
[
  {
    "id": 1,
    "text": "Hello, world",
    "user": 10
  },
  { 
    "id": 2,
    "text": "Foobar",
    "user": 11
  }
]
```

I can still return the full associated User object, if desired, with the `include:` option. 

My reasoning is that when I say "I want a post" or "I want all posts" then that means I want *all* of the data for those posts. If I only want a subset of columns then I'll use the `select:` option and list the specific fields that I want.

In the app I'm currently working in I'll pull a collection of data when the app launches and additional data later if the user navigates to a certain page. When they do, the additional data I need is looked up by a foreign key and then associated and displayed. I find myself constantly having to use an `:include => :select` in order to get that foreign key returned in my first batch of data. One of my queries looks like:

```javascript
photon.users.findMany({
  include: {
    note: { select: { id: true } },
    responses: {
      include: {
        form: { select: { id: true } },
        answers: {
          include: {
            question: { select: { id: true } }
          }
        }
      }
    }
  }
})
```

If the foreign keys were included by default this would become:

```javascript
photon.users.findMany({
  include: {
    note: true,
    responses: { include: { answers: true } }
  }
})
```

**Comment by schickling** [comment]
Thanks a lot for raising this point @cannikin. We'll try to improve this behavior!

**Comment by schickling** [comment]
Looks like this is being addressed here: https://github.com/prisma/prisma2/issues/1606#issuecomment-601753275

**Comment by mavilein** [comment]
This is implemented now and available on `alpha`.
