### ISSUE TITLE
Nexus prisma performance

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#196]
Right now neither photon nor nexus-prisma implements a dataloader which introduces the N + 1 problem. 

So any nested type resolution right now is a separate database call which is bad for performance. There is already an issue for dataloader introduction in photon(#153) but this issue is meant to keep track of the progress of implementation of this pattern in nexus prisma.

nexus-prisma v1 also suffered from the same performance drops because of a lack of dataloader implementation. So we should act on this in order to give a proper upgrade path to v1 users so that they can make use of the better that can be provided by batching db calls.

Read this comment for getting a brief idea about the path that needs to be followed in order to achieve this: https://github.com/prisma/photonjs/issues/153#issuecomment-516767534

**Comment by jhalborg** [comment]
@pantharshit00 Do you know if any work is being done regarding this topic and Photon? We're looking to perform a major migration from `prisma-bindings` to Photon+Nexus-Prisma within the next couple of months

**Comment by pantharshit00** [comment]
Yes, definitely. This is one of the things that we will solve before the full release. Parallelism in the binary is the most important thing for this that we are working on right now.

Please read Tim's comment here: https://github.com/prisma/photonjs/issues/153#issuecomment-516767534

**Comment by schickling** [comment]
This will be unblocked once https://github.com/prisma/specs/issues/242 is specced and implemented.

**Comment by jhalborg** [comment]
Won't the implementation of the DataLoader in Prisma automatically make Nexus Prisma use it as well, or am I missing something? 😅

**Comment by schickling** [comment]
Yes, exactly @jhalborg 💯

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
