### ISSUE TITLE
Name collision with identical relational property names on separate types that refer to a common type

### ISSUE THREAD

**Issue by artemzakharov** [prisma/prisma-client-js#201]
Apologize if the title is confusing, but this is a really odd issue, so I wasn't sure how to word it 😅 feel free to edit it to something more appropriate!

I have a schema that looks like this (excluding the obvious fields like ids):
```
model Foo {
  fooVersions: FooVersion[]   @relation("A")
}

model FooVersion {
  foo:      Foo?              @relation("A")
  bars:     Bar[]             @relation("B")

}

model Bar {
  fooVersions: FooVersion[]   @relation("B")
}
```

If I try to simultaneously create a Foo and a FooVersion node and then customize the FooVersion node's `bars` relation, however, I get an odd type error:
```
photon.foos.create({
  data: {
    fooVersions: {
      create: {
        bars: <- this property isn't accessible
      }
    }
  }
})
```
If I hover over the `create` property to see the type, it gives something like this:
```
(property) create?: Enumerable<FooVersionCreateWithoutBarsInput>
```
However, if I now modify the schema by renaming `fooVersions` on type `Bar` to something else (like `otherFooVersions`),
```
model Bar {
  otherFooVersions: FooVersion[]   @relation("B")
}
```
the `bars` property is suddenly accessible:
```
photon.foos.create({
  data: {
    fooVersions: {
      create: {
        bars: <- this property is now accessible
      }
    }
  }
})
```
and hovering over the `create` field now gives this type instead:
```
(property) create?: Enumerable<FooVersionCreateWithoutFooInput>
```
I'm not sure how to summarize all of this in a sentence or two, but it seems like there's some sort of type collision going on when you have two types that are both related to a third type, and those two types have the exact same property name for referring to their relation to that third type.

**Comment by pantharshit00** [comment]
I can confirm this bug.

Reproduction: https://github.com/harshit-test-org/prisma-photon-201
