### ISSUE TITLE
Update examples to nexus-prisma beta 6

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma-client-js#204]
[Now that nexus-prisma no longer needs our nexus fork](https://github.com/prisma/nexus-prisma/pull/365), we can update all examples to stop using `@prisma/nexus` which is quite confusing for users not to mention developing internally.

**Comment by jasonkuhrt** [comment]
But first I think we'll need to have prisma2 cli updated so that `generate` outputs the correct code: https://github.com/prisma/prisma2/pull/413

**Comment by janpio** [comment]
PR was merged, so with next `alpha` this should be good to go.
