### ISSUE TITLE
Instantiate Prisma Client with an existing pg connection

### ISSUE THREAD

**Issue by jgoux** [prisma/prisma-client-js#216]
Hello,

As photon appears to be a great solution to interact with the database (I see it as something like [massivejs](http://massivejs.org) with type safety), I'd like to be able to instantiate photon with an existing [pg](https://node-postgres.com)'s connection.

My reasoning here is that I use [postgraphile](https://www.graphile.org/postgraphile) as my GraphQL solution which use pg internally. Postgraphile takes care of opening a transaction before a mutation, and pass this transaction to the resolvers. Ideally I'd like to hook into its mechanism and inject photon in place of the low level pg client so I can enjoy interacting with my database inside my resolvers while being in posgraphile's transactional workflow.

For the API, I think just passing the connection to a postgresql generated `Photon` would be enough, such as : `const photon = new Photon({ connection: pgInstance })`

**Comment by thebiglabasky** [comment]
Hi @jgoux 
The architecture of Prisma makes this impossible: the connection to the database is handled at our query engine level (a Rust binary), which can't take a Node connection.
I'll thus close this issue. Thanks!
