### ISSUE TITLE
"exists" query from Prisma 1

### ISSUE THREAD

**Issue by nhuesmann** [prisma/prisma-client-js#224]
In Prisma 1 if I had a User model, I could call `db.exists.User({ email: "test@test.com" })` to check for existence. This functionality came out of the box. Is Prisma 2 going to have this same functionality?

**Comment by divyenduz** [comment]
Yes, this is the WIP Photon spec: https://github.com/prisma/specs/tree/master/photonjs#basic-queries

Exists will be a part of the API in future. 

Please share your feedback on the upcoming Photon API via issues here: https://github.com/prisma/specs/issues

**Comment by albertoperdomo** [comment]
Hello @nhuesmann,

Thanks for taking the time to submit this issue!
The feature request is being tracked in https://github.com/prisma/prisma-client-js/issues/703.
