### ISSUE TITLE
Add some more custom helper methods

### ISSUE THREAD

**Issue by krunaldodiya** [prisma/prisma-client-js#225]
I like this framework so much but still need some more methods to work with, like I come from laravel background and they have many Eloquent Methods, one of them that PhotonJS is needed is "FirstOrCreate"

It would be great to have it, it will reduce too much boilerplate to check if exists and if exist then do something and not then first create and do something

**Comment by albertoperdomo** [comment]
Hello @krunaldodiya,

thanks for taking the time to suggest improvements to Prisma! 
We are tracking this feature request at https://github.com/prisma/prisma-client-js/issues/703.
