### ISSUE TITLE
Confusing/overlapping terminology `photon.connect`

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#227]
While briefly skimming [this issue](https://github.com/prisma/specs/issues/150) I was first thinking of the database connection management (e.g. establishing a TCP connection to a Postgres DB) and just later realized the discussion was about API operations. I‘m wondering whether we should rename either the API operations called `connect` or the exposed query engine method `connect`.

Looking forward to hearing more thoughts on this! 🤔

**Comment by EranSch** [comment]
I think some disambiguation is a good idea. My thoughts based on working with photon here and there over the past few months:

IIRC, the recommendation to call `photon.connect()` has been getting removed from the docs... does this conversation become moot given that method isn't really essential anymore? If it's still to remain but will be less frequently used, I would propose `photon.initializeConnection()`.

It seems this would address the matter in the most straightforward, least disruptive way. 

Alternatively, I could see a case for changing the API operations. For the originally stated reason but also to help visually differentiate `connect` from `create` which I think improve readability. Some initial thoughts:

- `connectTo` & `createAndConnectTo`
- `link` & `create`
- `__connect` & `__create`

**Comment by timsuchanek** [comment]
As there wasn't any activity here and we renamed `prisma.connect` to `prisma.$connect`, I'm closing this.
