### ISSUE TITLE
Way to select certain fields from related tables for prisma2

### ISSUE THREAD

**Issue by P4trik** [prisma/prisma-client-js#250]
Hello *,

if I query a table together with a related table, how can I select only **certain** fields of that **related** table?
```ts
const productsResult = await pt.products.findOne({
  where: {
    product_id: id
  },
  include:{
    product_variants: true
  }
});
```

In this case, I just want to have the "**SKU**" field of the "**product_variants**" table and the "**name**" field of "**products**".
Is that possible at all?

Thank's for answering!

**Comment by divyenduz** [comment]
Internal note: candidate from bug triaging meeting

**Comment by timsuchanek** [comment]
Thanks for reporting this! On the first view this looks like a bug, but indeed is a feature we don't support yet.

To sum up the limitation we're talking about here:

Within a `select` statement, you can't do `include`.
Within an `include` statement, you can't do `select`.

While this is supported by the runtime, use this at your own risk.

The reason we don't support this yet is that the complexity of TypeScript types necessary to achieve this is very high.

In your use-case, the recommendation is to use `select` on all levels.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
