### ISSUE TITLE
Alllow for array-based `select` syntax

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-client-js#26]
Currently I can select fields in a Photon API call using the `select` syntax like so:

```ts
const allPosts: Post[] = await photon.posts.findMany({
  select: { id: true, author: true}
})
```

I think it would be great to provide an array-based API as well:

```ts
const allPosts: Post[] = await photon.posts.findMany({
  select: ["id", "author"]
})
```

**Comment by timsuchanek** [comment]
As we want to have a consistent API as discussed in https://github.com/prisma/prisma-client-js/issues/671 and there wasn't any activity here for over a year, I'm closing this now.
Feel free to reopen in case you want to candidate it.
