### ISSUE TITLE
Store Prisma Client inside `.prisma`

### ISSUE THREAD

**Issue by leo** [prisma/prisma-client-js#262]
This issue suggests a improvement over https://github.com/prisma/photonjs/issues/261.

## Problem

Please read the linked issue in order to understand the problem.

## Solution

In order for Photons not be wiped whenever `yarn` or `npm` are invoked, we want to store a `.prisma` directory directly in the root of the project that the user is working on.

Furthermore, a `@prisma/photon-loader` package will be introduced, which always contains the same code (independent from `prisma2 generate`) and looks for a `.prisma` directory when invoked. If the directory is found, your Photon will be loaded from that directory.

In turn, `prisma2 generate` would also output to that directory.

**Comment by timsuchanek** [comment]
Thanks for the proposal! I just tried out, if the pruning actually happens if we do the file creation in the `install` hook - it turns out, that both npm and yarn are fine with it. So I guess we probably don't need the extra `.prisma` dir.

https://github.com/timsuchanek/tension-with-the-engine

**Comment by leo** [comment]
> it turns out, that both npm and yarn are fine with it

That's 100% correct. However, I wouldn't rely on that assumption. It might change any time. Either way, a `.prisma` directory just seems cleaner and easier to reset for me. @schickling has the full context.

**Comment by jasonkuhrt** [comment]
To avoid pruning, just emit into a real package, in your case, `@prisma/photon-loader`. Also the package naming here strikes me muddying the user's mental model, as opposed to a nice abstraction.

One thing that is interesting about `.prisma` folder however is that ordering no longer matters. I can generate first then npm install or npm install then generate. This is a great benefit. I think it would be worthwhile requirement to put on any solution we go with.

@timsuchanek I'm not sure I follow your experiment. You emit into a package and you emit into the project root, but not into the `node_modules`.

![image](https://user-images.githubusercontent.com/284476/67031526-065d6480-f112-11e9-9a37-1b0a58d24e9f.png)

**Comment by jasonkuhrt** [comment]
@timsuchanek thanks for putting that together. It shows that we can overcome the [yarn always-all-packages-rebuilding issue](https://github.com/yarnpkg/yarn/issues/4703).

**Comment by timsuchanek** [comment]
We are now storing Prisma Client in `node_modules/.prisma`, which works great.
I'll close this for now, as the current solution seems to be what we want.
