### ISSUE TITLE
Implement batching protocol

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#284]
As described in https://github.com/prisma/specs/issues/242#issuecomment-548382431

This issue only tracks the implementation of the batching protocol both on the query-engine and Photon.js side.
The underlying optimization of "merging multiple findOne" queries is a separate issue.

**Comment by timsuchanek** [comment]
Internal Note: Will be dropped for this sprint.

**Comment by Aetherall** [comment]
Hi ! When do you plan to release this feature ?

**Comment by narciero** [comment]
+1 without this it is very time-consuming to seed/migrate data with 1000s of records

**Comment by timsuchanek** [comment]
We have a basic batch protocol implemented under the hood. Exposing that protocol in Prisma client is a separate working item.
