### ISSUE TITLE
throw on findOne if require true

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma-client-js#292]
### Motivation

Sometimes throwing errors is desirable, but sometimes it is preferable to work with `null | ...` (or more structured full-on `Either`/`Maybe` types).

Photon has a couple places in the API where a decision point between these two approaches occurs. I am familiar with `findOne` so will talk about that here.

### Idea

Introduce a new option called, say, `require?: boolean`.

If `true`, e.g.:

```ts
photon.blogs.findOne({ where: { id: 1 }, require: true })
```

1. The return type will be `BlogClient<Blog>`
2. Photon will throw an error if no blog can be found

If `false`, e.g.:

```ts
photon.blogs.findOne({ where: { id: 1 }, require: false })
```

1. The return type will be `BlogClient<null | Blog>`
2. Photon will _not_ throw an error if no blog can be found

If unspecified, e.g.:

```ts
photon.blogs.findOne({ where: { id: 1 } })
```

then it would default `false`. `false` is a good default because throwing is an untracked and unknowable (without prior knowledge) side-effect. Opting-in means you some of that unpredictability is tamed.

For the new Photon API that I've been privy to, I think a `.require()` would work well. Not sure exactly how it looks now, but for example:

```ts
photon.blogs.findOne.where({id: 1 }).require()
```

**Comment by timsuchanek** [comment]
We're now working on this, feedback for the API design welcome https://github.com/prisma/prisma-client-js/issues/708#issuecomment-757852829

**Comment by pantharshit00** [comment]
Closing in favour of #708
