### ISSUE TITLE
Improve debug output of array values

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#312]
Right now array values are just encoded as `[Array]` which doesn't give much information and you need to eventually start the query engine playground to get the full output.

![image](https://user-images.githubusercontent.com/22195362/69717527-3e54c000-1132-11ea-934c-b915a7a4a03e.png)

It would be great if we can get the full output.

**Comment by timsuchanek** [comment]
We're not printing the response anymore, as you can just do a 
```
console.dir(result, { depth: null })
```
yourself in your script.
