### ISSUE TITLE
Support unique relation fields in `findOne` query

### ISSUE THREAD

**Issue by aaronhayes** [prisma/prisma-client-js#328]
[findOne](https://github.com/prisma/specs/tree/master/prisma-client-js#find-a-single-record) Retrieves a single record that can be unambiguously identified by a single unique field or a combination of fields that together are unique.

Currently this only work for scalar fields:

```graphql
model User {
   id String @unique
}
```

```Typescript
const user = await client.users.findOne({ where: { id: 'userId' } })
```

# Suggested change

It is possible to expand this functionality while preserving the fundamental characteristic of the `findOne` operator that it must return a single unambiguously identifiable record. Consider the following schema:

```graphql
model User {
   id           String @unique
   personalInfo PersonalInfo
}

model PersonalInfo {
   id                   String @id
   socialSecurityNumber Int @unique
}
```

A user can be uniquely identified by the `socialSecurityNumber` in the related `PersonalInfo` record, so the following query should be valid:

```Typescript
const user = await client.users.findOne({ where: { personalInfo: { socialSecurityNumber: 123 } } })
```

This represents a significant ergonomics improvement over the current workaround, which requires extra error handling to deal with the array return type:

```Typescript
const users = await client.users.findMany({ where: { personalInfo: { socialSecurityNumber: 123 } } })
const user = users.length > 0 ? users[0] : null
```

**Comment by sorenbs** [comment]
@aaronhayes - I have updated the description of this feature request. I believe it accurately reflects what you were asking for, but please let me know if I missed a nuance in your request 🙏

**Comment by pantharshit00** [comment]
I think this is covered via `findFirst` API which released a while back. Closing.

https://www.prisma.io/docs/concepts/components/prisma-client/crud#findfirst
