### ISSUE TITLE
Filter with scalar lists

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma-client-js#334]
## Problem

Filtering by values in scalar lists is not supported by Client.
Example (credit @tvvignesh, see comment):

Prisma schema
```
model UserAuthentication {
    id          String   @default(cuid()) @id
    emails      String[]
}
```

Expected client functionality
```
db.userAuthentications.findMany({
        where: {
            emails: 'xyz@example.com'
        }
});
```

## Suggested solution

Implement support for filtering in scalar lists.

## Alternatives

Workaround: Use `queryRaw()` and filter manually.

## Original issue

hi guy!  I need help.
This is my model :
```graphql
model Post {
    id      String  @id @default(cuid())
    content String
    images String[]
    ...
}
```

Now I want to find a list of images for all posts, I only need images, so I need to filter out posts that don't have images.  

I try to do this:
```js
ctx.photon.posts.findMany({
     where: {
         images:{
              not: ""
         }
     },
     select:{
          id: true,
          images: true
     }
})
```
I only want images, but unfortunately, this doesn't work. I got the error:
```js
Unknown arg `images` in select.posts.where.images for type PostWhereInput
```
For `field type[]` ( ` images String[] `、`num Int[]` etc.), I don't know how to filter. 

I know I can build an `Image model` to solve this problem, but I don't want it because I don't have extra fields. I only need to store a list of strings like `String[]`, but now it doesn't work for filters.

What should I do ?  My database is pg.

**Comment by tvvignesh** [comment]
@divyenduz @janpio Would be great if this can be prioritized. Kind of a critical feature since its always a basic usecase to run a where clause against a list. Was trying to do it today but then came across this issue. 

For example, something like 
```
db.userAuthentications.findMany({
        where: {
            emails: 'xyz@example.com'
        }
});
```
where the schema is like:
```
model UserAuthentication {
    id          String   @default(cuid()) @id
    emails      String[]
}
```

Also, I was wondering, does `@unique` play any role in case of scalar lists? When doing that the migrations crash. Thanks.

**Comment by janpio** [comment]
@tvvignesh Please do not mention people from the development team if you are not responding to a question of them - I removed these mentions from your comment.

**Comment by tvvignesh** [comment]
@janpio Sure. Replied for the same here: https://github.com/prisma/prisma2/issues/1156#issuecomment-566926820

**Comment by albertoperdomo** [comment]
Actually, this is being tracked already at https://github.com/prisma/prisma-client-js/issues/341.
Closing as duplicate. Please use that issue to track progress.
