### ISSUE TITLE
In prisma2 how to connect db by rawAccess enabled just like prisma1

### ISSUE THREAD

**Issue by owcc** [prisma/prisma-client-js#335]
Pleases, I run some sql functions witch prisma2 is not support yet, so how can I excute raw sql querys with `executeRaw` just like prisma1?

**Comment by janpio** [comment]
This is now supported: https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#raw-database-access

Let us know if this solves your request @owcc
