### ISSUE TITLE
sort with orderBy lists

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma-client-js#337]
Hi.
I need to filter posts based on multiple sorting criteria, so I do the following:
```js
ctx.photon.posts.findMany({
     where: filters,
      orderBy:{
          createdAt:"desc",
          title:"asc",
          content: "asc"
      }
})
```
I want it to be sorted first according to the creation time, then sorted by title and content.

But I got an error:
```js
Argument orderBy of type PostOrderByInput needs exactly one argument, but you provided `createdAt` and `title` and `content`.
```
I seem to be able to choose only one, but not multiple.

So I want to know if photon implements multiple conditional sorting. I saw its usage in the [specs](https://github.com/prisma/specs/tree/master/photonjs).

**Comment by jana-uoft** [comment]
I came across this as a surprise since the official docs say it should work with multiple arguments. 

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#reference-1

Eg: 
`
export type UserOrderByInput = {
  id?: OrderByArg | null;
  name?: OrderByArg | null;
  email?: OrderByArg | null;
  role?: OrderByArg | null;
  profileViews?: OrderByArg | null;
};
`

**Comment by Sytten** [comment]
It says `Lets you order the returned list by any model property.`. I don't know how you interpret that has saying multiple properti**es**?

**Comment by jana-uoft** [comment]
Hmm, it is the same description for `UserWhereInput` where we can specify multiple properties right?
`
Wraps all fields of a model so that the list can be filtered by any model property.
`

**Comment by pantharshit00** [comment]
I think we can change the wording there to make it more clear for now, maybe you can make a PR here for that: https://github.com/prisma/prisma2-docs

**Comment by albertoperdomo** [comment]
Hello @sessionboy and everyone.

We are tracking this as a feature request in https://github.com/prisma/prisma-client-js/issues/702.
