### ISSUE TITLE
Test if record exists

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma-client-js#340]
Hi, I am enjoying the Prisma2. So far was a really nice experience.

I have a question: 

Previously you had the "exists" method, which is no longer there.
Now, for some reason Prisma throws an error, so now I have to do the try/catch routine to test for record existence.

Is there any less intrusive way of doing that?
It is not necessarily an exception when record does not exist.

**Comment by FinnFrotscher** [comment]
would be nice if you keep your references up to date.

**Comment by pantharshit00** [comment]
@FinnFrotscher Please follow https://github.com/prisma/prisma-client-js/issues/474 for this now

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma-client-js/issues/474 as this is almost a duplicate.
