### ISSUE TITLE
Add case sensitive/insensitive querying

### ISSUE THREAD

**Issue by herbertpimentel** [prisma/prisma-client-js#343]
This is a huge missing feature, as you can see from here (https://github.com/prisma/prisma1/issues/3611) this is really really wanted. all the workarounds we have found will drastically increase the complexity and amount of code necessary to support it.

By now, the best workaround that I have found, ONLY WORKS on prisma2, and is described here (https://www.logisticinfotech.com/blog/postgresql-case-insensitive-citext/) but fails with prisma1x like so (https://github.com/prisma/prisma/issues/4127)

People have been doing all kind of ugly and scary stuff to deal with it. Please add support to it.

**Comment by ctrlplusb** [comment]
Big feature for me. Having to do awkward things to get around this limitation right now - being storing values in all lowercase in a separate field to achieve this.

**Comment by nhuesmann** [comment]
I recently opened an issue for this not realizing there was already one open. Going to everyone else's sentiments, this would be really great to have. Like @ctrlplusb stated, the current workaround I am using involves duplicating each case-sensitive field and creating a lowercased version to sort by. It's not the most critical feature for me—I'd rather have aggregation first :) but it's unnecessary DB bloat.

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by tylerjbainbridge** [comment]
I noticed this was dropped from a sprint last month and wanted to express that this would be really great to have. Right now the workarounds are quite messy.

**Comment by nikolasburk** [comment]
Hey @tylerjbainbridge  👋 thanks a lot for bumping this! Unfortunately this functionality currently has a bit lower priority and it's currently not planned to included in the [initial Q1 launch of Prisma Client](https://www.prisma.io/blog/state-of-prisma-2-december-rcrwcqyu655e/), however we're planning to tackle it very soon after!

**Comment by FinnFrotscher** [comment]
Now that Q1 launch has taken place, any update?

**Comment by albertoperdomo** [comment]
Hello, I've created https://github.com/prisma/prisma-client-js/issues/690 to keep track of the feature request to support case sensitivity in filtering and sorting.

Please feel free to subscribe to [that issue](https://github.com/prisma/prisma-client-js/issues/690) for updates.
