### ISSUE TITLE
Scalar list set undefined throws error

### ISSUE THREAD

**Issue by bluwy** [prisma/prisma-client-js#368]
With [prisma2 2.0.0-preview019](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview019) support for native scalar lists for Postgres, Photon works out of the box setting the value but fails when set value is undefined.

### Environment
**Prisma2**: 2.0.0-preview019
**Photon**: 2.0.0-preview019

### Steps to reproduce

schema.prisma:
```prisma
model User {
  id      String   @default(cuid()) @id
  name    String   @unique
  hobbies String[]
}
```

Photon:
```js
const value = undefined
// Happens in create and update
photon.users.create({
  data: {
    name: 'John',
    hobbies: { set: value }
  }
})
```

### Expected Behavior
Ignore set since its undefined. Works the same way as `connect: undefined` etc

### Actual Behavior
Error occurred (Ansi-stripped)
```
Reason: called `Option::unwrap()` on a `None` value in src\libcore\option.rs:378:21
```

### Temporary Workaround
Directly set `hobbies` to undefined works, so if a variable may be undefined, check if the variable is undefined before assigning the object.

e.g.
```js
const value = undefined
photon.users.create({
  data: {
    name: 'John',
    hobbies: value != null ? { set: value } : undefined
  }
})
```

**Comment by pantharshit00** [comment]
I can confirm this. 

> With prisma2 2.0.0-preview019 support for native scalar lists for Postgres, Photon works out of the box setting the value but fails when set value is undefined.

I tested it out with an older version and behaviour is the same. I think we need to define the behaviour and adjust it accordingly. Marking as a bug for now.

**Comment by timsuchanek** [comment]
This is fixed in the latest version.
```
Error: 
Invalid `prisma.modl.create()` invocation:

{
  data: {
    hobbies: {
      set: undefined
    }
    ~~~~~~~~~~~~~~~~
  }
}

Argument hobbies: Got invalid value 
[
  {
    set: undefined
  }
]
on prisma.createOneModl. Provided List<Json>, expected List<ModlCreatehobbiesInput> or List<String>.
type ModlCreatehobbiesInput {
  set: List<String>
}
```
