### ISSUE TITLE
Cannot read property 'collectErrors' of null

### ISSUE THREAD

**Issue by asciant** [prisma/prisma-client-js#369]
Hi Team,

Probably like many Prisma1 converts, I like referring to the `index.d.ts` file, in the same way I was able to refer to the generated `prisma.graphql` in Prisma1.

While referencing that file, I found an error that didn't seem to be handled by Photon and it took a little tinkering to debug. I thought I would raise a Github issue as by my reading of `runtime/index.js` this is trying to tell me how that I caused the issue, although it isn't able to (and I assume others may be caught out like me).

```javascript
{
  "errors": [
    {
      "message": "Cannot read property 'collectErrors' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "filteredHorses"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'collectErrors' of null",
            "    at errors.push.value.flatMap (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40866:26)",
            "    at flattenIntoArray (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/internals/flatten-into-array.js:16:25)",
            "    at Array.flatMap (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/modules/es.array.flat-map.js:18:16)",
            "    at Arg.collectErrors (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40865:39)",
            "    at args.flatMap.arg (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40789:45)",
            "    at flattenIntoArray (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/internals/flatten-into-array.js:16:25)",
            "    at Array.flatMap (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/modules/es.array.flat-map.js:18:16)",
            "    at Args.collectErrors (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40789:26)",
            "    at Arg.collectErrors (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40876:39)",
            "    at args.flatMap.arg (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40789:45)",
            "    at flattenIntoArray (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/internals/flatten-into-array.js:16:25)",
            "    at Array.flatMap (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/modules/es.array.flat-map.js:18:16)",
            "    at Args.collectErrors (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40789:26)",
            "    at errors.push.value.flatMap (/Users/asciant/Projects/crimson/node_modules/@prisma/photon/runtime/index.js:40869:28)",
            "    at flattenIntoArray (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/internals/flatten-into-array.js:16:25)",
            "    at Array.flatMap (/Users/asciant/Projects/crimson/node_modules/apollo-env/node_modules/core-js/modules/es.array.flat-map.js:18:16)"
          ]
        }
      }
    }
  ],
  "data": {
    "filteredHorses": null
  }
}
```

I eventually tracked the issue down to how I was trying to query (as in the where object) a m:m relationship using the `findMany()` API.

In my `index.d.ts` file, I had the following defintion:

```javascript
    disciplines?: DisciplineFilter | null;
```

What I had assumed was `null` actually equalled the `null` primitive. Based on that, my `findMany` where clause (in cases where the user didn't want to filter results on that field):

```javascript
where: {
    disciplines: null
}
```

This created all manner of errors on each request, like the one above. I was prompted many times by the errors being returned to raise a Github issue (as I was debugging the issue and finding unreachable code), and to that end, thought I would put this up.

I ended up solving the issue by replacing the `null` primitive with a empty object and everything started working again.

```javascript
where: {
    disciplines: {}
}
```

I'm not sure if it is an opportunity to improve the error being returned, or just another one of those situations where you can't cater for everyone. 

There is obviously a little more code in the background, and I'm happy to share, just let me know what you need. While I haven't tried, I am almost certain you could replicate this with the javascript/graphql exmaple from the `prisma-examples` repo with an implicit m:m relationship, combined with the `null` primitive like I outlined above.

Either way, Photon is great to work with, looking forward to the full release.

**Comment by pantharshit00** [comment]
Hi,

Are you able to reliably reproduce this? The stacktrace points out that it a bug in our error collection logic.

Can you give me more details about your operating system and which version of photon you are using?



Also, you should be getting an error like following for this case:
![image](https://user-images.githubusercontent.com/22195362/72086718-6a688100-332d-11ea-875b-2332e3159aba.png)


```js
 const user1 = await photon.users.findMany({
    where:{
      posts: null
    }
  })
```


There is a discrepancy between the generated typing and runtime so I am going to label this as a bug. Typings allow null in where while runtime doesn't

To reproduce:
1. Deploy the following schema:
```prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String
  content   String?
  author    User?
}
```
2. Run the above query.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
