### ISSUE TITLE
Empty array for "disconnect" leads to error

### ISSUE THREAD

**Issue by eWert-Online** [prisma/prisma-client-js#377]
I am getting an error in Photon when trying to execute the following update: 

**Update:**
```
ctx.photon.projects.update({
  where: {
    id,
  },
  data: {
    title,
    members: {
      connect: [],
      disconnect:[],
    },
  },
});
```

**Error:**
```
InterpretationError("Error for binding '3': RecordsNotConnected { 
  relation_name: "ProjectMembers", 
  parent_name: "Project", 
  child_name: "User" 
}
```

The problem is the `disconnect: []`. Even though an empty array is working with `connect` it doesn't work for `disconnect`.

When I am changing it to `disconnect: undefined`, it is working.

Is this behaviour intendet?

**Comment by pantharshit00** [comment]
@eWert-Online Hey, I marked this a confirmed bug but I didn't write an answer to your question here, sorry about that.

This is not an intended behaviour as you should be able to remove all disconnections. That is why I marked this as a confirmed bug,

**Comment by timsuchanek** [comment]
This issue has already been fixed a while ago. If you still face it, let us know and we reopen it.
