### ISSUE TITLE
Optimize Photon's size 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#388]
Just adding Photon with no other deps leads to bundle size of >50 mb which is rejected by AWS Lambda. 

This issue tracks making Photon's size smaller. 

This can also be seen on npm's package list

![image](https://user-images.githubusercontent.com/746482/71996651-d919e180-323c-11ea-99b8-8fd272a6ba05.png)

This size does not include binaries, with them, the bundle is already ~90mb.

**Comment by divyenduz** [comment]
I only installed production deps but it still included `prisma2`, maybe photon has a dep on that. 

I could deploy my bundle by manually removing `node_modules/prisma2`, maybe that is a low handing fruit.

**Comment by janpio** [comment]
We already have a issue somewhere that tracks the removal of Typescript from Photon, which will take care of 99% of that.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest version of `prisma2`.
You can try it out with `npm i -g prisma2`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
