### ISSUE TITLE
Prisma Client + Wildcard = <3?

### ISSUE THREAD

**Issue by brillout** [prisma/prisma-client-js#404]
Hi!

I've implemented an RPC implementation called [Wildcard API](https://github.com/reframejs/wildcard-api#readme).

Wildcard can be used with TypeScript and types defined on the backend are available to the frontend.

This means that, with Wildcard, Photon's types can be used in the frontend code!

What do you think of Wildcard and of using Photon with Wildcard?

![](https://raw.githubusercontent.com/reframejs/wildcard-api/master/examples/prisma/screenshots/types-on-frontend.png)

You can browse an example [here](https://github.com/reframejs/wildcard-api/tree/master/examples/prisma).

Thanks for everything you are doing with Prisma, it's all super exciting.

**Comment by pantharshit00** [comment]
Looks pretty awesome, thanks for sharing!

**Comment by brillout** [comment]
Thanks @pantharshit00 :-)

You might think "Oh well, Wildcard is just RPC, nothing new here", but the thing is that, for most projects (precisely: for projects that don't need third parties to be able to access their data), a well polished RPC implementation such as Wildcard is actually much simpler and more powerful than GraphQL.

It's super important that you guys nail down the right ecosystem around Prisma. I believe Wildcard can be an important part of Prisma's ecosystem.

cc
@timsuchanek
@nikolasburk
@divyenduz
@matthewmueller
@schickling

**Comment by thebiglabasky** [comment]
Hi @brillout and thanks for your proposal,
We're already pretty staffed for the rest of the year with supporting more database types and our core client and migrate products, which makes it unlikely to take on work on the Wildcard API. This looks like an interesting concept though, so if anyone is up for contributing, we'll be happy to help with some reviews!

I will thus close this issue for the time being.
Thank you!
