### ISSUE TITLE
Optimise Photon generate command to only execute if schema has changed

### ISSUE THREAD

**Issue by ctrlplusb** [prisma/prisma-client-js#409]
The `primsa2 generate` command is an intensive operation that can take a while to complete. 

This can cause some friction, for example if making use of Zeit's `now dev` development/proxy server. Their development server follows a strategy of running `npm i` after each change. This causes the `postinstall` script to run, triggering the build of Photon, and has a significant impact to overall DX.

To alleviate this pain I came up with a strategy by which to utilise a checksum of the `prisma.schema` file and then only execute the `prisma2 generate` if the checksum has changed.

For e.g.

```json
{
  "scripts": {
    "generate:prisma": "run-if-changed -f prisma/schema.prisma -c \"prisma2 generate\" --checksumfile=.checksum.prisma",
    "postinstall": "npm run generate:prisma",
```

@schickling came back with the suggestion that we make this a first class behaviour of `prisma2 generate`.

[Original slack discussion here](https://prisma.slack.com/archives/CKQTGR6T0/p1578670032060200)

**Comment by pantharshit00** [comment]
`prisma2 generate --watch` which was shipped in preview020 already implements this. So this can be closed now :)
