### ISSUE TITLE
Usage with `pg-bouncer`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#410]
We should research how to set up Prisma Client together with `pg-bouncer`.

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/prisma2/issues/556

**Comment by pimeys** [comment]
I'll write a document about pgbouncer today.

**Comment by pimeys** [comment]
**Summary**: yes we can.
**Longer summary**: https://www.notion.so/prismaio/Pgbouncer-Evaluation-71076db4699e4ba48bf13df879d485a7

The work so far in two branches:
- https://github.com/prisma/prisma-engine/pull/403
- https://github.com/prisma/quaint/pull/67

**Comment by pimeys** [comment]
Merged to master now, instructions how to enable the transaction mode in query engine can be found here:

https://github.com/prisma/prisma-engine/pull/403

**Comment by pimeys** [comment]
Threw this back to @timsuchanek now. You should make a decision how and when to enable the flag in query engine, if wanting to support pgbouncer transaction mode in the client.

**Comment by timsuchanek** [comment]
Awesome @pimeys! This is a product decision that has to be made, how we expose this in Prisma Client. cc @sorenbs

**Comment by pimeys** [comment]
We now run all the tests against pgbouncer in transaction mode btw.

**Comment by pimeys** [comment]
I did an initial test how Heroku's Pgbouncer offering could work together with Prisma. Summarizing what needs to be done for Pgbouncer:

If in `session` mode, everything works just normally. Just point Prisma to the Pgbouncer URL and call it a day.

If in `transaction` mode, certain settings need to be modified in Pgbouncer config:

```
pool_mode = transaction
server_reset_query = DEALLOCATE ALL
server_reset_query_always = 1
```

And of course the Prisma Client needs to start the server in the right mode, e.g. [this spec](https://github.com/prisma/specs/issues/386) should be implemented.

Heroku allows changing Pgbouncer's settings using environment variables. For now only two of the three settings can be changed:
``` bash
> heroku config:add PGBOUNCER_POOL_MODE=transaction
> heroku config:add PGBOUNCER_SERVER_RESET_QUERY="DEALLOCATE ALL"
```
The third setting should be available when the [needed pull request](https://github.com/heroku/heroku-buildpack-pgbouncer/pull/129) lands.

For other important providers, as discussed with @divyenduz, he will make sure the settings are available. When all is set, these need to be communicated with our users through the documentation.
