### ISSUE TITLE
Remove pluralization

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#423]
This turns `client.users.findMany` into `client.user.findMany`.
The reason is, that especially in existing schemas, you can get very weird pluralization.

E.g. the plural of `Posts` -> `Postses` or `News` -> `Newses`.

**Comment by tvvignesh** [comment]
Just saw this. Off to re-writing my queries now :sob: But this is good in a long run ofcourse.

**Comment by tvvignesh** [comment]
@timsuchanek Also, it does not work for all cases. If you see the screenshot below, after running `prisma2 generate` `appCreds` is renamed to `appCreds` itself and the same with `providerData` and this causes duplication in the class and hence error `Duplicate identifier 'appCreds'`

![Screenshot from 2020-01-24 12-51-56](https://user-images.githubusercontent.com/1165845/73051258-546bcc00-3ea8-11ea-9096-e72814d26288.png)

This is how appcreds schema looks like:

```
model AppCreds {
    id           String             @default(cuid()) @id
    clientID     String             @unique
    clientSecret String
    app          AppAuthentication
    createdBy    UserAuthentication
    createdDate  DateTime           @default(now())
    updatedDate  DateTime           @updatedAt
}
```

**Comment by janpio** [comment]
Please open new issues about these problems @tvvignesh - otherwise your concerns might get lost accidentally. Only new issues make sure we can actually look into things and properly handle them.
