### ISSUE TITLE
Invalid `photon.()` invocation on ECONNREFUSED

### ISSUE THREAD

**Issue by seawatts** [prisma/prisma-client-js#424]
The error that is emitted if the connection cannot be established is not clear unless you set `DEBUG=*`  

`engine connect ECONNREFUSED 127.0.0.1:57626`

**Comment by pantharshit00** [comment]
Can you please share more details like a screenshot? Also, if you can provide a minimal reproduction for this, that would be great.

**Comment by JWambaugh** [comment]
I am having the same issue. Happens after just a few queries now. #435 Regardless of the cause, there should be a more verbose error message when this happens.

**Comment by timsuchanek** [comment]
Fixed in latest version.
