### ISSUE TITLE
Wrong error message when invoking `findOne` without args

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma-client-js#431]
this code

```
prisma.posts.findOne()
```

results in this error:

```
TypeError: Cannot read property 'select' of undefined
    at Function.PostDelegate.Post.findOne (/Users/sorenschmidt/code/a/node_modules/@prisma/client/index.js:279:35)
    at /Users/sorenschmidt/code/a/index.js:6:18
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

But should rather have been something like this:

![image](https://user-images.githubusercontent.com/281337/72922783-f9be5d00-3d4d-11ea-885c-b8b1975929b2.png)

**Comment by pantharshit00** [comment]
I can confirm this: 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22195362/72923512-3baec980-3d75-11ea-987a-7439408bca97.png">

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
