### ISSUE TITLE
Input Sanitization

### ISSUE THREAD

**Issue by asciant** [prisma/prisma-client-js#436]
Does Photon/Prisma-Client-JS sanitize user input?

I was led to believe that Prisma1 was safe from injection type attacks, although I couldn't be sure that this was the case.

Could you please confirm if we should be sanitizing user input or not.

**Comment by pantharshit00** [comment]
Yes, we do use prepared statements(https://en.wikipedia.org/wiki/Prepared_statement) in the engine so you are safe from injection attacks when you are using Prisma.
