### ISSUE TITLE
Stub types should be included in the released package

### ISSUE THREAD

**Issue by scriptcoded** [prisma/prisma-client-js#438]
As of preview020 types are not included with the NPM package. As suggested by @akoufatzis in https://github.com/prisma/prisma2/issues/1421#issuecomment-577614059 the project should compile before running the `prisma2 generate` command, or perhaps even before it's even released on NPM.

TypeScript gives the following error:

```
Could not find a declaration file for module '@prisma/client'. '/my/project/node_modules/@prisma/client/index.js' implicitly has an 'any' type.
  Try `npm install @types/prisma__client` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/client';`ts(7016)
```

(@janpio sorry if I rushed it 🙈)

**Comment by timsuchanek** [comment]
Thanks for posting this idea @scriptcoded ! We just added stub types in the latest alpha version.

You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
