### ISSUE TITLE
Filter according to relations

### ISSUE THREAD

**Issue by germsb** [prisma/prisma-client-js#440]
Filters according to relation documentation is quite poor, difficult to know what can be done.
An example is better than a long text:

```prisma
model Post {
  id          String   @id @default(cuid())
  title       String   @default("")
  tags        Tag[]
}

model Tag {
  id        String    @id @default(cuid())
  name      String    @default("") @unique
  posts     Post[]
}
```
after seeding, `await db.post.findMany()` return
```json
[
  {
    "title": "post 1",
    "tags": [{"name": "typescript"}, {"name": "prisma"}]
  },
  {
    "title": "post 2",
    "tags": [{"name": "typescript"}]
  },
  {
    "title": "post 3",
    "tags": [{"name": "prisma"}]
  },
  {
    "title": "post 4",
    "tags": [{"name": "filter"}]
  },
  {
    "title": "post 5",
    "tags": [{"name":"prisma"}, {"name":"filter"}]
  },
  {
    "title": "post 6",
    "tags": [{"name":"typescript"}, {"name":"prisma"}, {"name":"filter"}]
  }
]
```
### Somes requests:
```typescript
await db.post.findMany({ where: {
      tags: { every: { OR: [{ name: "typescript" }, { name: "prisma" }] } }
    }});
```
- return posts **1 2 3**

```typescript
await db.post.findMany({ where: {
      tags: { some: { OR: [{ name: "typescript" }, { name: "prisma" }] } }
    }});
```
- return posts **1 2 3 5 6**
```typescript
await db.post.findMany({ where: {
      tags: { every: { AND: [{ name: "typescript" }, { name: "prisma" }] } }
    }});
````
- return **nothings**

### Questions
- is there a way to find posts with at least the "typescript" and "prisma" tags  ? (eg: posts 1 and 6)
- is there a way to find posts with strictly "typescript" and "prisma" tags ? (eg: post 1)

**Comment by pantharshit00** [comment]
Thanks for asking this. These filters can be tricky for complex queries so please try to think them in terms of javascript arrays and remember or have `AND` and `OR` available at the top level.

Here are queries that you have asked for:

is there a way to find posts with strictly "typescript" and "prisma" tags? (eg: post 1)
```ts
const res1 = await prisma.posts.findMany({
    where: {
      AND: [
        {
          tags: {
            some: {
              name: 'typescript',
            },
          },
        },
        {
          tags: {
            some: {
              name: 'prisma',
            },
          },
        },
      ],
    },
    include: {
      tags: true,
    },
  })
```

The second one is a bit more tricky, in SQL you would match the count using `HAVING COUNT(*) = 2` in your join or you will use `3 = (your condition)`

The current API doesn't let you filter by count(maybe open a feature request about this).

So you will need to query like so and manually filter out in code the values which array item count greater than 2:
```ts
const res = await prisma.posts.findMany({
    where: {
      tags: {
        every: {
          name: {
            in: ['typescript', 'prisma'],
          },
        },
      },
    },
    include: {
      tags: true,
    },
  })

const data = res1.filter(r => r.tags.length === 2)
console.dir(data, { depth: Infinity })
```
