### ISSUE TITLE
Duplicate `null` in ENUM filters

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#442]
Reproduction: https://github.com/harshit-test-org/prisma2-client-442

Right now the enum filters are being generated with duplicate `null` types when they are marked as optional in the schema.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/22195362/73171304-76728200-4126-11ea-9c7c-00432ec66b71.png">

**Comment by timsuchanek** [comment]
Update: This also applies to other `Nullable` Scalar filters:
```ts
export type NullableStringFilter = {
  equals?: string | null | null
  not?: string | null | NullableStringFilter | null
  in?: Enumerable<string> | null
  notIn?: Enumerable<string> | null
  lt?: string | null
  lte?: string | null
  gt?: string | null
  gte?: string | null
  contains?: string | null
  startsWith?: string | null
  endsWith?: string | null
}
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
