### ISSUE TITLE
Database restart not handled gracefully

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#446]
I use a Postgres database and have a Node.js web server running with Prisma Client, pointing to it.
If I restart my Postgres database, it's not available for a couple of seconds.
The query engine then exits.
Prisma Client from then on errors, that the engine exited.
I would like Prisma Client and the query engine to be more resilient in this situation and have a longer timeout so that the application doesn't crash immediately.

**Comment by pimeys** [comment]
Updating the pool to a later version and testing with it:

https://github.com/prisma/quaint/pull/69

Now when prisma is open and one kills the database, some of the threads will crash and restart in tokio, some requests will get errors and when the database is back up, the connections will be back up. It needs to be decided what the client should do in a situation when the we get connection errors and crashing threads in QE. It can heal itself, but of course a situation when the database goes down would be one where we'd expect everything to panic and raise alarms.

Now QE will panic and yell when it happens, but will also heal itself hopefully in a good condition.

**Comment by pimeys** [comment]
@timsuchanek merged to alpha.

**Comment by timsuchanek** [comment]
This is implemented in the latest alpha.
