### ISSUE TITLE
File name (`datamodel.mdl`) and client name (`Photon JS`) in graphic in README need to be updated

### ISSUE THREAD

**Issue by smakosh** [prisma/prisma-client-js#447]
![image](https://user-images.githubusercontent.com/20082141/73139503-e9202680-406e-11ea-95a5-16947049195c.png)

**Comment by pantharshit00** [comment]
Thanks for reporting @smakosh. Sorry for the transfer, we tend to keep only the client issues in the repository but this one adheres to the README of this repository so it is fine keeping this here.

**Comment by nikolasburk** [comment]
Fixed both for Prisma Client and Prisma Migrate: 

- https://github.com/prisma/migrate/commit/ccc5b50cc08f74c534843fca606c9b8393f3c606
- https://github.com/prisma/prisma-client-js/commit/ae2313ef626ae443e4b897c95103318eb0da964c
