### ISSUE TITLE
Prisma Client should pick up required env vars from .env file during development

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#454]
## Context

We currently encourage users to hardcode their DB credentials into the `schema.prisma` by this being the default getting started experience. We should strongly **discourage** developers to do so and therefore adjust our getting started experience + examples accordingly in order to encourage the use of environment variables.

In order to not degrade the DX during local development, I'm suggesting the following change in Prisma Client.

## Proposal

- Prisma Client should auto-import required env vars (i.e. env vars referenced in the Prisma schema in the `datasource.url` property) from the `.env` file during development.
    - Implementation notes: It's important that this functionality/feature takes the **lowest precedent** (i.e. if the user provides their own env vars, call `require('dotenv')` or similar themselves, this feature shouldn't conflict in any way)
    - It should **not** make the env vars available to the entire Node process but just the query engine.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
