### ISSUE TITLE
.raw(...) query

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#455]
We want to offer a fallback for all queries that are not supported by Prisma Client itself. We will achieve that by offering a `.raw` method that you can use to send any query to the database and get back its result.

Prior Art:
https://github.com/prisma/specs/issues/12#issuecomment-562585839
https://github.com/prisma/prisma-client-js/issues/10

**Comment by Jolg42** [comment]
Implemented in `prisma2@2.0.0-alpha.741` 🎊

**Comment by timsuchanek** [comment]
Therefore this can be closed :)
