### ISSUE TITLE
Error when setting a relation field to `null`

### ISSUE THREAD

**Issue by kgoggin** [prisma/prisma-client-js#459]
Hello! I just stumbled on this error that I believe to be a bug and thought I'd share it. I've got a call out to create an entity with an optional 1:1 relation to another entity. Here's the code:

```js
ctx.prisma.lessons.create({
        data: {
          title: args.data.title,
          schoolYear: { connect: { id: schoolYear.id } },
          status: args.data.status,
          students: {
            connect: args.data.students.map(id => ({ id: id }))
          },
          subject: args.data.subjectId
            ? {
                connect: { id: args.data.subjectId }
              }
            : null,
          notes: {
            create: [
              {
                content: args.data.description,
                type: "DESCRIPTION"
              }
            ]
          },
          day
        }
      })
```

The offending line is where I'm setting the `subject` field with a ternary statement. If it evaluates as `null`, then the call fails with the following error:

```
Error occurred during query validation & transformation:\nAssertion error: Attempted conversion of non-map ParsedInputValue (Single(Null)) into map failed..
```
The `code` field is `P2009` if that's helpful.

The workaround for me is to change `null` to `undefined`, which seems to work fine. Note that TypeScript is cool with either value, so either the generated types are wrong or something with the query engine is.

Thanks!

**Comment by timsuchanek** [comment]
Thanks a lot for reporting!
And thanks for the reproduction @pantharshit00.

I just looked into it and there is an important difference between the reported error and the reproduction.

The reported error fails in 
```ts
  const data = await prisma.user.create({
    data: {
      name: "Harshit Pant",
      posts: null
    }
  });
```
Errors in 
```
P2009: Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Attempted conversion of non-map ParsedInputValue (Single(Null)) into map failed..` at ``
```

Whereas the reproduction mentions
```ts
  const data = await prisma.user.create({
    data: {
      name: "Harshit Pant",
      posts: { connect: null }
    }
  });
```
And errors in
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
```


They are related to different problems, but of course both need to be fixed.

**Comment by dpetrick** [comment]
Related, and probably resolved: https://github.com/prisma/prisma-client-js/issues/614

**Comment by pantharshit00** [comment]
I can confirm this has been fixed in the latest alpha. 

@kgoggin Can you please confirm, to install the alpha use `npm install @prisma/cli@alpha && npx prisma generate`

**Comment by kgoggin** [comment]
@pantharshit00 sorry I can't easily confirm - I've since refactored that code and don't have an easy way to verify. Glad for the fix though!
