### ISSUE TITLE
Better runtime error handling for missing binaries

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#466]
## Context

The Prisma Client relies on the query engine binary in order to connect to a datasource and execute queries. The binary is added to the generated Prisma Client Node package (by default in `node_modules/@prisma/client`) during the generation step and also needs to be consider during potential build/bundle steps when deploying an application.

While we're heavily investing into making sure this "implementation detail" is not really noticeable in any negative way for users, this still sometimes goes wrong (e.g. when we've not yet "paved the way" for a certain bundler/deployment platform like in this issue: https://github.com/prisma/prisma2/issues/1525). 

## Proposal

In these cases I'd like to make sure to provide a more helpful error message as a fallback. Currently we're showing an error message similar to this one:

```
Error: Error: Command failed with ENOENT: /tmp/build_beae1b0150b0593ec3b0251a339290fe/node_modules/prisma2/query-engine-debian-openssl-1.1.x cli --dmmf
spawn /tmp/build_beae1b0150b0593ec3b0251a339290fe/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
```

I'd like to introduce a special error handling for this kind of problem by roughly doing the following:

1. When Prisma Client is trying to spawn the query engine and fails it should catch the error
2. It should go through the known common error scenarios and detect whether any of these is the cause for the occurred problem.
3. It should now throw/print out a more helpful error message (i.e. better contextual information and concrete solution instructions)

It's important that this error handling happens "lazily" i.e. not **before** the query engine is spawned which would result in an potential IO overhead even in successful cases but just once an error has been thrown which just adds this overhead in the error case which is much better. (This is a more generally applicable pattern I suggest calling "lazy special error handling".)

**Comment by pantharshit00** [comment]
## Current behaviours

### Client
The following error is thrown when I manually remove the binary from the runtime folder:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22195362/74747851-9ad8fe80-528d-11ea-85b8-61bfcf6b5938.png">


### CLI
The following error is thrown when I manully remove the binaries from the `prisma2` folder inside the node_modules:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22195362/74747875-a62c2a00-528d-11ea-9a87-e38baa6c8506.png">

**Comment by janpio** [comment]
Next step:

> * It should go through the known common error scenarios and detect whether any of these is the cause for the occurred problem.
> * It should now throw/print out a more helpful error message (i.e. better contextual information and concrete solution instructions)

What are these common error scenarios?
What should the error message for each be?

> Client
> The following error is thrown when I manually remove the binary from the runtime folder:

The current custom error message for the Client does not seem to be correct, and was probably written for one of those cases.

**Comment by janpio** [comment]
One common scenario seems to be this one: https://github.com/prisma/prisma2/issues/1635

**Comment by timsuchanek** [comment]
This has been fixed in the latest alpha.
We added solutions and tests for the different scenarios that can occur.
