### ISSUE TITLE
Idea to better up prisma client

### ISSUE THREAD

**Issue by greguintow** [prisma/prisma-client-js#469]
You could do the functionality of filter in findMany, just like you use on studio like equals, gt, gte, lt, lte, not and also functions like non_sensitive that kind of stuff of conditions.
I think would be very helpful.

**Comment by pantharshit00** [comment]
> And another idea that would be helpful it's de function exists, that had on prisma-binding.

Can you please elaborate? I can't seem to understand you here.

**Comment by greguintow** [comment]
> > And another idea that would be helpful it's de function exists, that had on prisma-binding.
> 
> Can you please elaborate? I can't seem to understand you here.

@pantharshit00 Yes sure, what I meant that on prisma-binding there is a funciton of exists, I'm going to explain better below.
![image](https://user-images.githubusercontent.com/30958574/74041274-1d1b1600-49a4-11ea-9577-201423514095.png)
That function just like a where of a findMany, as you can see there AND, NOT, OR and there are of bunch of options for each property of the model, like birthday it's a DateTime, so if there is one row of User that has the filter that I put for example birthday greater than 2 days ago, it's going to return true and you can set as many filters as you want. If there is a 1:n relation on your model it's going to show model_every, model_none and model_some, and inside those object it's going to show the properties of the selected model. The color in the picture it's a string as you can see there is the contains option. And if there is a 1:1 relation it's going to show and in this case it's not required so is showing the "?".
I hope that helped to understand better.

**Comment by pantharshit00** [comment]
We still have all of these filters:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/22195362/74049389-04d5e600-49fa-11ea-8dbc-0636ac1028b2.png">


API is bit different now as we have rethought and reduces the clutter. Also, all these filters under `where` key as we have more options like `select` on the top level.

**Comment by greguintow** [comment]
> We still have all of these filters:
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/22195362/74049389-04d5e600-49fa-11ea-8dbc-0636ac1028b2.png">
> 
> API is bit different now as we have rethought and reduces the clutter. Also, all these filters under `where` key as we have more options like `select` on the top level.

@pantharshit00 I don't think you understand, this function (exists) return a boolean, not rows of the table according to the filters set. That funcition is going to look if there is a row or rows with the filters set and return a boolean based on that.

**Comment by pantharshit00** [comment]
Oh ok, now I got it. I think you can open a new FR for this, then we can have a look into this.

**Comment by greguintow** [comment]
> Oh ok, now I got it. I think you can open a new FR for this, then we can have a look into this.

@pantharshit00 I'm sorry to ask you that, but what is a FR? 😅

**Comment by pantharshit00** [comment]
FR means feature request. Just open a new issue in this repository with the description of the feature. That way our team can quickly go over it without reading all of these comments to get context about this.

**Comment by greguintow** [comment]
> FR means feature request. Just open a new issue in this repository with the description of the feature. That way our team can quickly go over it without reading all of these comments to get context about this.
@pantharshit00 Alright, I'm doing it.
