### ISSUE TITLE
Execute raw is failing when template literal span over multiple lines.

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#473]
`prisma2@2.0.0-alpha.751, binary version: 36b88f31e8d49e22e19d857beac80877164b163b`

I tried to run the following raw query:
```ts
const data = await prisma.raw`
  SELECT * from User
`
```

But it went ahead and threw the following error:
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/22195362/74050754-a78f6400-49fc-11ea-919b-d9e48f70a46d.png">

I think it is because we sending line breaks in the mutation:
![image](https://user-images.githubusercontent.com/22195362/74050840-d0aff480-49fc-11ea-85fe-f57b5a31783e.png)

**Comment by pantharshit00** [comment]
@pimeys would like to take this over at the engine level @Jolg42

**Comment by Jolg42** [comment]
So fixed with https://github.com/prisma/prisma-engine/commit/e7ce8fc5f13fed9dbf19a205f70c74fbb1118569 @pimeys ?
