### ISSUE TITLE
All included 1:1 relations return null

### ISSUE THREAD

**Issue by andres-valdes** [prisma/prisma-client-js#477]
Hi, I’m trying to query for a relation created with a nested create, but the returned model is null.

This is what it looks like `const user = await prisma.users.findOne({ where: { username }, include: { admin } });`

user is `{ ..., admin: null }`

In the database though, my relationships are all there. Am I using this wrong?

**Comment by andres-valdes** [comment]
Fixed by using `@id @default(cuid())` instead of `@id @default(uuid())`

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #434
