### ISSUE TITLE
Explore how generation works with Yarn PnP

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#48]

**Comment by divyenduz** [comment]
The generation just works by creating a `node_modules/@generated/photon` folder. It feels a weird that a `node_modules` folder is created when it is not needed by `yarn pnp` but this would be a docs/configuration issue.

**Comment by schickling** [comment]
Is there a reliable way to detect whether the user is using pnp?

**Comment by divyenduz** [comment]
I think existence of [`.pnp.js`](https://yarnpkg.com/lang/en/docs/pnp/) should be enough. Just skimmed through the docs and I think it is always at the same level as where the command is being run.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/1439
