### ISSUE TITLE
Include with filter not working

### ISSUE THREAD

**Issue by Nikxt** [prisma/prisma-client-js#496]
Filtering for a included list is not working like expected.

In the following code, prisma ignores my where condition and returns the full List of test results (Passed and not passed).

```javascript
  const exams = await ctx.prisma.exam.findOne({
    where: args.where,
    include: {
      students: true
      results: {where: {passed: true}}
    }
  });
```

I also tried to use "equals" like below, but still the same full return.
```javascript
results: {where: {passed: {equals: true}}}
```

**Comment by Nikxt** [comment]
Hi, is it possible to send the schema via email ?

**Comment by janpio** [comment]
Of course, schemas@prisma.io works for that.

**Comment by divyenduz** [comment]
Internal note: we did receive this schema (to be kept private) and I assigned Harshit internally

**Comment by Nikxt** [comment]
Is my approach even correct to filter nested relations?
Because I can't find any guidelines for this case.

**Comment by pantharshit00** [comment]
Can you please try this again with the latest version of Prisma? I tried that query out and it is working fine.

I have opened a documentation issue about this here: https://github.com/prisma/prisma/issues/2264

**Comment by Nikxt** [comment]
I tried it out. If I invoke the Prisma function and log my result, it's correct. The filter inside select is working: My object with filtered relations.

But there is still another strange error for me. 

If I return exactly this object inside my graphql-nexus resolver, and watch the result inside graphql playground, it's just the same object but with all relations (filters ignored).

It looks like the correct prisma result is overwritten just before returning from the server. 
Maybe its a nexus-prisma issue now.

**Comment by pantharshit00** [comment]
@Nikxt If you can log the data returned by the client the and verify that it is correct, please feel free to close this issue and open an issue in the nexus repository.

Nexus is currently handled by the labs team at Prisma so that will need to look into this.
