### ISSUE TITLE
Wrong examples on the main page

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [prisma/prisma-client-js#498]
Please take a look at the following examples from the [main page](https://photonjs.prisma.io):

![1](https://user-images.githubusercontent.com/7892779/74765099-01611b00-5294-11ea-84de-451a43c0f444.png)

Wrong result. Should be array of categories, not posts.

![2](https://user-images.githubusercontent.com/7892779/74765107-03c37500-5294-11ea-83ff-5661998bfb75.png)

Completely wrong example. The comment means array of posts. The code means array of user profiles. The TS type means array of categories. The result means array of posts. 🤯

![3](https://user-images.githubusercontent.com/7892779/74765133-0e7e0a00-5294-11ea-96a4-6f458e6ecac9.png)

Wrong comment. The comment mentions the `author` property, but the code and the result don't.

Also I think it's time to update the all examples (**photon**.post**s** -> **prisma**.post, etc.).

**Comment by nikolasburk** [comment]
Thanks a lot for catching those @FluorescentHallucinogen🙏 I just fixed the responses that you pointed out. As for renaming, we're currently already working on a new website and will leave the current website as is (the banner on top in this case provides the context that Photon.js has been renamed).

**Comment by FluorescentHallucinogen** [comment]
@nikolasburk 
> I just fixed the responses that you pointed out.

The problems are not only with responses, but with TS types too.

Just checked

![2-2](https://user-images.githubusercontent.com/7892779/74971619-73bb3200-5431-11ea-9b8b-c5c3c26c7a7c.png)

The TS type should be `Profile` or something like that, not `Category[]`.

Also `id: 1` looks very strange, because IDs in Prisma have the different format.

Using unreal IDs in examples produce funny things like:

![4](https://user-images.githubusercontent.com/7892779/74971634-79187c80-5431-11ea-8d19-61ccaa6606fd.png)

The post with ID `54394` was requested, but the post with ID `cjnymovv3s3ht0a516fhmria8` was returned.

Wrong examples like this may confuse Prisma newcommers.

> we're currently already working on a new website

Hope the new website will use the real demo API with real queries and real responses to avoid things like this, and users will be able to edit and play with any examples right on the website. :wink:

**Comment by 2color** [comment]
Thanks for spotting this @FluorescentHallucinogen.

These have addressed in the new website documentation.
