### ISSUE TITLE
Rename "forced transaction mode" flag

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#499]
Right now this is implemented as `forceTransactions`. When https://github.com/prisma/specs/issues/386 was closed/specced, this should be renamed to what was decided to enable our users to use it.

**Comment by timsuchanek** [comment]
I implemented the `forceTransactions` property for now.

**Comment by timsuchanek** [comment]
We wait for the spec here to know to what it has to be renamed.

**Comment by janpio** [comment]
Name was accepted and will be documented as such.
