### ISSUE TITLE
Test Prisma Client with pgBouncer

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#500]
After https://github.com/prisma/prisma-client-js/issues/499 is implemented we should test if our configuration works with different pgBoucner setups.

- DigitalOcean: https://www.digitalocean.com/docs/databases/postgresql/how-to/manage-connection-pools/
- Heroku: ???
- Local pgBouncer setup via Docker
- ???

**Comment by divyenduz** [comment]
Exploring here: 

https://github.com/divyendu-test/p2-bouncer

**Comment by divyenduz** [comment]
DO, Docker + pgBouncer exist in e2e tests now: https://github.com/prisma/prisma2-e2e-tests/tree/master/databases

**Comment by janpio** [comment]
Closing in favor of https://github.com/prisma/prisma2-e2e-tests/issues/165
