### ISSUE TITLE
Print query parameters

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#504]
As of now, we only print the query when using

```ts
new PrismaClient({
  log: ['query']
})
```

We only print the sql query generated for the js queries. However, we should also print the parameters.

**Comment by timsuchanek** [comment]
As this might be a security concern, we first need to decide, if we want to expose the parameters by default.

**Comment by nikolasburk** [comment]
The docs needed here are for `.on(...)` (?), more info will be provided by @timsuchanek.

**Comment by timsuchanek** [comment]
You can find most of the necessary information here in the spec: https://github.com/prisma/specs/tree/master/prisma-client-js#logging

**Comment by nikolasburk** [comment]
Added docs for logging query parameters here: https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#logging-query-events
