### ISSUE TITLE
@@id doesn't add DMMF id fields to the model

### ISSUE THREAD

**Issue by maticzav** [prisma/prisma-client-js#511]
Hey :wave:,

The following model defines `id` fields, but the DMMF in `prisma-client-js` has no field marked as `isId`.

```prisma
model PlaylistTrack {
  PlaylistId Playlist
  TrackId    Track

  @@id([PlaylistId, TrackId])
  @@index([TrackId], name: "IFK_PlaylistTrackTrackId")
}
```

**Comment by pantharshit00** [comment]
They are mentioned in the `idFields` property:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/22195362/74961979-05786e80-5435-11ea-9fbd-02dd7840e3cc.png">

I am not sure what our behaviour should be so I am marking this as a bug for now but you can use this property for now.

**Comment by janpio** [comment]
This is as expected.
