### ISSUE TITLE
Prisma not reading from existing dotenv

### ISSUE THREAD

**Issue by sachaw** [prisma/prisma-client-js#520]
Since the latest prerelease (22), my existing dotenv implementation no longer works, if I place the .env file in the prisma folder, it gets loaded, but It is used by the rest of my application, so I want it to work from the one in my root.

dotenv gets loaded before Prisma is initialized, which used to work but not now.

**Comment by pantharshit00** [comment]
I won't call it a bug as it was a deliberate decision made in https://github.com/prisma/prisma2/issues/1519. You can follow the further discussion that is going on there.
