### ISSUE TITLE
Type 'string' is not assignable to type 'PostWhereUniqueInput | null | undefined'

### ISSUE THREAD

**Issue by tre-dev** [prisma/prisma-client-js#521]
Before upgrading to v22, on v21, it worked fine when using `string` as argument for `after` or `before`, i.e:

`prisma.post.findMany({ where: { id }, after: 'uniquePostId')`

But now, I have to do the following (`PostWhereUniqueInput`):

`prisma.post.findMany({ where: { id }, after: { id: 'uniquePostId' })`

Is there a reason for this change?

Also, here is the type definition of the required field:

```
export type PostWhereUniqueInput = {
  id?: string | null
}
```

**Comment by pantharshit00** [comment]
Yes, this change is expected as we released support for composite unique indexes.

Check out our release notes for more information: https://github.com/prisma/prisma2/releases/tag/2.0.0-preview023
