### ISSUE TITLE
Optimization of `findOne` queries

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#523]
This issue tracks the implementation of optimizing the `findOne` queries as described in https://github.com/prisma/specs/issues/242#issuecomment-548382431

This can be tackled, once https://github.com/prisma/photonjs/issues/284 is done.

**Comment by Manborough** [comment]
I can't seem to find any notes on the matter, but does a FluentApi call using findOne like this:

`const planters = await prisma.room.findOne({
				where: {
					id: obj.id
				}}).planters()`

use the findOne batching?

**Comment by timsuchanek** [comment]
@Manborough yes it does!
Note, that the batching only kicks in under the following conditions:
- The same model
- The same where filter (same fields, but obviously different values)
- The same selection set


So this will be batched:
```ts
const planters = await Promise.all([
  prisma.room.findOne({ where: { id: 1 }}).planters(),
  prisma.room.findOne({ where: { id: 2 }}).planters()
])
```

This will not be batched:
```ts
const planters = await Promise.all([
  prisma.room.findOne({ where: { id: 1 }}),
  prisma.room.findOne({ where: { id: 2 }}).planters()
])
```

**Comment by timsuchanek** [comment]
We have finished this in the latest alpha.
You can try it out with `@prisma/cli@alpha` and `@prisma/client@alpha`.
Have fun!
