### ISSUE TITLE
Prisma Client JS apis for browser

### ISSUE THREAD

**Issue by ansarizafar** [prisma/prisma-client-js#54]
It would be great If prisma2 can generate photon api for the browser. We can use Postgres row based permissions for security. The browser apis will allow developers to quickly build an application without using rest/graphql endpoint.

**Comment by matthewmueller** [comment]
Hey @ansarizafar! Thanks for your feedback! I've actually implemented a similar system in the past, so I can see the usefulness. 

Once we add more database-specific features (postgres' row-level security) to our datamodel, I can see this being a viable option.

**Comment by thebiglabasky** [comment]
Hi, as @matthewmueller mentioned, we are focusing right now on database-level support which pushes these kinds of integrations further down the road and unlikely to be tackled anytime soon.

I will thus close this issue. Meanwhile we advocate for using Express, Apollo or Nexus Framework or rely on our [examples](https://github.com/prisma/prisma-examples/) to get started faster and have more control over their setup.

Thank you!
