### ISSUE TITLE
Add configuration option to throw error if `findOne` result doesn't exist.

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma-client-js#547]
There are apps where you always want `findOne` to throw an error if the requested item doesn't exist. The error can then easily be handled in a controller abstraction and return a 404 for the request.

It'd be fine for the PrismaClient constructor to accept this option. Perhaps `throwNotFound` or something

**Comment by timsuchanek** [comment]
We're now working on this, feedback for the API design welcome https://github.com/prisma/prisma-client-js/issues/708#issuecomment-757852829

**Comment by pantharshit00** [comment]
Closing in favor of #708
