### ISSUE TITLE
Mutating a `Float` sometimes results on sightly different value written to Postgres

### ISSUE THREAD

**Issue by snake575** [prisma/prisma-client-js#555]
Hi, I found a problem that may be related to #537

I'm using the same reproduction repo with a different amount `0.00071832` on the mutation.

[snake575/prisma-float-error](https://github.com/snake575/prisma-float-error)

Mutation:
```js
const transaction = await prisma.transaction.create({
  data: {
    amount: 0.00071832,
    currency: 'BTC',
  },
})
console.log({ transaction })
```

Returns correct amount:
```js
{ transaction: { id: 2, amount: 0.00071832, currency: 'BTC' } }
```

But a sightly different value is written to Postgres:
```
2020-03-06 17:00:27.304 -03 [33] LOG: execute s0: INSERT INTO "public"."Transaction" ("amount","currency") VALUES ($1,$2) RETURNING "public"."Transaction"."id"
2020-03-06 17:00:27.304 -03 [33] DETAIL: parameters: $1 = '0.0007183200000000001', $2 = 'BTC
```

**Comment by tomhoule** [comment]
Fixed in alpha 927 - it will be in the next preview :) Also see https://github.com/prisma/prisma-client-js/issues/537

**Comment by janpio** [comment]
@snake575 Can you maybe try out with alpha 927 and report back if the error is fixed for you? That would be awesome.

**Comment by snake575** [comment]
@janpio I confirm it's fixed on alpha 927, it's also fixed on preview-24 😃

**Comment by janpio** [comment]
Wonderful. Thanks! 🐰
