### ISSUE TITLE
Best practice to handle (dynamically) reserved words?

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma-client-js#557]
Consider the following: I have two models in my schema file:

* `WorkspaceTask` (a task that is directly associated to a workspace)
* `WorkspaceTaskFilter` (a filter that the user can apply to their workspace to filter tasks by this filter)
  * Some examples:
    * "All tasks"
    * "Overdue tasks"
    * ...

Since the Prisma Client itself generates `Filter`s  my model `WorkspaceTask` gets an additional `WorkspaceTaskFilter` and my model `WorkspaceTaskFilter` gets an additional `WorkspaceTaskFilterFilter` (yay).

Because of this I had to rename my `WorkspaceTaskFilter` to `WorkspaceTasksFilter` due to the collision with the other `WorkspaceTaskFilter` generated out of `WorkspaceTask`.

Would you consider this a best or bad practice to just rename my models accordingly to get the generated code to work correctly?

Also the generation **worked**. Maybe one should get an error, in that case, that the generated Prisma Client broke? Because when I want to import it it tells me that `WorkspaceTaskFilter` was declared twice.

May be connected to #528 

Edit: Oh, and in this case `Filter` is not a "reserved word" but it could be one?

**Comment by pantharshit00** [comment]
This sounds like a bug to me. We should fix this :)

**Comment by pantharshit00** [comment]
Schema for a minimal reproduction:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model WorkspaceTask {
  id String @id @default(cuid())
  filters WorkspaceTaskFilter[]
} 

model WorkspaceTaskFilter {
  id String @id @default(cuid())
  workspace WorkspaceTask
}
```


Might be related that we fixed a similar bug for enum but with a different argument: https://github.com/prisma/prisma-client-js/issues/363

**Comment by Jolg42** [comment]
Thank you! I added `modelNameFilter` to the denylist.

**Comment by Jolg42** [comment]
So the current denylist is here https://github.com/prisma/prisma/blob/c80d262778d98e9bc833ec60cf152e26f055ebe3/src/packages/client/src/generation/generateClient.ts#L346-L498

There will be a dedicated section about that in the docs in the future :)

So renaming is a good way to avoid this problem, either in the database or in the model with `@@map` like this https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#naming-models
