### ISSUE TITLE
prisma2 generate always uses yarn even if you're using NPM in your project

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-js#561]
If you're an NPM user, you'll get a `package-lock.json` and `package.json`. Running `prisma2 generate` does not pick up that we're using NPM and always uses yarn. This ends up creating both a `package-lock.json` file and a `yarn.lock` file.

Full repro here: https://github.com/prisma/prisma-client-js/issues/560

**Comment by Jolg42** [comment]
We may want to use https://github.com/sindresorhus/has-yarn in `generate`

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/prisma-client-js/issues/560

**Comment by Jolg42** [comment]
fixed in alpha 920!
