### ISSUE TITLE
No more *GetSelectPayload exported by the client

### ISSUE THREAD

**Issue by samrith-s** [prisma/prisma-client-js#564]
Hey,

Before installing `@prisma/client@2.0.0-alpha.904` and `prisma2@2.0.0-alpha.904`, I used to get a `<Collection>GetSelectPayload` for every model.

I used to use it to annotate the arguments to my functions like so:
```typescript
function checkUserTroup(user: UserGetSelectPayload<{ troups: true }>): boolean {
    return !!user.troups.length;
}
```

Now, `@prisma/client` doesn't have any export called `UserGetSelectPayload`. So I tried this approach:
```typescript
function checkUserTroup(user: UserGetPayload<UserArgs['select']['troups']>): boolean {
    return !!user.troups.length;
}
```

But this doesn't work and I get the following errors, which are fairly understandable:
![image](https://user-images.githubusercontent.com/9032162/76528166-a96f9b80-6470-11ea-8bf8-e541a5275497.png)

My question is, is there any replacement for `*GetSelectPayload`?

**Comment by Jolg42** [comment]
Thank you for creating this issue 👍 

So indeed `UserGetSelectPayload` was [exported before](https://github.com/prisma/prisma-client-js/blob/3f1c39975afbd3626d4b24d3b95f1437e1293829/packages/photon/src/generation/TSClient.ts#L985) and [documented here](https://github.com/prisma/prisma2/blob/5409fb75e3347334e1f7b1f837cbc83facf7dfb1/docs/prisma-client-js/generated-types.md#L67) but disappeared after the dynamic client changes by @timsuchanek 

Now [there is indeed UserGetPayload](https://github.com/prisma/prisma-client-js/blob/d8e32bad19f7fa285ba6b69a0d80050bf669788f/packages/photon/src/generation/TSClient.ts#L592)

I don't know any replacement or workaround yet, @timsuchanek will be the best person for that but he's on holiday at the moment. We'll get back as soon as possible 😃

**Comment by nikolasburk** [comment]
Hey @samrith-s, thanks for opening this issue. I just [updated the docs](https://github.com/prisma/prisma2/pull/1900). This is how the new type `UserGetPayload` can be used:

```ts
import { UserGetPayload } from "@prisma/client";

// Define a type that includes the relation to `Post`
type UserWithPosts = UserGetPayload<{ 
  include: { posts: true } 
}>

// Define a type that only contains a subset of the scalar fields
type UserPersonalData = UserGetPayload<{
  select: { email: true; name: true }
}>
```

**Comment by samrith-s** [comment]
Gotcha, thanks! 😄
