### ISSUE TITLE
Export the current Prisma version

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-js#573]
I'd like to be able to access the current Prisma version:

```
import { version } from "PrismaClient"

console.log(version)
```

which would print

```
2.0.0-alpha.785
```

The main use case for this is to [verify our deployment platforms are not out of sync](https://github.com/prisma/prisma2-e2e-tests/issues/51) and actually test the latest Prisma version. Also, we think it may be useful if the version string is printed somewhere (maybe additionally in a comment in the first few lines), so users can easily verify that the generated code is indeed generated by a given Prisma version.

**Comment by timsuchanek** [comment]
Thanks @steebchen.
We now export the following:
```ts

/**
 * Query Engine version: 4ff8379527ec7797e7bb5b55d374f82f5812a6f9
 * Prisma Client JS version: 2.0.0-alpha.913
 */
exports.version = {
  engine: "4ff8379527ec7797e7bb5b55d374f82f5812a6f9",
  client: "2.0.0-alpha.913"
}
```

You can try it out in the latest alpha.
