### ISSUE TITLE
Error when calling prisma delete many.

### ISSUE THREAD

**Issue by nnennajohn** [prisma/prisma-client-js#575]
I got the following error when trying to run prisma.user.deleteMany({}).  I get the following error. I think it has to do with having multiple back relation on the user model. Is there a way to bypass this? 

I am on prisma-client-js@2.0.0-preview024

Thanks.

<img width="1012" alt="Screen Shot 2020-03-15 at 11 45 02 PM" src="https://user-images.githubusercontent.com/1761197/76729856-52d7bb00-6717-11ea-91ad-a95467e41f99.png">

**Comment by nnennajohn** [comment]
Also errors in prisma studio:

my back-relations are

  ```
  profileViews     User[]   @relation("UserProfileViews")
  followers    User[]  @relation(name: "UserFollows")
  following User[]  @relation(name: "UserFollows")
```


<img width="1676" alt="Screen Shot 2020-03-16 at 12 46 52 AM" src="https://user-images.githubusercontent.com/1761197/76734236-b8c84080-671f-11ea-9151-be8421609c06.png">

**Comment by pantharshit00** [comment]
@nnennajohn Can you please share your client call and the datamodel? That will help us in reproducing this issue so that we can identify the bug here 🙏

**Comment by nnennajohn** [comment]
@pantharshit00 Thanks for looking at this. 

Given the below

`
model User {
  id               String  @default(cuid()) @id
  email            String   @default("") @unique
  createdAt        DateTime @default(now())
  updatedAt        DateTime @default(now())
 notificationsSetting UserNotificationsSettings? @relation("UserNotificationsSettings")
}

model UserNotificationsSettings {
  id String  @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @default(now())
  user User @relation("UserNotificationsSettings")
  message String
}
`

Running prisma.user.deleteMany(), throws the following error or the error above. Removing notificationsSetting gets rid of the error. The same for when I use a back_relation as done in the docs.

<img width="742" alt="Screen Shot 2020-03-20 at 10 52 50 PM" src="https://user-images.githubusercontent.com/1761197/77220467-8f335e80-6afd-11ea-9d24-17b3c35c4734.png">

**Comment by alexvilchis** [comment]
I have this same issue on beta. It seems that the `deleteMany` invocation is trying to delete the child record (`UserNotificationsSettings`) even when it is null.

My model is something like this:

```

model Patient {
  id               String             @id @default(cuid())
  createdAt        DateTime           @default(now())
  updatedAt        DateTime           @updatedAt
  legacyId         String             @unique
  recordId         String?
  user             User @relation(fields: [userId], references: [id])
  userId String
}



model User {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  username  String   @unique
  password  String
}
```

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma-client-js/issues/609

This is happening when one side of relation is required but the other side is optional.
