### ISSUE TITLE
Provide support for a "find or create" feature

### ISSUE THREAD

**Issue by cannikin** [prisma/prisma-client-js#583]
I'd love support of some sort of "first or create" function. There is an equivalent in Rails called `first_or_create` and it either returns an existing record, if it exists, or creates a new record and then returns that. It also lets you find by any field you want, not just unique ones. https://guides.rubyonrails.org/v3.2.13/active_record_querying.html#first_or_create

```ruby
User.where(:email => 'rob@me.com').first_or_create(:name => 'Rob')
```

It combines the fields you put in the `where` with the fields you gave to `first_or_create` when it goes to create the record.

ClientJS currently has `upsert` but it requires an `update` param, which I don’t care about, and you can only `where` on unique fields.

Right now as a workaround I’m doing:

```javascript
const existing = await db.user.findMany({ where: { email: 'admin@email.com' }})
if (!existing.length) {
  await db.user.create({data: { name: 'Admin', email: 'admin@email.com' }})
}
```

And I feel all gross. :)

@schickling mentioned in a thread on Slack that this will be available soon which would be awesome:

```javascript
await prisma.user
  .findFirst({ lastName: 'Doe' })
  .orCreate({
    firstName: 'Alice',
    lastName: 'Doe',
    email: 'alice@prisma.io',
    profile: { imageUrl: 'http://...', imageSize: 100 },
  })```

**Comment by albertoperdomo** [comment]
Hello @cannikin,

thanks for submitting your feature request!

I think this or similar functionality is being already tracked in https://github.com/prisma/prisma-client-js/issues/85.

I'm closing this issue. Please feel free to leave a comment if you don't think this is addressed in that issue and I will have a look again.
