### ISSUE TITLE
Better error message when generated Client and local Prisma schema are out of sync

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#586]
## Problem

Given the Prisma Client is generated based on the schema information it can happen that the generated Prisma Client gets "out of sync" with the `schema.prisma` file (e.g. when the user forgot to run `prisma generate`). This can result in invalid DB queries being issued which can break the user application.

## Solution

A way to significantly improve the DX in this situation could be to introduce the following behavior: When Prisma Client detects an error that could be caused by it being out of sync, instead of throw an error directly Prisma Client should handle the situation more gracefully. Here's a rough sketch of the possible implementation:

1. Error is detected and caught
2. Client checks whether it's running in local development and therefor has access to the `schema.prisma` file.
   - In case no local schema was found: Throw original error from 1
   - In case a local schema was found: continue with 3
3. Print a more helpful error message by including a schema diff comparing the embedded schema of the client with the local schema (i.e. the source of truth).
4. Additionally Prisma Client could also try validate the Prisma schema with the underlying DB schema (similar to `prisma status` see https://github.com/prisma/specs/issues/400) and include this information in the error message as well.

**Comment by matthewmueller** [comment]
The steps @schickling laid out seem good to me.

If it's too much work to add the diff for #3-#4, we could also say, 

```
Run `prisma status` to see the differences
```

Related: https://github.com/prisma/specs/pull/463

**Comment by timsuchanek** [comment]
This is implemented in `dev` with `prisma doctor`.
For now `prisma doctor` is not part of the official help string, but will soon be added.
