### ISSUE TITLE
Possibly wrong type generation for models with @id & @unique fields

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma-client-js#588]
## Bug description
For some schemas, Prisma Client's autocomplete list is wrong

## How to reproduce

Have a model like so:
```
model User {
  id        String   @id
  email  String   @unique
  name  String
}
```

When I write

```
prisma.user.findMany({
  where: { 
    _
  }
})
```

the possible autocomplete options inside the `where` argument are: `id` & `email`. This is incorrect, because you can only supply one at a time. Passing in both `id` and `email` would lead to a query engine error:
```
Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (email, id)
```

## Expected behavior
The Typescript type of the `where` argument should be `{ id: String } | { email: String }` (aka, accept only one at a time)

## Environment & setup

- OS: macOS Catalina
- Database: PostgresQL
- Prisma CLI Version   : prisma2@2.0.0-alpha.939
- Current platform     : darwin
- Query Engine         : prisma 00c64c12cd73d8943c479d708b3a73003d611413
- Node.js version: v13.10.1

**Comment by madebysid** [comment]
This model would also break:
```
model User {
  @@unique([id, name])

  id    String @default(cuid()) @id
  email String
  name  String
}
```

In this case, the following query is invalid (but Typescript does not complain)
```
prisma.user.findMany({
  where: {
      id: 'ck7ymc7xe0000o80xftlw4rh3',
      id_name: {
          id: 'something',
          name: 'some name',
      },
  }
})
```

where the query engine would fail with:
```
Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (id, id_name).
```

**Comment by pantharshit00** [comment]
Unable to reproduce this with `2.0.0-alpha.973, binary version: 8814060fa684793b73d07dbfccd4b7777b3361ae`

Type generation is correct as if you have multiple two items in `findMany` are there treated to be joined by logical AND and a result is returned.

![image](https://user-images.githubusercontent.com/22195362/77748961-3c026400-7047-11ea-97d1-30a8d18801dd.png)

The second query is not possible as you can't multi-field unique indexes on findMany, you need to use them in findOne

**Comment by madebysid** [comment]
@pantharshit00 You're right, I also just tested with alpha.976 and it seems that error is gone now and `id` and `name` are ANDed. I'm no longer seeing the error I was seeing in alpha.939. Closing!
