### ISSUE TITLE
Update Many in self-referencing relations

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma-client-js#589]
Hi. I wanted to create a doubly linked list (for orderable checklists in prisma) and I created a data model like this:

```
model ChecklistItem {
    id          String              @default(cuid()) @id
    content     String
    status      String
    assignees   ChecklistAssignee[]
    checklist   Checklist
    dueDate     DateTime?
    previousItem ChecklistItem?  @relation(name: "itemLinks")
    nextItem     ChecklistItem?  @relation(name: "itemLinks")
    createdDate DateTime            @default(now())
    updatedDate DateTime            @updatedAt
}
```

If you notice, previousItem and nextItem refer to the same ChecklistItem model with a separate relationtable created.

But, when I try to do an update query like this, it does not work (I am basically trying to change the nextItem pointer of the doubly linked list):

![Screenshot from 2020-03-21 18-53-49](https://user-images.githubusercontent.com/1165845/77227303-5949b500-6ba5-11ea-8d77-02d12a25ad76.png)

I even tried using connect but even that does not work.

![Screenshot from 2020-03-21 18-55-13](https://user-images.githubusercontent.com/1165845/77227319-8302dc00-6ba5-11ea-91c2-5e1a2214dd04.png)

If I see the interface file, I dont see the fields previousItem and nextItem for updateMany

![Screenshot from 2020-03-21 19-04-42](https://user-images.githubusercontent.com/1165845/77227524-efcaa600-6ba6-11ea-87b0-790ca5f2d824.png)

Is this a bug or am I doing something wrong? Thanks.

**Comment by timsuchanek** [comment]
Thanks for reporting @tvvignesh 
`updateMany` is expected to not be able to manipulate relations.
If you want to manipulate relations, please use the `update` method.
This applies both for normal relations as for self-relations, as in your example.
Btw to support the new relations syntax, you need to write your schema like so:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model ChecklistItem {
  id             String         @default(cuid()) @id
  content        String
  status         String
  dueDate        DateTime?
  previousItemId String?
  previousItem   ChecklistItem? @relation("itemLinks", fields: [previousItemId])
  nextItem       ChecklistItem? @relation("itemLinks", references: [id])
  createdDate    DateTime       @default(now())
  updatedDate    DateTime       @updatedAt
}
```
