### ISSUE TITLE
Support for JSON/JSONB

### ISSUE THREAD

**Issue by newtack** [prisma/prisma-client-js#60]
Does Prisma Client support these types? If not, what are the plans to support them going forward?

**Comment by matthewmueller** [comment]
Hi @newtack! Yes, we definitely want to support these features in the near future.

**Comment by schickling** [comment]
This is currently being specced out here: https://github.com/prisma/specs/issues/8

**Comment by AntoinedeChassey** [comment]
Hi guys,
Has this feature been implemented?
Thanks.

**Comment by janpio** [comment]
Closing this one as duplicate of https://github.com/prisma/prisma/issues/186 which has more rections <3
