### ISSUE TITLE
Error when creating a record with relations: syntax error at or near ")"

### ISSUE THREAD

**Issue by odensc** [prisma/prisma-client-js#617]
## Bug description
When I create a record that has a relation, I get the following error:

```js
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error at or near \")\"", detail: None, hint: None, position: Some(Original(57)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1145), routine: Some("scanner_yyerror") }) }) })
    at PrismaClientFetcher.request (/home/oden/Dev/Templates/test/node_modules/@prisma/client/runtime/index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## How to reproduce
I created a minimal repro to demonstrate the issue: https://github.com/odensc/prisma-repro

1. Clone the repo
2. Create the Postgres database and table
3. `npm install`
4. `prisma2 migrate up --experimental`
5. `node index.js`
6. The script should error.

Seems like the issue is here:

```sql
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE () IN (($1)) OFFSET $2
```

You can see the WHERE parameter list is empty.

## Expected behavior
The create call should work and returns the new record.

## Prisma information 
All included in the repo.

## Environment & setup

- OS: Arch Linux
- Database: Postgres 12.2
- Prisma version: 2.0.0-beta.1
- Node.js version: 13.8.0

**Comment by odensc** [comment]
Same error as #578 it seems but different data model.

**Comment by odensc** [comment]
I traced this back to the breaking relation change in [`2.0.0-beta.1`](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1).

Apparently I decided to start fiddling around literally minutes after `2.0.0-beta.1` was released, but before the GitHub docs were redirected to prisma.io - so I was working off the old documentation regarding relations. Just unlucky :)

So I suppose the real issue is that the error message could be more helpful :+1: Would you prefer I open a new issue for that, or edit this one?

**Comment by mavilein** [comment]
This will be fixed once we have improved the validation of `@relation`. Currently the schema validation does not fail when `fields` is required but not specified.

**Comment by janpio** [comment]
You should get an error during `generate` now.

**Comment by odensc** [comment]
@janpio Can confirm. Thanks!
