### ISSUE TITLE
Bug on Windows when running prisma generate

### ISSUE THREAD

**Issue by decosvaldo** [prisma/prisma-client-js#636]
## Bug description

Dear developers, this is a small bug, but I'm running the prisma client inside my Documents folder on Windows and turns out that I have spaces on my username folder. Ex: C:\Users\Andre Luiz\Documents\prismafolder\node_modules. And when I run prisma generate inside it, it will display an error about the spaces on the folder name.

## How to reproduce

Just run npx prisma generate inside a folder where it's parent has a space on the name. If you move the application to a different folder, everything works fine.

## Expected behavior

No error.

## Prisma information

@prisma/cli          : 2.0.0-beta.1
Current platform     : windows
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at C:\80Minutos-prisma\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at C:\80Minutos-prisma\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at C:\80Minutos-prisma\node_modules\@prisma\cli\introspection-engine-windows.exe)

## Environment & setup

- Windows

**Comment by janpio** [comment]
What is the error message you are getting? There might already be an issue for this over at https://github.com/prisma/prisma/issues/1973

**Comment by decosvaldo** [comment]
You're correct. Is it the same thing that the other issue you presented.
Thanks

André Luiz Paiz

________________________________
De: Jan Piotrowski <notifications@github.com>
Enviado: quarta-feira, 8 de abril de 2020 19:25
Para: prisma/prisma-client-js
Cc: decosvaldo; Author
Assunto: Re: [prisma/prisma-client-js] Bug on Windows when running prisma generate (#636)


What is the error message you are getting? There might already be an issue for this over at prisma/prisma#1973<https://github.com/prisma/prisma/issues/1973>
