### ISSUE TITLE
All query not resolved since new Prisma version

### ISSUE THREAD

**Issue by Suniron** [prisma/prisma-client-js#638]
## Bug description

All of Prisma queries arn't resolved ( stucked! ) since i've uptaded the Prisma version to the latest (i followed instructions in new documentation).

My machine is a Rasperry Pi 4 with 4gb RAM and i upgraded the differents binaries with prisma-engine and latest version of Rust, i think's it's ok for this.

## How to reproduce

Steps to reproduce the behavior on my raspberry:
1. Update Rust Langage and Prisma-engine to the latest,
2. Build Prisma binaries and export into env variable (like old working install),
3. Do a `npx prisma generate` into the project folder,
4. Start express server where Prisma is used,
5. Test a server request without using prisma: it's OK,
6. Test a request using Prisma Client: it's stucked in query `await prisma.word.findMany({});` (a console log after this isn't showed), i dont' see any error message, just stucked....
7. If i try again with env variable DEBUG="*", i go the debug message bellow.

Debug message:
```
  prisma-client Prisma Client call: +55s
  prisma-client prisma.word.findMany({}) +1ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManyWord {
  prisma-client     id
  prisma-client     description
  prisma-client     isValid
  prisma-client     subtitle
  prisma-client     title
  prisma-client   }
  prisma-client }
  prisma-client  +1ms
```

## Expected behavior

I would like that's different Prisma requests work fine like before upgrading Prisma Versio to the beta.

## Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

model Word {
  id            String         @default(cuid()) @id
  description   String
  isValid       Boolean        @default(false)
  subtitle      String
  title         String
  reportedWords ReportedWord[]
}

model ReportedWord {
  id      String @default(cuid()) @id
  word    Word   @relation(fields: [wordId], references: [id])
  wordId  String
  contact String
  reason  String
}

model User {
  id       String @default(cuid()) @id
  email    String @unique
  password String
  role     Role   @default(USER)
}

// -- ENUM --
enum Role {
  USER
  ADMIN
}
```

## Environment & setup

- OS: Ubuntu Server 18.10 64 Bits
- Database: PostgreSQL
- Prisma version: "@prisma/cli": "^2.0.0-beta.1",
- Node.js version: v13.11.0

Thank's a lot by advance ! 

(Sorry for my english 😢 )

**Comment by pguilbault** [comment]
I had the same issue since the `2.0.0-alpha.1036` release but everything has just been fixed with the `2.0.0-alpha.1046` and the `2.0.0-beta.2` releases.

**Comment by Suniron** [comment]
Thank's for your answer !

Mmmh.. I see that `prisma.yml` seem's mandatory with this latest version.

I have to create this file and try after :-)

**Comment by pguilbault** [comment]
Are you sure you are using the right version of Prisma ? Because `prisma.yml` refers to the Prisma1's configuration file.
What is the output of `npx prisma -v` ?

**Comment by Suniron** [comment]
OK, it's my bad.

I'm trying now and I see that it's OK! 

Thanks for your help, I'm really happy 🎉
