### ISSUE TITLE
Improve documentation for query possibilities

### ISSUE THREAD

**Issue by michael-hillmann** [prisma/prisma-client-js#644]
## Bug description

I'm a very beginner, so I hope I did something wrong. I want to use the function `findMany()` with a `where` clause with multiple comparisons, combined with `OR`. Like:

`where (name contains "pattern" OR email contains "pattern")`

The results are wrong because the query uses `AND` instead of `OR`.

## How to reproduce

Try to find data within a single model where any of 2 (or more) conditions are valid.

SQL query contains AND within the WHERE clause

## Expected behavior

SQL query with OR within the WHERE clause

## Prisma information

The resolver function in JavaScript:

~~~
    users(parent, args, { prisma }, info) {
        const where = args.query ? {
            where: {
                firstname: { contains: args.query },
                OR: { lastname: { contains: args.query },
                OR: { email: { contains: args.query } } }
            }
          } : {}
        return prisma.user.findMany(where)
    },
~~~

Log Output (query):

~~~
prisma:query SELECT `web_graphql`.`User`.`id`, `web_graphql`.`User`.`email`, `web_graphql`.`User`.`firstname`, `web_graphql`.`User`.`lastname`, `web_graphql`.`User`.`company`, `web_graphql`.`User`.`phone` FROM `web_graphql`.`User` WHERE ((`web_graphql`.`User`.`email` LIKE ? AND `web_graphql`.`User`.`lastname` LIKE ?) AND `web_graphql`.`User`.`firstname` LIKE ?)
~~~

## Environment & setup

@prisma/cli: 2.0.0-beta.1
Current platform: windows
Query Engine: prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203
Database: MySQL 8.0.19
Node.js version: v12.16.1

**Comment by michael-hillmann** [comment]
Sorry, I got it (with some investigation into the code). My query was wrong.
Just for reference: the correct one is:

~~~
    users(parent, args, { prisma }, info) {
        const where = args.query ? {
            where: {
                OR: [
                    { firstname: { contains: args.query } },
                    { lastname: { contains: args.query } },
                    { email: { contains: args.query } }
                ]
            }
          } : {}
        return prisma.user.findMany(where)
    },
~~~

Maybe we add some descriptions of the query possibilities into the new docs (e.g. contains, OR, etc..)?
Well, but I'm just a pure newbie ;-)

**Comment by pantharshit00** [comment]
Yes, there is already an issue about this: https://github.com/prisma/prisma/issues/2126

Going to close this as a duplicate.
