### ISSUE TITLE
Rename FindOneModelArgs & FindManyModelArgs to ModelFindOneArgs and ModelFindManyArgs

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma-client-js#647]
## Problem

It's currently difficult to guess the name of a Typescript Type because they are inconsistent on whether the model name comes first or second.

All types except for `FindOneModelArgs` and `FindManyModelArgs` start with the model like `Model...`

## Solution
- Rename `FindOneModelArgs` to `ModelFindOneArgs`
- Rename `FindManyModelArgs` to `ModelFindManyArgs`

**Comment by williamluke4** [comment]
Changes
-`GroupBy${modelName}Args`
+`${modelName}GroupByArgs`

-`Aggregate${modelName}Args`
+`${modelName}AggregateArgs`

-`FindMany${name}Args`
+`${name}FindManyArgs`

-`FindUnique${modelName}Args`
+`${modelName}FindUniqueArgs`

-`FindFirst${modelName}Args`
+`${modelName}FindFirstArgs`
