### ISSUE TITLE
Prisma Client triggers or lifecycle events 

### ISSUE THREAD

**Issue by markrieth** [prisma/prisma-client-js#653]
## Problem
Prisma Client lacks observable lifecycle events or database triggers. Popular alternatives to prisma (and even databases themselves) have these as mature and well documented features. 
For example, [Hasura](https://hasura.io/docs/1.0/graphql/manual/event-triggers/index.html) and [Sequelize](https://sequelize.org/master/manual/hooks.html). Having triggers / events is important because it opens up huge possibilities with the prisma-nexus plugin. The goal would be to leverage the code reduction and API consistency that nexus allows without having to tap into a custom mutation for seemingly every case but the most absolutely simplified. Not to mention data validation. 

## Solution
Prisma Client should have a way to define functions before and after crud operations. Here is an example that I thought of which would be pretty common. The Sequelize link I posted above also has plenty of examples and concepts, basically an instruction guide on what to include. 
```js
prisma = new PrismaClient();
prisma.setTriggers(prisma => ({
  beforeOrderCreate: async (args: OrderCreateArgs): Promise<OrderCreateArgs> => {
  const grandTotal = calcGrandTotal(args.data.lineItems.create);
  // Error can be thrown here
  await processPayment(grandTotal, args.data.user.connect.id);
  return {
    ...args, 
    { 
      data: {
        ...args.data, 
        grandTotal 
      }
    }
  })
  afterOrderCreate: async (order: Order): Promise<void> => {
    const user = await prisma.order.findOne({ where: { id: order.id } }).user();
    if (user.acceptsEmail) {
       await sendEmailToCustomer(order.id, order.grandTotal, user.name);
    }
  },
  afterOrderUpdate: async (newOrder: Order, oldOrder: Order): Promise<void> => {
    if (newOrder.grandTotal !== oldOrder.grandTotal) {
      await prisma.creditNote.create({
        data: {
          amount: newOrder.grandTotal - oldOrder.grandTotal,
          order: { connect: { id: newOrder.id }
        }
      }
    }
  }
}))
```

**Comment by schickling** [comment]
Thanks a lot for raising this issue. This is definitely something we've thought about before (e.g. here https://github.com/prisma/specs/issues/444).

**Comment by markrieth** [comment]
I see ok. I was thinking that there are a handful of common cases for the "before" functions (auth, validation, derived fields). But really, prisma doesn't _need_ to consider those uses. Simply having a synchronous (and possibly async) before and after would open a window to implement those things. If you could `prisma.setTriggers` in the context creation function (Apollo Server), then you would have full access to the request context (auth info) and dataSources (for REST calls) inside your prisma triggers. This means *anything* is possible inside the triggers, and you can (dare I say ***should***?) reduce your application to nothing more than protected, auto-generated crud operations (nexus) and business logic inside event triggers to enhance the auto-generated. So you write code where you need to, *and only where you need to*.

**Comment by pie6k** [comment]
I'm also looking for this feature. I need to process the data on the backend side in some sort of queue, where I'd like to watch for status changes of entities and perform some operations.

I could technically do it just after I perform updates, but the goal of my architecture is to make processing fully independent from CRUD implementation

**Comment by chareice** [comment]
Any Progress? It's Important.

**Comment by pantharshit00** [comment]
@chareice I think you can use a Prisma middleware for this now: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/middleware

**Comment by timsuchanek** [comment]
This is covered by middlewares. If your use-case might not be supported, please create a separate issue.
