### ISSUE TITLE
findMany / OR accepts non-array value - should only accept arrays

### ISSUE THREAD

**Issue by mhwelander** [prisma/prisma-client-js#657]
## Bug description

`findMany` accepts a non-array value when filtering with `OR` even though `OR` requires an array. 

The following is 'allowed' but does NOT return the expected results:

```
  const orIncorrect = await prisma.post.findMany({
    orderBy: {
      id: 'asc'
    },
    where: {
      OR: {
        title: {
          equals: "Prisma makes databases easy"
        },
        authorId: {
          equals: 2
        }
      }
    }
  });
```

Correct syntax is: 

 ```
 const orCorrect = await prisma.post.findMany({
    orderBy: {
      id: 'asc'
    },
    where: {
      OR: [{
        title: {
          equals: "Prisma makes databases easy"
        },
      }, {
        authorId: {
          equals: 2
        }
      }]
    }
  })
```

## Expected behavior

`OR` does not accept non-array value.

## Prisma information

Schema from TypeScript starter project (https://www.prisma.io/docs/getting-started/quickstart?lang=typescript):

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @default(autoincrement()) @id
  published Boolean @default(false)
  title     String
  User      User?   @relation(fields: [authorId], references: [id])
}

model User {
  email   String   @unique
  id      Int      @default(autoincrement()) @id
  name    String?
  Post    Post[]
  Profile Profile?
}

model Profile {
  bio    String?
  id     Int     @default(autoincrement()) @id
  userId String  @unique
  User   User    @relation(fields: [userId], references: [id])
}
```

## Environment & setup

- Prisma version: 2.0.0-beta.2

**Comment by timsuchanek** [comment]
Thanks for reporting!
Although the behavior is very ugly, it's the expected behavior right now.
Therefore I remove the bug label.
This is for sure something we can change, just a bit of more thinking and product work is needed.

**Comment by nikolasburk** [comment]
Here's the relevant [internal discussion](https://prisma-company.slack.com/archives/CEYCG2MCN/p1587377224017400).

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
