### ISSUE TITLE
unable delete items

### ISSUE THREAD

**Issue by calidion** [prisma/prisma-client-js#659]
## Problem

```
    Invalid `prisma.user.delete()` invocation:
    Error occurred during query execution:
    ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: ForeignKey } })

```

**Comment by pantharshit00** [comment]
Hi @calidion 

Can you please provide a reproduction for this? Share your database schema, Prisma schema and which query you are trying to perform.

Related: https://github.com/prisma/prisma-client-js/issues/612

**Comment by calidion** [comment]
changed relationship and works now.
