### ISSUE TITLE
Update fields with arithmetical expressions

### ISSUE THREAD

**Issue by unlight** [prisma/prisma-client-js#662]
## Problem
For example, I have model:
```
model Article {
    id  String  @id  @default(cuid())
    title  String
    favoritesCount  Int  @default(0)
}
```
How can I increment `favoritesCount` field by one statement?

Equivalent SQL update expression:

```
update Article set favoritesCount = favoritesCount + 1 where id = 'ck98sw9cc0006awwz4v1ks665'
```

**Comment by pantharshit00** [comment]
This is something that is not covered by the current client API. You will need to use `prisma.raw` to workaround it for now.

Please follow https://github.com/prisma/prisma-client-js/issues/655 for this feature. I am going to close this as a duplicate.
