### ISSUE TITLE
Does not work with yarn workspace

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#664]
If I have a simple workspace setup like this:
```bash
project1
  prisma
    schema.prisma
  package.json <- includes @prisma/client
project2
  package.json
package.json
```

This includes the workspaces `project1` and `project2`, the postinstall hook does not succeed when doing `yarn install` in the parent directory.

This is the case, because `yarn install` unfortunately doesn't give the `postinstall` hook any hint, that it's needed by `project1`, therefore the `schema.prisma` file can't be found.

A solution for this can be, to look out for the env var `INIT_CWD`, which would in this case point to the root of the project.

From there we can execute `yarn workspaces info --json`, which lists out the workspaces. We can then look into these workspaces to find the `schema.prisma` file.

**Comment by timsuchanek** [comment]
This has been fixed in the latest alpha.

**Comment by yovanoc** [comment]
Just a random question: isn't better to have the prisma/ folder at the same level of the packages/ one, and not in a single project?

**Comment by timsuchanek** [comment]
You could for sure set your project up like that. However, different people have different preferences, so we need to support as many as possible.

**Comment by yovanoc** [comment]
yes I agree but I was thinking about that. If you need prisma in multiple packages in need to be one level higher

**Comment by timsuchanek** [comment]
Yes, we should also create a guide how to optimally set up Prisma with yarn workspaces, including your suggestion.

**Comment by yovanoc** [comment]
Yes, and I created that issue one year ago: https://github.com/prisma/prisma/issues/400

I think it could be a good idea, to have a guide for this. Docker or not but at least for workspaces. Yarn berry will bring people here too I think :)
