### ISSUE TITLE
Using findOne with include does not resolve relation when using CompoundUniqueInput

### ISSUE THREAD

**Issue by martinnirtl** [prisma/prisma-client-js#668]
## Bug description

Using `findOne` with `include` does not resolve relation when using `CompoundUniqueInput`. 

## How to reproduce

The following code would not make author resolvable: 
```js
  const postWithAuthor = await prisma.post.findOne({
    where: {
      title_authorId: {
        authorId: 0,
        title: "hello world",
      },
    },
    include: {
      author: true,
    },
  });

  if (!postWithAuthor) {
    throw new Error("no post found");
  }

  console.log(`post from ${postWithAuthor.author.name}`);
``` 

This leads to `Property 'author' does not exist on type 'Post'. Did you mean 'authorId'?`.

## Expected behavior

Expected would be the same behavior as for `findOne` by `id` or `findMany`, where `include` would lead to resolved relation.

## Prisma information

Database was initialized with `prisma migrate`:

```prisma
model User {
  id   Int    @default(autoincrement()) @id
  name String
}

model Post {
  id       Int     @default(autoincrement()) @id
  title    String
  authorId Int
  author   User    @relation(fields: [authorId], references: [id])
  content  String

  @@unique([title, authorId])
}
```

## Environment & setup

- os: macOS
- db: postgres
- prisma cli: 2.0.0-beta.2
- prisma client: 2.0.0-beta.2
- node version: v12.16.1

**Comment by pantharshit00** [comment]
Hello @martinnirtl 

I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/80593217-6a0c0700-8a3e-11ea-80e1-98e220d3d79e.png)


Can you please try this again with `2.0.0-beta.3`? Also, if this is still failing with that version, please send me a sql dump of your database.

**Comment by martinnirtl** [comment]
Hey @pantharshit00 

I tried with `beta.3` and it's still the same. 

<img width="1008" alt="Screen Shot 2020-04-29 at 21 39 04" src="https://user-images.githubusercontent.com/7869930/80639489-60949600-8a62-11ea-816f-badce8c57546.png">

In my case `postWithAuthor` is of type `Post | null`, but should rather be `(Post & { author: User; }) | null`.

As soon as i use `id` for querying, the expected type gets assigned properly:

<img width="690" alt="Screen Shot 2020-04-29 at 21 44 13" src="https://user-images.githubusercontent.com/7869930/80639747-b8cb9800-8a62-11ea-8c72-c58784bfb403.png">

This code works perfectly fine. Do i get something wrong here?

Pls find a pg dump attached.

[pg-dump.txt](https://github.com/prisma/prisma-client-js/files/4554257/pg-dump.txt)

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/80714921-3ea71c00-8b13-11ea-9b35-82c2265e23f8.png)

I still can't reproduce this. Maybe try this again with alpha version, to do so upgrade prisma dependencies to alpha tag and run ` npx prisma generate --experimental`

If you can still reproduce this, please share a git repository with a reproduction of the problem.

**Comment by martinnirtl** [comment]
Just tested with newest version `2.0.0-beta.4` and it works!

Thanks for your effort and help 👍
