### ISSUE TITLE
Shortcut `findOne` api

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#671]
If you have a schema like this, which only has one id field (no compound id):

```prisma
model User {
  id Int @id @default(autoincrement())
  name String
}
```

We can implement a short-cut for the where syntax.

Instead of
```ts
await prisma.user.findOne({ where: { id: 123 }})
```

we can implement the shortcut
```ts
await prisma.user.findOne(123)
```

The same for string-based ids:
```prisma
model Post {
  id String @id @default(cuid())
  title String
}
```

```ts
await prisma.post.findOne('ck9llgg2x000001lbfcv13fjy')
```

This can already be implemented today in TypeScript, as we don't need any change in the Rust Query Engine for this.

**Comment by Sytten** [comment]
I think I still prefer the shortcut `await prisma.user.findOne({ where: 123 })`?

**Comment by timsuchanek** [comment]
That shortcut is possible as well.
This is just about the most minimal case, in which I don't even need the `include` or `select`, which is quite often the case.

**Comment by squirly** [comment]
I feel like this should not be added to the API. Having many different function overloads makes the API harder to understand and reason about. I feel like having exactly one way to do this enough. If users have a significant use case for shortcuts to reduce code, they can make them as needed with wrappers.

Having more overloads and conditions will make the documentation more complex and the generated typings harder to read.

I am also thinking about the precedent this would set for making future API changes. Where would the line be drawn for additional convenience overloads? I feel like having a clear heuristic in the Prisma design docs would help with this.

**Comment by timsuchanek** [comment]
Thanks @squirly for your thoughts. I agree with what you just said. We'll revisit this topic once we work on a new version of the whole Prisma Client API.

**Comment by gothdawid** [comment]
> ```ts
> await prisma.user.findOne(123)
> ```


Good Idea! :D

**Comment by jwld** [comment]
One of my favourite things about the prisma 2 API is the consistency across the various operations. So would be strongly against any changes that go against that.

**Comment by timsuchanek** [comment]
For now, we won't do this, so the issue can be closed.
