### ISSUE TITLE
Investigate Amazon RDS Proxy

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#676]
RDS Proxy, which is in preview now has Postgres support https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-rds-proxy-with-postgresql-compatibility-preview/

We should investigate if Prisma Client works with RDS Proxy.

**Comment by dajinchu** [comment]
I'm able to run prisma with RDS proxy.

Caveats:
- Migrations don't work


This might be out of scope, but running a lot of queries causes this error:
```
PrismaClientUnknownRequestError:
Invalid `prisma.product.findMany()` invocation in
/home/ubuntu/blitz-perftest/.blitz/caches/dev/.next/server/static/development/pages/api/test.js:131:79

Error in connector: Error creating a database connection.
```

For context, I'm running Prisma through a blitz.js app on EC2 in the same VPC as the RDS Proxy, with 100% of the 80 something max connections given to the proxy. I'm using this repo https://github.com/dajinchu/blitz-perftest/ I'm using artillery to send 20 req/s for 10 seconds. Using regular RDS w/o proxy at the same load does not cause this error.

**Comment by Sytten** [comment]
RDS proxy is fine, I just finished automated migrations on deploy on Cloud Build for a client.

**Comment by dajinchu** [comment]
@Sytten Would you mind elaborating on your setup? I'm not sure why mine isn't working. How are you accessing RDS Proxy from Cloud Build? I thought RDS Proxy only worked within the same VPC.

**Comment by Sytten** [comment]
You need a public IP to make it work because cloud build is not in the same vpc. This was fine with my client since the firewall denies all external connections except those from the proxy.

**Comment by dajinchu** [comment]
@Sytten Hi, sorry I'm still struggling with this. Do you mean the RDS Proxy has a public IP or Cloud Build has a public IP? Thanks.

**Comment by Sytten** [comment]
Your Cloud SQL instance needs a public IP.

**Comment by dajinchu** [comment]
Ah ok, I think I may be thinking about AWS RDS and you are referring to GCP Cloud SQL?

**Comment by Sytten** [comment]
My bad, I probably misread the first time and thought about GCP since thats what I am currently working with.

**Comment by timsuchanek** [comment]
We tested this from AWS Lambda and Prisma Client 2.2.2 and it works.
We will as a further task run our full test suite against it to make sure all edge cases are covered.

**Comment by Jolg42** [comment]
Awesome!

**Comment by mcsdevv** [comment]
Hey @timsuchanek, what was the outcome of your full tests?
