### ISSUE TITLE
Be able to set an ID, which is being autoincremented

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma-client-js#688]
I would like to be able to set an ID in some cases, which is an `Int` and has `@default(autoincrement())`. 

So if no value is provided it would just increment from the highest id onwards.

**Comment by mavilein** [comment]
We had this discussion already a few times. We did not implement this yet because it could lead to a state where it is not possible to create new records anymore.
E.g. on Postgres the following could happen:
1. Setup an empty database.
1. Create a record with a manual id of 1.
1. Try to create a new record by relying on the default.

**Result**: The underlying sequence in postgres was not used yet. It returns the value 1. The create fails because the id exists already. 

I think MySQL and SQLite don’t have this problem as they are incrementing on top of the last inserted (no matter if it was created manually or automatically).

**Comment by BjoernRave** [comment]
okay, I didn't know about that behavior from postgres. I gues in this case the only way to achieve this would be to handle it on the prisma side of things opposed to natively. I understand though, that this might not be the path you want to go. I guess I will just keep two Id's for the entries which need this incrementing counter

**Comment by mavilein** [comment]
Handling this in the Prisma layer is probably not an option. This would come with severe performance implications.
The only thing that i can imagine is that we would support this only on MySQL and SQLite.

**Comment by janpio** [comment]
We _could_ work around the limitation of Postgres:
When you set a value manually, we get the max value of the sequence (we can not just use the one we just set, as it could also fill a whole in the sequence) afterwards and set it via `setval` on the sequence. (via https://stackoverflow.com/a/3905447) Adds a query and is definitely not very elegant, but it would work and ensure that just by using Prisma you can not mess up your sequences.

**Comment by thebiglabasky** [comment]
Hi @BjoernRave 
I'd love to understand better the underlying reasons behind sometimes wanting to set the ID manually and sometimes not.
Could you elaborate?
As of today this is unlikely that we would consider it soon given what is already planned (support for distinct, order by multiple fields, aggregates, group by, native types...). Having a better understanding of your use case would help.

Thanks!

**Comment by BjoernRave** [comment]
hey @thebiglabasky sure. So I am developing an inventory management system. Every movement get's an ID which is autoincremented. We also support for clients to import existing movements from excel for example. Those might already have ID's assigned by the user in which case we would need to specifically set the ID. currently we are working around this by having a seperate "Movement ID" beside the normal "ID", which we increment manually

**Comment by thebiglabasky** [comment]
Right, thanks for that context. It makes sense and is largely related to bulk imports in general. 
We'll have to park that for a moment to think about the topic more, but I'll keep it open.

**Comment by BjoernRave** [comment]
yea, no worries my workaround works fine

**Comment by timsuchanek** [comment]
This is implemented with unchecked scalar inputs, which we shipped in preview in https://github.com/prisma/prisma/releases/tag/2.11.0
