### ISSUE TITLE
`before` not working correctly - error in generated sql statement

### ISSUE THREAD

**Issue by richardwardza** [prisma/prisma-client-js#694]
I have a repo with the small example here: https://github.com/richardwardza/prisma-before-bug

## Bug description

When using the `before` parameter in a `findMany` query, the response is not what it expected.
I have 12 clients in the table (`a` to `l`) and am paginating them 2 at a time using `first: 2` and `after: X` (x is the last client in the previous query).
Going "forward" works fine but going "backwards" using `before: X` and `orderBy: { id: "desc" }` does not work correctly.

Forward query: `await prisma.client.findMany({ first: 2, after: { id: 'b' } });` // implicit `orderBy: { id: "asc" }});`
Backwards query: `await prisma.client.findMany({first: 2,before: { id: 'e' },orderBy: { id: "desc" }});`

The generated sql for the `before` query looks as follows:
```
SELECT
"play"."Client"."id",
"play"."Client"."name" 
FROM
"play"."Client" 
WHERE
(
    1 = 1 
    AND (
        (
            ( "play"."Client"."id" ) = ( SELECT "play"."Client"."id" FROM "play"."Client" WHERE ( "play"."Client"."id" ) = ( 'e' ) ) 
            AND ( "play"."Client"."id" ) < ( 'e' ) 
        ) 
        OR ( "play"."Client"."id" ) > ( SELECT "play"."Client"."id" FROM "play"."Client" WHERE ( "play"."Client"."id" ) = ( 'e' ) ) 
    ) 
) 
ORDER BY
"play"."Client"."id" DESC 
LIMIT 3 OFFSET 0;
```

The issue appears to be in the last `OR`:
`OR ( "play"."Client"."id" ) > ( SELECT "play"."Client"."id" FROM "play"."Client" WHERE ( "play"."Client"."id" ) = ( 'e' ) )`

Changing the `comparison` from `>` to `<` gets the correct answer back, like so:

`OR ( "play"."Client"."id" ) < ( SELECT "play"."Client"."id" FROM "play"."Client" WHERE ( "play"."Client"."id" ) = ( 'e' ) )`

This results in the query correctly returning:
```
d
c
b
```

## How to reproduce

1. clone `https://github.com/richardwardza/prisma-before-bug`
2. run `yarn`
3. create a valid `prisma/.env` file
4. run `yarn save`
5. run `yarn up`
6. run `yarn gen`
7. run `yarn start`

## Expected behavior

The output currently has:
```
Remove all data.
Clients created.
Retrieve first set of 2 (from start):
a
b
Retrieve second set of 2 (from after b):
c
d
Retrieve third set of 2 (from after d):
e
f
Retrieve second set of 2 (from before e):
l
k
Done
```

The last piece of output should be:
```
Retrieve second set of 2 (from before e):
d
c
```

## Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Client {
  id   String @default(cuid()) @id
  name String
}
```
## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.5
- Node.js version: v12.16.1

**Comment by richardwardza** [comment]
This isn't a bug - I'm not using the `findMany` correctly.

The last, "backwards" query, should be:
```
await prisma.client.findMany({last: 2,before: { id: 'e' },orderBy: { id: "desc" }});
```

I'm leaving this all here but closing the ticket. 

Thank you.

**Comment by pantharshit00** [comment]
Thanks for the write up anyways @richardwardza 

Feel to open more issues if you encounter any other problem
