### ISSUE TITLE
Client, Engine version incorrect when overriding binary with Prisma client constructor

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#696]
## Bug description

With `export DEBUG=*`, Prisma client logs Engine, Client version. 

These versions are correct

1. For the default binary
1. When a binary is replace with `QUERY_ENGINE_BINARY_PATH` env var

These versions are incorrect (incorrectly pointing to the default binary)

1. When binary is overridden with Prisma client's constructor

```ts
const prisma = new PrismaClient({
  __internal: {
    engine: {
      cwd: process.cwd(),
      binaryPath: path.join(process.cwd(), './binaries/query-engine'),
    },
  },
})
```

## How to reproduce

1. Compile a custom binary and use Prisma client constructor to override it.
2. Use `DEBUG=*`
3. Run the client and execute a query against it. 

## Expected behavior

The logged version should be of the binary being used.

**Comment by Jolg42** [comment]
So it appears that the `engineVersion` from the DEBUG output comes from the code generated client 
<img width="470" alt="Screen Shot 2020-05-18 at 16 30 37" src="https://user-images.githubusercontent.com/1328733/82226100-5a3d5f80-9926-11ea-80f2-a32c32d32ea9.png">
(The client version in this screenshot is wrong and was already fixed)

**Comment by Jolg42** [comment]
The issue here is that the hash in the debug log is hardcoded so when the binary is different like when using an env var or with the constructor in the client it still outputs the hardcoded version.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
