### ISSUE TITLE
Datasource override from client constructor doesn't match the datasource block from the schema.prisma file

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-client-js#698]
## Problem
prisma.schema
```prisma
datasource myawesomedb {
  provider = "mysql"
  url      = "mysql://......"
}
```

The shape of the input in the constructor is not the same as the datasource block in the schema:
```ts
const client = new PrismaClient({
  datasources: {
    myawesomedb: 'mysql://........'
  },
})
```

## Suggested solution
```ts
const client = new PrismaClient({
  datasources: {
    myawesomedb: {
      url: 'mysql://........',
    },
  },
})
```

Only the url can be overridden, this will add the provider as well. 

Todo

- [ ] Modify constructor
- [ ] Add JSDoc
- [ ] Update tests
- [ ] Update docs

**Comment by Jolg42** [comment]
So I discussed with Tim and right now the most confusing part is that there is a bug in TypeScript and the autocompletion doesn’t work at all for this.

https://github.com/microsoft/TypeScript/issues/37249

**Comment by timsuchanek** [comment]
We now have fixed the auto-completion in the Prisma Client, so I would consider this "fixed" for now, because the confusion of what the input should be, should not occur anymore with the types.
