### ISSUE TITLE
Generate JSDoc

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#7]
...

Related: https://github.com/prisma/photonjs/issues/391

**Comment by schickling** [comment]
`yargs` is a great example for this. Would love to take first steps on this asap.

![image](https://user-images.githubusercontent.com/1567498/67144488-32462a80-f277-11e9-836d-9361e9fa5284.png)

**Comment by matthewmueller** [comment]
Internal note: Do the first 10% to setup the machinery. Create an issue to do the rest later

**Comment by nikolasburk** [comment]
Update: Not started.

**Comment by divyenduz** [comment]
Internal note: dropping because priority!

**Comment by timsuchanek** [comment]
We have the first go of this implemented. 
![image](https://user-images.githubusercontent.com/1094804/73458653-e88cd600-4375-11ea-8395-92aed20c8f99.png)

The issues #457 and #458 now track more advanced JSDoc for nested arguments.
