### ISSUE TITLE
Adapt a more conflict resistant naming for Prisma client's types

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#707]
Right now properties like `${name}Client` are ending up in the denyList and it is very common to name something like `UserClient`.

This adds unnecessary friction and we can totally avoid this by using a more conflict resistant naming for types like `User__Client`.

Internal: https://prisma-company.slack.com/archives/CUXLS0Z6K/p1590736839231000

Related: https://github.com/prisma/prisma/issues/2539

**Comment by dodas** [comment]
What about generating those classes conflicting with model names to different file and import them to index under different, perhaps very conflict-tolerant/avoiding names?

**Comment by pantharshit00** [comment]
Yes, that can be one way of doing that.

**Comment by janpio** [comment]
Possibly related: https://github.com/prisma/prisma/issues/2656

**Comment by timsuchanek** [comment]
We now implemented `Prisma__UserClient`.
