### ISSUE TITLE
Allow Callbacks for Upsert

### ISSUE THREAD

**Issue by nahtnam** [prisma/prisma-client-js#709]
## Problem
Currently when you upsert, you provide a create block and an update block. I would like to log some statistics of when something is updates vs when something is created.

## Suggested solution
It would be nice to have some additional hooks available, such as `onCreate` and `onUpdate` in the upsert statement which run if something is updated or created.

## Alternatives
N/A

## Additional context
N/A

**Comment by pantharshit00** [comment]
Related to https://github.com/prisma/prisma-client-js/issues/669, might be a duplicate as well but I am not sure. Will that issue address your problem?

**Comment by nahtnam** [comment]
@pantharshit00 Not really, from what I see, it wouldn't give you information if SQL inserted or updated, but I actually thought of a better idea. I saw that upsert returns the inserted object. It would be cool if it had additional properties like `_created`, and `_updated` which are booleans saying if the action was an insert or update.

**Comment by timsuchanek** [comment]
This is possible with our middleware API - https://www.prisma.io/docs/concepts/components/prisma-client/middleware
