### ISSUE TITLE
Is pluralization still needed on `photon.<model_name>` ?

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma-client-js#73]
## Description

Let's assume a `User` model.
Since we're planning to drop support for the shortcut `photon.users({ ... })`, I don't see the reason anymore to have pluralization.

It feels especially weird to me when doing `photon.users.findOne({ ... })`

## Proposal

Remove pluralization and always use the model names lowercased.

```
photon.user.findOne()
photon.user.findMany()
```

**Comment by schickling** [comment]
Related to https://github.com/prisma/prisma2/issues/17

**Comment by pantharshit00** [comment]
This is done. We have removed pluralization in the client in the latest version.
