### ISSUE TITLE
When using `@prisma/cli` as a `devDependency` Firebase doesn't install it.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-client-js#732]
@janpio I was opening up a new issue for this and rubber-ducked my way into finding the solution. The issue was that I had `@prisma/cli` listed as a `devDependency` and it seems like firebase does not install those. Therefore, when deploying, it would install all my dependencies (not prisma/cli) and then run the initial `prisma generate`, leaving me with the error I had outlined above.

I moved `@prisma/cli` to a normal `dependency` and tried deploying and it worked!

I was getting the following error and attempted the fix as outlined, but given what I mentioned above, that fix wouldn't work in Firebase's situation as it suggests adding as a dev dependency.
```
In order to use "@prisma/client", please install @prisma/cli. You can install it with "npm add -D @prisma/cli".
```

This seems to be pretty specific to my situation with Firebase, however, it might be helpful to note in the [setup](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client#1-prerequisites) that services like Firebase might require the cli to be listed as a normal dependency.

Thanks for the quick response and for building an awesome product!

_Originally posted by @seanking11 in https://github.com/prisma/prisma-client-js/issues/390#issuecomment-639894380_

**Comment by Jolg42** [comment]
Update:
> I had similar issue, but it was my own fault ignoring `node_modules` in `firebase.json`. Don't add `"**/node_modules/**"` in ignore field:
> 
> ```json
> {
>   "functions": {
>     "predeploy": [
>       "npm --prefix \"$RESOURCE_DIR\" run lint",
>       "npm --prefix \"$RESOURCE_DIR\" run build"
>     ],
>     "source": "functions",
>     "ignore": ["**/.*", "*.log", "**/node_modules/**"]
>   }
> }
> ```
> 
> UPDATE: false alarm, use `yarn` instead of npm. You can still ignore node_modules.
https://github.com/prisma/prisma/discussions/2106#discussioncomment-27511

**Comment by pantharshit00** [comment]
So this can be closed right? @Jolg42

**Comment by Jolg42** [comment]
I'm gonna close it like you suggested @pantharshit00 

If anybody has this problem again we will reopen the issue 😃
