### ISSUE TITLE
Non-recoverable error on pagination

### ISSUE THREAD

**Issue by isidoro98** [prisma/prisma-client-js#733]
## Bug description

When running pagination on a query, if `skip` or `first` or other pagination parameters is passed a negative number as an argument the service stops working.

## How to reproduce

`t.list.field('posts', {
      type: 'post',
      args: {
        skipAmount: intArg(),
        getAmount: intArg(),
      },
      resolve: (_, { skipAmount, getAmount }, ctx) => {
        return ctx.prisma.post.findMany({
          skip: skipAmount,
          first: getAmount,
        })
      },
    })`

When running the code above and passing a negative number as either of the parameters the result is a non-recoverable error.

## Expected behavior

This query should fail but the server should still be able to handle other queries.

## Prisma information

`    "@nexus/schema": "0.13.1",
    "@prisma/client": "2.0.0-beta.4",
    "nexus-prisma": "0.12.0"`

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version:     "nexus-prisma": "0.12.0"
- Node.js version: v12.16.3

**Comment by pantharshit00** [comment]
@isidoro98 Can you please try again with the latest version of Prisma and Nexus? Thanks!
