### ISSUE TITLE
Improve automatically generated error reports

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#744]
Right now the generated report that we have for Prisma Client doesn't contain much helpful information.

Example report can be seen here: #724 

Things that we can improve:
- Add a more detailed trace
- Add the datamodel(or at least prompt the user so that they can add it manually)
- Properly prompt the user to add information about what they did to reach that panic.

**Comment by alexnederlof** [comment]
Not sure if I need to create a separate issue, but for me, 50% of the time the link cannot be submitted because it is too long for GitHub. I would suggest to check the size, and try to reduce the link length as much as possible 😅

**Comment by janpio** [comment]
Next step: Find working reproduction, possibly via explicit "cause crash" method (whihc might be a new feature request).

**Comment by pantharshit00** [comment]
@timsuchanek were you able to reproduce this using the debug mode?
