### ISSUE TITLE
Transaction API is not writing the transaction

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#750]
## Bug description

The transaction API is not writing data to database even though I am getting result back in the transaction object

![image](https://user-images.githubusercontent.com/22195362/85574883-c2354300-b654-11ea-875f-e9e86508cf11.png)
![image](https://user-images.githubusercontent.com/22195362/85574901-c6616080-b654-11ea-899f-ec4276305caa.png)

## How to reproduce

See https://github.com/harshit-test-org/prisma-internal-transaction-issue

## Expected behavior

It should write data to the database.

## Environment & setup

- OS: MacOS 10.15.5
- Database: Postgres 11
- Prisma version: 2.2.0-dev.1
- Node.js version: 12.16.2

**Comment by pantharshit00** [comment]
Fix is available in `2.2.0-dev.6`

**Comment by Sytten** [comment]
@janpio @pantharshit00 This should be backported in a patch version IMO, it's not supposed to be a beta software anymore so it should use semver correctly and this is clearly a break in a feature of `2.1.0`.

**Comment by janpio** [comment]
This is being merged into a patch branch and will be released tomorrow.

But: The transaction API is behind a feature flag that makes it explicit that this is experimental functionality and not covered by the normal expectations. Please differentiate here.
https://github.com/harshit-test-org/prisma-internal-transaction-issue/blob/92bc7194e41381e59a6a47bd207faf98afda2c0d/prisma/schema.prisma#L3

**Comment by mavilein** [comment]
The patch is available in [2.2.2](https://github.com/prisma/prisma/releases/tag/2.1.2). This contained a regression for studio though. So i recommend to use `2.2.3` instead.

**Comment by Sytten** [comment]
Note for others @mavilein means 2.1.2 and 2.1.3.

**Comment by mavilein** [comment]
Thanks @Sytten . Fixed it! 🙏
