### ISSUE TITLE
Client should download the correct binary for FreeBSD 12

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-client-js#752]
Part of the parent issue https://github.com/prisma/prisma/issues/2841

**Comment by janpio** [comment]
Unfortunately we had to undo this as described in https://github.com/prisma/prisma/issues/3558: We do not build binaries for FreeBSD 12 and provide them for download automatically any more. Please see https://github.com/prisma/prisma-engines#building-prisma-engines and https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries how to build and then use a custom binary.
