### ISSUE TITLE
Escaping parameters of `queryRaw` and `executeRaw` to prevent SQL injections

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma-client-js#755]
## Problem
As of today, parametrized queries executed through `queryRaw` or `executeRaw` do not escape parameters to prevent from SQL injections. This can lead users to forget about this and open serious vulnerabilities in their software.
This is problematic as:
* Not mentioned in Prisma's documentation which can let people assume it's done by default
* Not the standard practice in most SQL clients (e.g. [Node-Postgres](https://node-postgres.com/features/queries#Parameterized%20query), [Knex.js](http://knexjs.org/#Raw-Bindings), [Sequelize](https://sequelize.org/master/manual/raw-queries.html#replacements)...)
* Done whenever using the [tagged template call form](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access#tagged-templates)

## Suggested solution
Ensure `queryRaw` and `executeRaw` do escape parameters before sending those to the engine.
Update documentation to reflect how Prisma protects from SQL injections

## Alternatives
I don't think there's any.

## Additional context
Mentioned #727 that there could be confusion between escaped and unescaped ways to make queries.

**Comment by Sytten** [comment]
I am not sure what you mean by that:
- templated string version works as expected
- If using the regular `$` notation, parameters (the second parameter) are also escaped

I feel this is mostly a documentation issue. The documentation also does not have any mention of now exposed `sql`, `join`, etc that can be used to create complex safe queries.

**Comment by pantharshit00** [comment]
I also agree with that. At most what we can do here is to change the name of the method version to indicate that it can dangerous if you don't use prepared parameters.

**Comment by thebiglabasky** [comment]
Hey, so after digging further, I've summarized the situation in [this comment](https://github.com/prisma/prisma-client-js/issues/727#issuecomment-650096790)
**TL;DR:** this issue is invalid, because queryRaw and executeRaw, whenever called with parameters as second arguments, will result in a prepared statement at query engine level. I'll close this one.

**Comment by Sytten** [comment]
As commented on the other issue, the doc on it is still bad.
