### ISSUE TITLE
Expose debug mode to trigger a panic for reproductions

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#756]
## Problem

We have a debug mode in the engines which we can use to trigger a panic. We need to expose that now in the client. 

Ref: https://github.com/prisma/prisma-engines/issues/764

## Suggested API

```js
prisma.__internal_triggerPanic()
```

**Comment by timsuchanek** [comment]
Will help debugging https://github.com/prisma/prisma/issues/2748

**Comment by timsuchanek** [comment]
Fixed in `2.1.2`.
