### ISSUE TITLE
Consider scoping the transaction API to a database

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-client-js#767]
## Problem
We recently shipped the new transaction API as an experimental feature. The api looks like the following:
```js
await prisma.transaction([write1, write2, ..])
```

This will just work fine as of now. But it gets complicated in case we introduce support for multiple databases in a schema. Then this API signature implies that we implemented transaction support across multiple different databases, which we will probably not do. In the above example `write1` could go database A and `write2` could go to database B.
We could anticipate this change and already future proof the API now.

## Suggested solution
I have no preference. We should just make a conscious decision.

## Alternatives
These are just some spontaneouos ideas i had. There are probably more alternatives out there.

**1. Introduce datasource scopes**
We could introduce an additional scope for the transaction call. E.g.
```js
await prisma.db1.transaction([write1, write2, ..])
await prisma.db2.transaction([write3, write4, ..])
```
In the above example `db1` and `db2` refer to the datasources in the schema which are named like that.

**2. Introduce datasource parameter**
We could introduce a parameter to choose the datasource. It might be tricky to make this call typesafe then. E.g. a user should be only able to pass writes into the function that are indeed part of the provided datasource.
```js
await prisma.transaction([write1, write2, ..], datasource: 'db1')
await prisma.transaction([write3, write4, ..], datasource: 'db2')
```

**Comment by matthewmueller** [comment]
I think this should work actually `await prisma.transaction([write1, write2, ..])`, where `write1`, `write2` share the same database interface.

```typescript
async function transaction(...actions: SQLiteables[]): Promise<void>
```

**Comment by matthewmueller** [comment]
We decided to go with what we have now and consider namespacing when we have multiple datasources. Closing.
