### ISSUE TITLE
Unknown error in Prisma Client This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

### ISSUE THREAD

**Issue by sk8Guerra** [prisma/prisma-client-js#777]
Hi Prisma team, I'm building an app, that initially made with `Mongo`, now I'm migrating it to `Postgres` and of course, I'm using this beauty of `Prisma`.

Today, while I was trying to make a huge insert in a table via `prismaSerivce` (because I'm using nestjs), got an error that has the same title as above there 👆🏼 I realized that it has a body that contains some weird code and then has this message: `If you want the Prisma team to look into it, please open the link above...` So here I am, but what should I do with the body? Because has some names and directions that I would not like to be public. 

Thanks 😃

**Comment by pantharshit00** [comment]
Hey @sk8Guerra 

Can you please provide a minimal reproduction for that above issue? We can't identify if there is a bug in our system with a reproduction. Thanks!

**Comment by sk8Guerra** [comment]
Hi, @pantharshit00 thanks for your attention, but it turns out that, my issue was with Postgres. **_I created a table that has a foreign key, to another table, but for some reason, the foreign key was pointing to the table itself, not to the other one._** So, here is what happened to me, in case someone is having Prisma telling you the error up there in the title of this issue.

I'm closing this issue. 😃

**Comment by janpio** [comment]
Technically that should also work @sk8Guerra - do you still have an export of that database schema so we can possibly recreate the problem you were getting?

**Comment by sk8Guerra** [comment]
Well, I've actually changed it, but I can re-create it. Then I can send it to you, is it ok?

**Comment by janpio** [comment]
Yes, that would be great. If you can even recreate it in a minimal example and put it on GitHub, that would even be better - because that would be our next step as well.

**Comment by sk8Guerra** [comment]
@janpio a mini nestjs project with the setup like when the error occurred?

**Comment by janpio** [comment]
That would be _perfect_.

**Comment by sk8Guerra** [comment]
Just give me some time. 😉
