### ISSUE TITLE
Filter By Enum is not working, its throwing error message 

### ISSUE THREAD

**Issue by hcmuleva** [prisma/prisma-client-js#778]
I am using t.crud for enum and when I tried to query from apollo client its returning error (Detailed filter query Please find as attachment)

Error
[GraphQL error]: Message: Variable "$role" of type "String" used in position expecting type "role_enum"., Path: undefined  inside 

```
enum role_enum {
    Admin
    Teacher
}
```
```
type Assigned_Role {
    assigned_role_id: Int!
    role: role_enum!
}
```
In GraphQL Playground i can apply filter query on enum(without double quotes)
```
query{
  assigned_roles(
    where:{
      role:Admin
    }
  ){
    content_type
  }
}

```

Role:
"nexus-plugin-prisma": "^0.16.1"
"@nexus/schema": "0.14.0",

**Comment by pantharshit00** [comment]
Hi @hcmuleva,

Can you please open this issue in the nexus repository? It is situated here: https://github.com/graphql-nexus/nexus

I can't transfer this there as it is not possible to transfer issues across orgs in GitHub.

**Comment by hcmuleva** [comment]
Ok sure i will do
 Thanks
