### ISSUE TITLE
DATABASE_URL required when setting `datasources.db.url`

### ISSUE THREAD

**Issue by defrex** [prisma/prisma-client-js#779]
## Bug description

I originally identified this as a regression of https://github.com/prisma/prisma/issues/2609.

`DATABASE_URL` is required, even when explicitly setting `datasources.db.url` in the `PrismaClient` constructor.

## How to reproduce

Given the following,

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  // ...etc
}
```

```typescript

import { PrismaClient } from '@prisma/client'

const url = `postgresql://user:pass@localhost/mydb`

const prisma = new PrismaClient({
  datasources: { db: { url } },
})

console.log('user count', await prisma.user.count())
```

Without setting `DATABASE_URL`, I get this error.

```
(node:35938) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.count()` invocation in
/Users/defrex/Code/treasure/api/src/prisma-repro.ts:19:47

  15 const prisma = new PrismaClient({
  16   datasources: { db: { url } },
  17 })
  18 
→ 19 console.log('user count', await prisma.user.count()


  error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at PrismaClientFetcher.message [as _request] (/Users/defrex/Code/treasure/api/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:999:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:35938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior

I expect it to connect without needing to set the `DATABASE_URL` environment variable.

This error can be solved by setting `DATABASE_URL` to a "dummy" value that appears valid. Eg. `DATABASE_URL=postgres://notarealhostname`.

## Environment & setup

- OS: Mac OS
- Database: Postgres
- Prisma version: 2.2.0
- Node.js version: 12.18.1

**Comment by pantharshit00** [comment]
I am going to mark this as an improvement for now since the overriding by client is not officially supported right now

**Comment by asktree** [comment]
I've started encountering this issue when I wasn't in the past, without changing versions of prisma. One attempted workaround was setting `DATABASE_URL` in my script using `process.env.DATABASE_URL = blahblah`, but this didn't work even though it seems like it should.

**Comment by defrex** [comment]
@asktree FWIW, setting `process.env.DATABASE_URL = url` worked for me, and is the solution I ended up going with

**Comment by asktree** [comment]
@defrex With or without setting a nonsense value in the schema? It works for me if I set a nonsense value. yeah.

**Comment by defrex** [comment]
@asktree 

I have `url = env("DATABASE_URL")` in my `schema.pirsma` file. Then initialize prisma like so.

```typescript
const url = `postgresql://user:pass@localhost/mydb`

process.env.DATABASE_URL = url

const prisma = new PrismaClient({
  datasources: { db: { url } },
})
```

**Comment by janpio** [comment]
@defrex The syntax your are using in `PrismaClient` is outdated. See https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor#datasources for the current, working version that should enable you to use the detour using the env variable.

**Comment by asktree** [comment]
@defrex No, this isn't a valid detour using 2.3.0

**Comment by timsuchanek** [comment]
This is fixed in the latest version. Of you still face this issue, please let us know.
