### ISSUE TITLE
Unknown error in Prisma Client

### ISSUE THREAD

**Issue by Tobbe** [prisma/prisma-client-js#783]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.16.3           | 
| OS       | rhel-openssl-1.0.x |
| Prisma   | 2.2.2              |

## Logs
```
2020-07-16T19:45:50.899Z prisma-client {
  engineConfig: {
    cwd: '/var/task/src/node_modules/.prisma/client',
    debug: false,
    datamodelPath: '/var/task/src/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/opt/build/repo/node_modules/@prisma/client',
      binaryTargets: [Array],
      experimentalFeatures: [Array],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.2.2',
    enableExperimental: [ 'aggregations' ]
  }
}
2020-07-16T19:45:50.991Z prisma-client Prisma Client call:
2020-07-16T19:45:50.992Z prisma-client prisma.product.findMany(undefined)
2020-07-16T19:45:50.992Z prisma-client Generated request:
2020-07-16T19:45:50.992Z prisma-client query {
  findManyProduct {
    id
    name
    desc
    longDesc
    price
    imgUrl
    createdAt
    sku
    productId
  }
}

2020-07-16T19:45:51.007Z plusX Execution permissions of /var/task/src/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
2020-07-16T19:45:51.246Z prisma-client Client Version 2.2.2
2020-07-16T19:45:51.246Z prisma-client Engine Version a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4
2020-07-16T19:46:08.195Z prisma-client Prisma Client call:
2020-07-16T19:46:08.195Z prisma-client prisma.product.findMany(undefined)
2020-07-16T19:46:08.195Z prisma-client Generated request:
2020-07-16T19:46:08.195Z prisma-client query {
  findManyProduct {
    id
    name
    desc
    longDesc
    price
    imgUrl
    createdAt
    sku
    productId
  }
}

2020-07-16T19:47:27.760Z prisma-client Prisma Client call:
2020-07-16T19:47:27.760Z prisma-client prisma.product.findMany(undefined)
2020-07-16T19:47:27.760Z prisma-client Generated request:
2020-07-16T19:47:27.760Z prisma-client query {
  findManyProduct {
    id
    name
    desc
    longDesc
    price
    imgUrl
    createdAt
    sku
    productId
  }
}

```

---

I'm new to the world of Prisma/apollo/gql so I'm not really sure where to start troubleshooting this. Can anyone spot anything strange in the report above? I've built a web shop, and I get the error above when just browsing through the products in the shop. I can access the same product just fine several times, and then all of a sudden when I just refresh the page I get the error above. It can happen with any product in the store, and I have not been able to notice any kind of pattern of when it happens.

Sorry for being so vague. Any help with troubleshooting this would be greatly appreciated 🙏 🙂

**Comment by pantharshit00** [comment]
Hello @Tobbe 

Can you provide a minimal reproduction for the above error? Right now the above information is insufficient for me to reproduce the problem and identify the bug. Thanks!

**Comment by Tobbe** [comment]
I'll see if I can make something smaller than what I currently have to reproduce my problem. But it will probably be a couple of days.

In the meantime I'll give you my schema, if that's of any help

```
datasource DS {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGET")
}

model Product {
  id        Int      @default(autoincrement()) @id
  name      String
  desc      String?
  longDesc  String?
  price     Int?
  imgUrl    String?
  createdAt DateTime @default(now())
  sku       String?
  productId String?
}
```

**Comment by Tobbe** [comment]
I guess I could have shared the actual error message as well 🙄 

> Error: GraphQL error: Invalid prisma.product.findMany() invocation in /var/task/src/api/dist/services/products/products.js:14:25 Unknown error in Prisma Client This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

**Comment by Tobbe** [comment]
The original report is with `findMany`, but I'm also getting the same error with `findOne`. 
I have the code as a Netlify lambda function, and I've managed to somewhat reliably reproduce it by doing this:

```
$ for i in {1..100}; do curl -s https://MY_SITE.netlify.app/.netlify/functions/prisma?id=155; done; sleep 120s && curl -s https://MY_SITE.netlify.app/.netlify/functions/prisma?id=15
```

The specific `id`s doesn't seem to matter. What's important is the pattern of quick sequential requests. Then wait a bit. Then do a new request. This final request causes the crash.

This is the code
```javascript
import { db } from 'src/lib/db'

exports.handler = async (event, context, callback) => {
  try {
    const id = parseInt(event.queryStringParameters.id || '2', 10)

    const product = await db.product.findOne({
      where: { id },
    })

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(product)
    }
  } catch (error) {
    console.error(error)

    return {
      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(error)
    }
  }
}
```

**Comment by Tobbe** [comment]
Manged to turn on more logging, and now I see this when it crashes

```
1:09:12 AM: 2020-08-04T23:09:12.498Z engine {
1:09:12 AM: error: SocketError: other side closed
1:09:12 AM: at Socket.<anonymous> (/var/task/src/node_modules/@prisma/client/runtime/index.js:1:81651)
1:09:12 AM: at Socket.emit (events.js:327:22)
1:09:12 AM: at endReadableNT (_stream_readable.js:1221:12)
1:09:12 AM: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
1:09:12 AM: code: 'UND_ERR_SOCKET'
1:09:12 AM: }
1:09:12 AM: }
```

**Comment by Tobbe** [comment]
I played around with different versions of @prisma/client

@prisma/client@2.0.0-beta.1: No crashes
@prisma/client@2.2.2: Crashes
@prisma/client@2.4.0: No crashes

So whatever the issue was seems to be resolved now :)

**Comment by janpio** [comment]
Weird, but great 👍
