### ISSUE TITLE
Non-optional array fields are erroneously optional in PrismaClient types

### ISSUE THREAD

**Issue by asktree** [prisma/prisma-client-js#784]
## Bug description

![image](https://user-images.githubusercontent.com/12001874/87725709-a6641f00-c772-11ea-8172-c4a517ed8730.png)
![image](https://user-images.githubusercontent.com/12001874/87725793-cb589200-c772-11ea-9898-c4e9b077c0eb.png)

## Environment & setup

- Database: Postgres
- Prisma version: 2.0.0-beta.6
- Node.js version: 10

**Comment by pantharshit00** [comment]
This is expected. Non null arrays means you can't set them to null that is why there is no `| null` in the type definition.


But you have have an empty array in the database(empty != null). So the behavior here is expected.

**Comment by asktree** [comment]
@pantharshit00 If you use `prisma.booking.create` to make a booking, and do not specify `images` or `invoiceStripeIds`, postgres will reject this. `empty != undefined`, and when I made this Issue I hadn't set any defaults for these columns.

**Comment by ryanyu104** [comment]
same issue

**Comment by timsuchanek** [comment]
The client by default will set them to an empty array, if you don't provide it.
That's by design.
If you have a concrete runtime error that gets thrown, please create a separate issue.
