### ISSUE TITLE
Unknown error in Prisma Client

### ISSUE THREAD

**Issue by duongntse** [prisma/prisma-client-js#785]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.13.0           | 
| OS       | debian-openssl-1.0.x|
| Prisma   | 2.2.2              |

## Logs
```
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/mnt/d/Develop_Chome_Extensions/applications/hello-prisma/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/mnt/d/Develop_Chome_Extensions/applications/hello-prisma/node_modules/.prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     engineEndpoint: undefined,
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/mnt/d/Develop_Chome_Extensions/applications/hello-prisma/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       experimentalFeatures: [Array],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.2.2',
  prisma-client     enableExperimental: [ 'aggregations' ]
  prisma-client   }
  prisma-client }  +0ms
  prisma-client Prisma Client call:  +216ms
  prisma-client prisma.user.findOne({
  prisma-client   where: {
  prisma-client     id: 4
  prisma-client   },
  prisma-client   include: {
  prisma-client     profile: true
  prisma-client   }
  prisma-client })  +1ms
  prisma-client Generated request:  +0ms
  prisma-client query {
  prisma-client   findOneUser(where: {
  prisma-client     id: 4
  prisma-client   }) {
  prisma-client     email
  prisma-client     email_confirmed
  prisma-client     id
  prisma-client     name
  prisma-client     profile {
  prisma-client       bio
  prisma-client       birth_date
  prisma-client       first_name
  prisma-client       id
  prisma-client       last_name
  prisma-client       userId
  prisma-client     }
  prisma-client   }
  prisma-client }
  prisma-client   +0ms
  plusX Execution permissions of /mnt/d/Develop_Chome_Extensions/applications/hello-prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x are fine  +0ms
  prisma-client Client Version 2.2.2  +67ms
  prisma-client Engine Version 45c4da4dd3ccd6a322796b228bdf937c7ce884e8  +0ms
```

**Comment by pantharshit00** [comment]
Hello @duongntse 

Can you provide a minimal reproduction for the above error? Right now the above information is insufficient for me to reproduce the problem and identify the bug. Thanks!

**Comment by duongntse** [comment]
Hi @pantharshit00 

To reproduce the problem, I'd just followed "Getting Started" from Prisma page: 
Here's the link: 
https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql-typescript-mysql

Note: I used "sqlite" database file (dev.db) to run the above example instead of mysql.

# First of all, I completed the tutorial from "getting-started".
 It's run smoothly and no error at this stage.
# After that, I try to update database to serve my purpose as following steps:
1. I added column "registered_date" into table "User" by SQLiteStudio.
    It's an GUI application for sqlite from https://sqlitestudio.pl/
2. run "npx prisma introspect"
3. update "schema.prisma" to follow prisma's convention.
4. run "npx prisma generate"
5. edit "index.ts" as follow

```
const allUsers = await prisma.user.findMany({
     include: {
	  posts: true,
	  profile: true,
     },
});
console.dir(allUsers, { depth: null });
```
6. run "npm run dev"
7. Its ERROR

I hope it'll help you to reproduce the error as I got.

**Comment by timsuchanek** [comment]
This should be fixed in the latest version. If you still face this issue, please let us know.
