### ISSUE TITLE
Sorting Performance with indizes on multiple fields

### ISSUE THREAD

**Issue by v-morlock** [prisma/prisma-client-js#794]
## Bug description

I have a table in a mysql-database with one timestamp-column. The Table also has a primary (auto-increment)-Key. I added an index to the timestamp-column and want to fetch the entry with the highest value (thus the latest) of this timestamp.

Prisma always seems to add a sort by the ID-column which leads to very poor query-performance.  

## How to reproduce

Create a table with multiple column, one of them (not the primary key) has a secondary index. Sort by this column. 

According to the debug logging, prisma generates a query like this:

```
SELECT
	<fields>
FROM
	<table>
WHERE
	<condition>
ORDER BY
	<table>.`receivedAt` DESC,
	<table>.`primaryKey` ASC
LIMIT ? OFFSET ?
```

My prisma-invocation is something like:

```
await prisma.<table>.findMany({
      where: { <condition> },
      orderBy: { receivedAt: "desc" },
      take: 1,
    })
```

When comparing queries manually, just by omitting the `<table>.primaryKey ASC`, performance jumps from multiple seconds to 50ms.

## Expected behavior

No additional sorting if not specified

## Prisma information

Prisma 2.2.2

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Prisma version: 2.2.2
- Node.js version: v14.5.0

**Comment by timsuchanek** [comment]
This issue has already been fixed a while ago. If you still face it, let us know and we reopen it.
