### ISSUE TITLE
Log event typing breaks when adding datasources to `PrismaClient` constructor

### ISSUE THREAD

**Issue by ianwensink** [prisma/prisma-client-js#801]
## Bug description

When creating the `PrismaClient`, you can pass a log array with an entry to emit query events. By doing so, you can later on use `prisma.on('query', callback);`. Without the `log` property during initialisation, the event won't work, since the typing looks at `keyof PrismaClientOptions extends 'log'`.

When I add another property to the options object (e.g. `datasources`), this typing breaks. It will throw a `Argument of type '"query"' is not assignable to parameter of type 'never'.ts(2345)` error. My assumption would be that `keyof PrismaClientOptions` no longer only extends `'log'`, but now also has a key called `'datasources'`.

Am I doing something wrong, or should this just work?

## How to reproduce
The following will work fine and as expected.

```typescript
const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
  ],
});

prisma.on('query', (e) => {
  console.log(e);
});
```

But this will break the typing of the event listener:

```typescript
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: '[INSERT_POSTGRES_CONNECTION_STRING]',
    },
  },
  log: [
    {
      emit: 'event',
      level: 'query',
    },
  ],
});

prisma.on('query', (e) => {
  console.log(e);
});
```

## Expected behavior

I'd expect that adding other properties to the options object, doesn't break the typings for event listeners.

**Comment by divyenduz** [comment]
I am able to reproduce this https://www.loom.com/share/7b8386a150c04ed09c24110069bc0164
