### ISSUE TITLE
Invalid `prisma.friend.create()` invocation 

### ISSUE THREAD

**Issue by fernandotec** [prisma/prisma-client-js#805]
## Bug description

I have been working in a project that consists in a simple messaging website, and i never tried anything like that and didn't searched for this type of project, that means that probably i messed up some things in the database.

But with that said i can't create a new "Friend" in the database, if i try this message shows up: 

Invalid `prisma.friend.create()` invocation
Missing a required value at `Mutation.createOneFriend.data.FriendCreateInput.message`

I'm using typescript and postgresql

# Expected behavior

It should create a new entity normally, i can't see a reason why this bug would happen 

## Prisma information

```
//Schema

model User {
  id Int @id @default(autoincrement())
  email String @unique
  image String
  name String 
  number String?
  password String 
  friends Friend[]
} 

model Friend {
  id Int @id @default(autoincrement())
  email String @unique
  image String
  name String
  number String?
  user_id Int
  User User @relation(fields: [user_id],references: [id])
  message Chat?
}

model Chat {
  friend_id Int @unique 
  created_at DateTime? @default(now())
  body String
  message Friend @relation(fields: [friend_id],references: [id])
}

```
//.TS file that i create a new entity "Friend"

```
import { PrismaClient } from '@prisma/client';
import { Request,Response } from 'express';

const prisma = new PrismaClient();

export default {
    async add(request: Request,response: Response){
        const { name, email, image, number} = request.body;

        try {
           
            await prisma.friend.create({
                data:{
                    User:{
                        connect:{
                            email:email,
                        },
                    },
                    email:String(email),
                    image:String(image),
                    name:String(name),
                    number:String(number),
                    message:undefined,
                },
            });

            return response.json({message: 'User created sucessfully'});

        } catch (err) {

            throw err;

        };
    },
}
```

## Environment & setup

- OS:  Windows
- Database:  Postgresql
- Node.js version:  NodeJS - 12.18.2 (with typescript)
- Prisma version:
 2.2.2

**Comment by divyenduz** [comment]
@fernandotec Thanks for raising this issue. I was unable to reproduce it. Is it possible for you to share a small reproduction repository that shows this issue? 

Also, did you run Prisma generate again after changing the schema. The error message suggests that message is required, however, in the `schema.prisma` it is optional.

**Comment by fernandotec** [comment]
> @fernandotec Thanks for raising this issue. I was unable to reproduce it. Is it possible for you to share a small reproduction repository that shows this issue?
> 
> Also, did you run Prisma generate again after changing the schema. The error message suggests that message is required, however, in the `schema.prisma` it is optional.

Hey thanks for the reply, i 've ran prisma generate and it worked, i didn' know i had to run it after changing the schema, 
I am going to close this issue now, thanks again.
