### ISSUE TITLE
Advanced usage of generated types (payload) compilation error

### ISSUE THREAD

**Issue by vh13294** [prisma/prisma-client-js#810]
## Bug description

[Advanced usage of generated types](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/advanced-usage-of-generated-types)

Error while trying to get type of Prisma Query Output of "findMany".

Actually error message:

<img width="1157" alt="Screen Shot 2020-08-05 at 9 04 08 PM" src="https://user-images.githubusercontent.com/17086745/89422285-54099300-d75f-11ea-9e7d-2ef0a4a728cc.png">

## How to reproduce

inventory.ts
```typescript

import { InventoryGetPayload, InventorySelect, Inventory } from "@prisma/client";

export const findSingleLocationSelect: InventorySelect = {
    id: true,
    quantity: true,
}

type findSingleLocationSelectGenerated = InventoryGetPayload<{
    select: findSingleLocationSelect
}>
```

## Prisma information

schema.prisma
```typescript
model Inventory {
  @@map(name: "inventories")
  comment     String?
  created_at  DateTime? @default(now())
  id          Int       @default(autoincrement()) @id
  quantity    Int
}


// Query

const inventories = await this.prismaService.inventory.findMany({
            select: findSingleLocationSelect,
        });

const inventoriesTransformed = findSingleLocationInventoryTransform(inventories);


 function findSingleLocationInventoryTransform(
    inventories: findSingleLocationSelectGenerated[]
): findSingleLocationInventory[] {
    return inventories.map(inventory => {
        const result = {
            id: inventory.id,
            quantity: inventory.quantity,
            createdAt: inventory.created_at,
            // ...
        };
        return result;
    })
};
```

## Environment & setup

- OS: Catalina 10.15.6
- Database: MySQL 8.0
- Node.js version: 12.18.3
- Prisma version:
```
@prisma/cli          : 2.4.1
Current platform     : darwin
```

## Attempted Solution

```typescript
type findSingleLocationSelectGen = InventoryGetPayload<{
    select: typeof findSingleLocationSelect // add typeof
}>
```

Error Message:  Property 'quantity' does not exist on type '{}'.

**Comment by pantharshit00** [comment]
Remove the type from the variable:
```ts
export const findSingleLocationSelect = {
    id: true,
    quantity: true,
}
```

When you type this as `InventorySelect` it makes type of it `InventorySelect` which has every key option instead of `{ id: boolean, quantity: boolean }` so attempt you posted didn't work as GetPayload needs the exact keys for it to work:
```
type findSingleLocationSelectGen = InventoryGetPayload<{
    select: typeof findSingleLocationSelect 
}>
```

**Comment by vh13294** [comment]
@pantharshit00 

I reason I choose Prisma is because of type safety. 

How would you suggest I get the type of "findMany"? 

*Note I need to reuse the select query(InventorySelect) in my application.

I also need to pass the output from "findMany" to some transform method because returning the api data.

**Comment by pantharshit00** [comment]
@vh13294 Sorry for late reply here and apologies for not explaining it properly at the first reply.

See the answer here: https://github.com/prisma/prisma/issues/3372#issuecomment-685978933

What you can do here if you want really want explicitly type of the select object:
```ts
type CheckSelectKeys<T, U> = {
  [K in keyof T]: K extends keyof U ? T[K] : never;
};

const createInventorySelect = <T extends InventorySelect>(
  arg: CheckSelectKeys<T, InventorySelect>
) => arg;


export const findSingleLocationSelect = createInventorySelect({
    id: true,
    quantity: true,
})

type findSingleLocationSelectGen = InventoryGetPayload<{
    select: typeof findSingleLocationSelect // add typeof
}>
```

**Comment by vh13294** [comment]
@pantharshit00 
Thanks you so much!
That is some advance typescript, I was trying to do that myself but couldn’t figure it out.
Where should I improve the advance typing skills ? Apart from the typescript docs page.

**Comment by pantharshit00** [comment]
@vh13294 Checkout this talk by my co worker @timsuchanek : https://www.youtube.com/watch?v=PJjeHzvi_VQ

It has a good general overview of mapped typed and conditional types for typescript.

In general, go through the advanced types section of TS docs and research language features which interests you separately.
