### ISSUE TITLE
Remove Aggregate as reserved word

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma-client-js#811]
Why is `AggregateBalance` a reserved name for models?

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1845861/89504902-117ca080-d7c9-11ea-81f7-9213d0449dc0.png">

**Comment by janpio** [comment]
Ah, just looked at the Rust list. We will look into if it is possible to remove this reserved name (as with many others).

**Comment by cyrus-za** [comment]
Thanks, please tag me when this is fixed so I can switch my model name back

**Comment by janpio** [comment]
No promises this will happen any time soon - but it is a general thing we are trying to do.

**Comment by timsuchanek** [comment]
This is fixed in the latest dev version - `2.12.0-dev.19` and will be shipped on `latest` next week Tuesday in our `2.12.0` release.
