### ISSUE TITLE
Integration Tests, Errors: Writing a signed Int to an unsigned column

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#820]
We should add a test that confirms and tracks the behavior and error message when you try to write a signed Int to an unsigned Int column.

See https://github.com/prisma/prisma/issues/1823#issuecomment-670524499

**Comment by janpio** [comment]
Can you link to the integration test that covers this @eemmiillyy please? Thanks.

**Comment by eemmiillyy** [comment]
Integration tests have been added for these with (https://github.com/prisma/prisma/pull/3683) in (https://github.com/prisma/prisma/commit/cd8361cf5a1e4c8786f40075db9888e188e701c1#diff-6e4bbddeca93b81ae24c82eaef9bbf5e)
