### ISSUE TITLE
where query not working as expected

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [prisma/prisma-client-js#833]
## Bug description

`not` filter not working as doc says [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering) 

```
await prisma.post.findMany({
      where: {
        content: {
          not: { contains: "sample" },
        },
      },
    });

```

```

Error happened  PrismaClientValidationError: 
Invalid `prisma.post.findMany()` invocation in
/home/galala/projects/prisma-examples/typescript/rest-express/src/index.ts:24:23

{
  where: {
    content: {
      not: {
        contains: 'sample'
      }
      ~~~~~~~~~~~~~~~~~~~~
    }
  }
}

Argument not: Got invalid value 
{
  contains: 'sample'
}
on prisma.findManyPost. Provided Json, expected String or null or NullableStringFilter.


```

## How to reproduce

https://github.com/mohamedGamalAbuGalala/prisma-bugs

## Expected behavior

query with not is supposed to work as expected in docs and in typedef  `not?: string | StringFilter | null`

**Comment by RitikDua** [comment]
Do you want "NOT"  as boolean expression?
If yes then you need an array here.
Hence, the right syntax will be

```
await prisma.post.findMany({
      where: {
          not: [ content:{
                  contains: "sample" 
              }],
        },
    });
```
For more refer [this](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering/#filter-conditions).

**Comment by mohamedGamalAbuGalala** [comment]
@RitikDua 
Your example is not working with the typedef

![image](https://user-images.githubusercontent.com/14947957/91981970-dd45c280-ed29-11ea-9be3-f2671f81cfd7.png)

**Comment by mohamedGamalAbuGalala** [comment]
The problem here is that typedef has the definition of `not` as `not?: string | StringFilter | null`

So this example should work and it is accepted by typedef but it doesn't in runtime and it throws the error I posted in the issue description.

```
 await prisma.post.findMany({
      where: {
        content: {
          not: { contains: "sample" },
        },
      },
    });
```

**Comment by RitikDua** [comment]
> The problem here is that typedef has the definition of `not` as `not?: string | StringFilter | null`
> 
> So this example should work and it is accepted by typedef but it doesn't in runtime and it throws the error I posted in the issue description.
> 
> ```
>  await prisma.post.findMany({
>       where: {
>         content: {
>           not: { contains: "sample" },
>         },
>       },
>     });
> ```

sorry i did a little mistake there you need **not** as Capital letters.
Hence you need it as **NOT**

**Comment by mohamedGamalAbuGalala** [comment]
I know that `NOT` will work for me.


@pantharshit00 what kind of info do you need?

**Comment by pantharshit00** [comment]
Hey @mohamedGamalAbuGalala 

I was waiting for you to respond to @RitikDua's comment so that is why I added that label.

Also, I am unable to reproduce this with 2.6.0, the provided example works.

I was having trouble running it on codesandbox so I made a repl it with working example: https://repl.it/@HarshitPant/prisma-issue-833#src/index.ts

**Comment by mohamedGamalAbuGalala** [comment]
Confirming that the bug is no longer exist in 2.6.0 ([sandbox](https://codesandbox.io/s/icy-waterfall-21vs3?file=/package.json:419-424))
