### ISSUE TITLE
Test and stabilize Unix Domain Sockets

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#837]
Per https://github.com/prisma/prisma/issues/3092 UDS is now available to be used in Prisma Client. We need to test this more and make sure there are no negative side effects.

**Comment by janpio** [comment]
Plan: Split Integration tests of Prisma Client into a standalone Github Action, then allow them to be configured to use UDS or not and run them in a matrix for operating systems (UDS: Linux, Mac | TCP: Linux, Mac, Windows)

**Comment by timsuchanek** [comment]
We looked into this and it turned out, that there is a fix in the query-engine needed to make this work properly https://github.com/prisma/prisma-engines/issues/1173

**Comment by matthewmueller** [comment]
Depends on: https://github.com/prisma/prisma-engines/issues/1173
