### ISSUE TITLE
New error after update to 2.5 for "not null" query

### ISSUE THREAD

**Issue by hayes** [prisma/prisma-client-js#842]
## Bug description

Getting a new Error after updating to 2.5 
```
Missing a required value at `Query.findManyPlay.where.PlayWhereInput.klutchId.StringNullableFilter.not`
```

## How to reproduce

I am seeing this for a fairly simple query:

```
await prisma.play.findMany({
          where: {
            studyId,
            taskSlug,
            weaponName,
            klutchId: { not: null },
          },
          skip,
          take,
        })
```

klutchId is a nullable string
## Expected behavior

Should execute query as it did when using 2.4

## Environment & setup

- OS: OSX or in lambda
- Database: Postgres
- Node.js version: 12
- Prisma version:

```
@prisma/cli          : 2.5.0
Current platform     : darwin
Query Engine         : query-engine 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.259.0
```

**Comment by Jolg42** [comment]
@pantharshit00 will try to reproduce.

We issued 2 fixes that could already solve your problem, if you want to try change your version to `2.5.1-dev.3` and let us know 😃

**Comment by pantharshit00** [comment]
I can reproduce this in `2.5.1-dev.3`

Here is a minimal reproduction: https://github.com/harshit-test-org/prisma-issue-client-842

**Comment by Jolg42** [comment]
This is fixed in `2.5.1-dev.4` and will be part of the 2.5.1 official patch. Thanks for the issue 😃

**Comment by Jolg42** [comment]
You can now use [the official 2.5.1 patch](https://github.com/prisma/prisma/releases/tag/2.5.1) 🎊

**Comment by hayes** [comment]
Thanks for the quick fix!
