### ISSUE TITLE
Invalid feature flag: aggregations error on All Requests.

### ISSUE THREAD

**Issue by lucascardev** [prisma/prisma-client-js#843]
## Bug description

All my querries stop working. I'm in a [currently TS project](https://github.com/lucascardev/odonto-easy-backend), it was all running... since last changes. It hapens in all querries now. It's a invalid invocation handler and ocuours during an initialization, as show on logging info...

`prisma:info  Encountered error during initialization:`

I'm currently testing requests on Insomnia and querries do not complete... unless i take off que await promisse. But this completed promise doesn't alter my database. Only shows return message seted on controller, and a empty object. In development enviorment i'm using sucrase with nodemon... 
And prisma client querries with await promise stop and throws this error:

**Invalid feature flag: aggregations**

``` 
Error: 
Invalid `prisma.clinic.create()` invocation in
E:\Projetos-Lucas\odontoeasy\odontoeasy-backend\src\controllers\Clinics\ClinicControllers\ClinicController.ts:38:44
Invalid feature flag: aggregations
    at PrismaClientFetcher._request (E:\Projetos-Lucas\odontoeasy\odontoeasy-backend\node_modules\@prisma\client\runtime\index.js:1:213487)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {stack: 'Error: 
Invalid `prisma.clinic.create()` invo…ctions (internal/process/task_queues.js:97:5)', message: '
Invalid `prisma.clinic.create()` invocation…38:44
  Invalid feature flag: aggregations'}
```

## How to reproduce

1. Clone [repository](https://github.com/lucascardev/odonto-easy-backend)
1. Start the server - in development - RUN yarn dev
2. Set this request 

HTTP:

`http://localhost:3000/clinic/new`

WITH BODY: 

```
{
	"cnpj": "testing",
	"fantasy_name": "centrodonto",
	"socialreason": "testes EIRELI",
	"payment_day": 10,
	"payment_method": "CREDIT_CARD",
        "registered_credit_card": true,
	"registered_debit_card": false,
	"commission_template": 0.2
}

```

## My code example

```
import { Request, Response } from "express";
import { PrismaClient, Payment_method, Clinic, Clinic_payment_information, Clinic_finance_options } from "@prisma/client";
import moment from "moment";
const prisma = new PrismaClient({
  log: ['query', 'info', 'warn'],
});

class ClinicController {
  public async index(req: Request, res: Response): Promise<Response> {
    const clinics = await prisma.clinic.findMany();
    return res.status(200).json(clinics);
  }
  public async store(req: Request, res: Response): Promise<Response> {
    const {
      cnpj,
      fantasy_name,
      socialreason,
      payment_method,
      registered_credit_card,
      registered_debit_card,
      credit_card_number,
      credit_card_CCV,
      credit_card_name,
      debit_card_number,
      debit_card_CCV,
      debit_card_name,
      payment_day,
      commission_template,
    }: Clinic & Clinic_payment_information & Clinic_finance_options = req.body;
    try {
    const actually_date = moment(new Date());
    const actually_year = actually_date.year();
    const actually_month = actually_date.month();
    const next_payment_date = await moment([actually_year, actually_month, payment_day, 10])
    .add(1, "month").toISOString();
    // console.log("sended, date: "+actually_date+" month: "+ actually_month+" year: " + actually_year + " day: "+ payment_day)
    // console.log("next payment is: " + next_payment_date);
    const new_clinic = await prisma.clinic.create({
      data: {
        cnpj: cnpj,
        fantasy_name: fantasy_name,
        socialreason: socialreason,
        Clinic_payment_information: {
          create: {
            payment_method: payment_method,
            payment_day: payment_day,
            next_payment: next_payment_date,
            registered_credit_card: registered_credit_card,
            registered_debit_card: registered_debit_card,
            credit_card_number: credit_card_number,
            credit_card_name: credit_card_name,
            credit_card_CCV: credit_card_CCV,
            debit_card_name: debit_card_name,
            debit_card_number: debit_card_number,
            debit_card_CCV: debit_card_CCV
          }
        },
        Clinic_finance_options: {
          create: {
            calculation_hour_of_day: 18,
            commission_template: commission_template
          }
        },
        logs: {
          create: {
            description:
              "Clinic registry was created with cnpj, " +
              cnpj +
              " and the social reason of " +
              socialreason +
              "."
          }
        }
      }
    });
    return res.status(201).json({response: "You are registered now", clinic: new_clinic});
      
    } catch (error) {
      console.log(error)
    }
  }
}
export default new ClinicController();
```

## Expected behavior

The shema should works normaly like was working before. Maybe somone has this error before? I dont see in any other discussion!

## Prisma information

Query Engine         : query-engine 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.259.0
Preview Features     : connectOrCreate, aggregateApi

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v12.18.3
- Prisma version: @prisma/cli :2.5.0
                            @prisma/client": "2.2.0

**Comment by janpio** [comment]
Did this start failing with the update to Prisma CLI 2.5.0?
What version where you using before the update?

**Comment by lucascardev** [comment]
Hello @janpio Thanks for helping! I decide rollback all changes i've made and surprise: Its comming back to working after... I hope the Prisma Team don't find this bug no more haha! 

**SO**, about you question, one of my changes i refer was the version update... With first rollback i used prisma CLI 2.2.0, and with that version doesn't throw any error, and all queries start to working. 
 I left the  prisma debugging options active and once that queries works fine its prompting a lot of things that didn't  show up, before the rollback, when that error was thrown.
Then i update prisma again to check if update was the source of error i've got. And return, one by one,  once all changes are  rollbacked a second time, to have sure. 
With the Prisma CLI with version 2.5.1 its all working with any issues. 
I just updated and reinstaled Prima CLI and CLIENT to version 2.5.1 and the error desapears. 
SORRY I WILL CLOSE THIS ISSUE since there are no more errors with the latest version... maybe was version 2.5.0 related bug and i dint'n updated properly in first time...
 Thanks for answer!
Lets go forward on this project!
