### ISSUE TITLE
Improve error message when object is passed to `prisma.$transaction` instead of a Prisma promise

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#846]
In order to avoid confusion in cases like prisma/prisma#3244  we can improve the error message when someone passes an object in `prisma.$transaction` which might be potentially cause by awaiting the promises which user intended to pass. 

Right now we throw ` Error: All elements of the array need to be Prisma Client promises.`

We can change this to ` Error: All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.`

**Comment by tkinte** [comment]
The suggested fix works for the debug code. Unfortunately it does not  in my real code. It shows finally that The transaction API does not work for neither create nor update Actions. 

Here is the code I use. It mixes create and update with  more than 1M of instances. The alternative code without transaction works correctly. 

> `.... async function run(reportXmlPath) {
  console.log("\n");
  let json = await reportXmlJson(reportXmlPath);
  let actionCreate = "create";
  let actionUpdate = "update";
  let jobPlan = [
    {
      action: actionCreate,
      model: "knowledgeBase",
      dataHandler: prepareData4CreateKnowledgeBase,
    },
    {
      action: actionCreate,
      model: "value",
      dataHandler: prepareData4CreateValue,
    },
    {
      action: actionCreate,
      model: "ownSlotValue",
      dataHandler: prepareData4CreateOwnSlotValue,
    },
    {
      action: actionCreate,
      model: "templateFacetValue",
      dataHandler: prepareData4CreateTemplateFacetValue,
    },
    {
      action: actionUpdate,
      model: "class",
      dataHandler: prepareData4UpdateClass,
    },
    {
      action: actionUpdate,
      model: "facet",
      dataHandler: prepareData4UpdateFacet,
    },
    {
      action: actionUpdate,
      model: "slot",
      dataHandler: prepareData4UpdateSlot,
    },
    {
      action: actionUpdate,
      model: "simpleInstance",
      dataHandler: prepareData4UpdateSimpleInstance,
    },
  ];

  while (jobPlan.length) {
    let job = jobPlan.shift();

    let models = job.dataHandler(json);
    // exexute in transaction
    try {
      console.log("Transactionnal Tasks START ...");
      await prisma.$transaction(
        models.map((model) =>
          prisma[job.model][job.action](
            job.action === actionCreate
              ? {
                  data: model,
                }
              : model
          )
        )
      );
      console.log("... Transactionnal Tasks END");
    } catch (error) {
      console.log("... cancelling the transaction ....\n");
      console.dir(error);
    } finally {
      await prisma.$disconnect();
      setTimeout(() => {}, 1);
    }
  }
} ...`

And the dependencies

> {
  "name": "essential-node",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev-ep": "node --trace-warnings ./src/script.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/client": "^2.5.1",
    "graphql-yoga": "^1.18.3",
    "node-fetch": "^2.6.0",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@prisma/cli": "^2.5.1",
    "to": "^0.2.9",
    "update": "^0.7.4"
  },
  "description": ""
}

**Comment by johhansantana** [comment]
ah! was having this warning and everything in the transaction was running correctly but this message popped up which is definitely confusing. +1 from me.

**Comment by Jolg42** [comment]
Needs to happen here https://github.com/prisma/prisma/blob/5c7c767f1c64189398fe0e0232bc0e6f36373a90/src/packages/client/src/runtime/getPrismaClient.ts#L678
