### ISSUE TITLE
Export `Sql` from @prisma/client

### ISSUE THREAD

**Issue by eddeee888** [prisma/prisma-client-js#858]
## Problem
Currently, I have to reach into `@prisma/client/runtime` to grab `Sql` which is the return type of sql template functions such as `sql`, `empty`, etc. It would be nice if this is re-exported like the other functions.

![Screen Shot 2020-08-30 at 12 05 36 am](https://user-images.githubusercontent.com/33769523/91638679-910e3000-ea54-11ea-8515-ff082e6c131f.png)

## Suggested solution

Please export it as part of these `sql-template-tag` re-exports if possible 

![Screen Shot 2020-08-30 at 12 06 23 am](https://user-images.githubusercontent.com/33769523/91638697-b00cc200-ea54-11ea-9d02-a6c3d22400f8.png)

## Alternatives

I could use `ReturnType<typeof sql>` but it's more verbose. This small quality of life change would make me love Prisma2 more 🙏

**Comment by 2color** [comment]
Hey @eddeee888 👋🏼,
Could you share an example of how you write raw SQL queries? I'm curious to learn more about your use case.

**Comment by eddeee888** [comment]
Hello @2color , here's an example of a raw query to find robots near user location by longitude and latitude, with counts for pagination. This is similar to one of the more complex queries in my app. 

```typescript
import { Sql } from "@prisma/client/runtime";
import { sql, join, empty } from "@prisma/client";
import { OrderBy, OrderByDirection, ... } from "./types";


const orderByMapper: Record<OrderBy, Sql> = {
  DISTANCE: sql`distance_in_km`,
  RELEVANCE: sql`relevance`,
};

const orderByDirectionMapper: Record<OrderByDirection, Sql> = {
  DESC: sql`DESC`,
  ASC: sql`ASC`,
};

const printHavings = (havings: Sql[]): Sql => {
  return havings.length > 0 ? sql`HAVING ${join(havings, " AND ")}` : empty;
};

const search = (input: SearchInput) => {
  const { searchTerms, currentLongitude, currentLatitude, tags, orderBy, orderByDirection } = input;

  const havingConditions = [];
  if (distanceInKm) {
    havingConditions.push(sql`distance_in_km <= ${distanceInKm}`);
  }
  // Clean searchTerms or get error in some cases: https://github.com/prisma/prisma-client-js/issues/831
  const cleanedSearchTerms = searchTerms ? searchTerms.split('"').join(" ") : ""; 
  if (cleanedSearchTerms) {
    havingConditions.push(sql`relevance > 0`);
  }

const mainQuery = sql`
  SELECT r.*,
      MATCH(r.name, r.description) AGAINST(${cleanedSearchTerms}) as relevance,
      111.045* DEGREES(ACOS(LEAST(1.0, COS(RADIANS(${currentLatitude}))
      * COS(RADIANS(r.latitude))
      * COS(RADIANS(${currentLongitude}) - RADIANS(r.longitude))
      + SIN(RADIANS(${currentLatitude}))
      * SIN(RADIANS(r.latitude))))) AS distance_in_km
      FROM Robot r
      WHERE r.status = 'ACTIVE'
      GROUP BY r.id
      ${printHavings(havingConditions)}
      ORDER BY ${orderByMapper[orderBy]} ${orderByDirectionMapper[orderByDirection]}
`;

const [robots, [{ robotCount }]] = await Promise.all([
    prisma.$queryRaw<Robot[]>`
      ${mainQuery}
      LIMIT ${finalRecordsPerPage}
      OFFSET ${finalRecordsPerPage * (page - 1)}`,
    prisma.$queryRaw<{ robotCount: number }[]>`SELECT COUNT(*) as robotCount FROM ( ${mainQuery} ) R`,
  ]);
}
```

Basically, I like to construct the raw query based on user inputs and reuse as much as possible with a few utils helpers. If there's a better way that you would recommend, please let me know :)
