### ISSUE TITLE
Prisma Query panic

### ISSUE THREAD

**Issue by RitikDua** [prisma/prisma-client-js#859]
This error happened when i added a field of ***createdAt*** in my Order model.
```
model Order{
  id Int @id @default(autoincrement())
  atPrice Int
  product Product @relation(name:"OrderProduct",references: [id],fields:[productId])
  quantity Int
  productId Int
  user    User   @relation(fields: [userId], references: [id])
  userId  Int
  totalPrice Int @default(0) 
  createdAt DateTime @default(now())
}
```

Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.13.1           | 
| OS       | debian-openssl-1.1.x|
| Prisma   | 2.4.1              |

## Logs
```
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/home/ritik/ecommerce/main/Ecommerce/backend/prisma',
  prisma-client     enableDebugLogs: false,
  prisma-client     enableEngineDebugMode: undefined,
  prisma-client     datamodelPath: '/home/ritik/.cache/prisma/studio/home-ritik-ecommerce-main-Ecommerce-backend/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     engineEndpoint: undefined,
  prisma-client     generator: {
  prisma-client       binaryTargets: [],
  prisma-client       previewFeatures: [Array],
  prisma-client       config: [Object],
  prisma-client       name: 'photon',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/home/ritik/.cache/prisma/studio/home-ritik-ecommerce-main-Ecommerce-backend',
  prisma-client       isCustomOutput: true
  prisma-client

**Comment by janpio** [comment]
> This error happened when i added a field of _**createdAt**_ in my Order model.

What steps exactly did you follow to add that field?

**Comment by RitikDua** [comment]
> > This error happened when i added a field of _**createdAt**_ in my Order model.
> 
> What steps exactly did you follow to add that field?

1. Add field to prisma schema
2. 
```
npx. prisma save --name "Change in Order" --experimental
```
 3.
```
npx prisma migrate up --experimental
```

4. npx prisma generate

I used this method everywhere is just it is not working in this scenario.
 I am little new to prisma please let me know if there is another method possible to do so.

**Comment by pantharshit00** [comment]
Hey @RitikDua 

I am unable to reproduce this with `2.6.1`. Can you please try again with that version once and if it still fails can you please the full error log here with `export DEBUG=*` set before running the migrate command. Thanks!

**Comment by RitikDua** [comment]
> Hey @RitikDua
> 
> I am unable to reproduce this with `2.6.1`. Can you please try again with that version once and if it still fails can you please the full error log here with `export DEBUG=*` set before running the migrate command. Thanks!

Thanks it worked with with v2.6.1 .
