### ISSUE TITLE
Remove direct string as ID argument to Fluent Read API

### ISSUE THREAD

**Issue by ChristianJacobsen** [prisma/prisma-client-js#876]
Photon currently supports being able to read data using the following syntax:
```javascript
const user = await photon.user.find('bobs-id')
```
This assumes that `User` has a field tagged with `@id` and that it is a _single_ field, i.e. not a compound index. If `User` has a compound index then the syntax would no longer be valid for `User`. I suggest that we remove the ability to pass the ID in directly if the model has a single ID field. This removes any chance of a developer using Photon having to remember what type of index is used in the model and enforces a consistency between the different models in terms of accessing the desired data.

Preferred syntax:
```javascript
// Single ID field
const user = await photon.user.find({ id: 'bobs-id' })

// Compound index
const user = await.photon.user.find({
  customer: { name: 'Bob', email: 'bob@bobs.com' }
})

// Connecting
await photon.user.create({
  email: 'bob@bobs.com',
  posts: {
    connect: {
      id: 'post-id'
    }
  }
})
```

**Comment by pantharshit00** [comment]
This was removed a long time ago. We no longer have this shortcut.
