### ISSUE TITLE
Prisma Client and Javascript bundlers

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#877]
A lot of project in Javascript/Typescript ecosystem use a module/asset bundler for various reasons like tree-shaking, transpiling, code-splitting, and more. 

While all the bundlers have APIs to copy the assets, it is not transparent that [binaries](https://github.com/prisma/specs/tree/master/binaries) act as assets for Prisma Client. 

Some bundlers (like `ncc`, parse `path.join` and copy over required assets while others don't). This leads to [confusion](https://github.com/prisma/prisma2/issues/818). 

This issue tracks improvement of the developer experience around this.

**Comment by timsuchanek** [comment]
Closing this, as we by now have various e2e tests covering this
