### ISSUE TITLE
Decrease package size by removing source map files

### ISSUE THREAD

**Issue by Siilwyn** [prisma/prisma-client-js#881]
## Problem
The @prisma/client package install size [2 MB](https://packagephobia.com/result?p=%40prisma%2Fclient). Reducing the size will help install speed.

## Suggested solution
Do not include source map files will halve the package size, the largest ones I found:
- `node_moduesl/@prisma/client/runtime/index.js.map`: 763 kB
- `node_moduesl/@prisma/client/generator-build/index.js.map`: 677 kB

## Alternatives
Not sure, if they are needed I suppose there is no alternative

**Comment by pantharshit00** [comment]
I am candidating this because I think we already did this because we switched from ncc to esbuild + rollup for compilation.

**Comment by Siilwyn** [comment]
@pantharshit00 that's great! I also just realized the package size could be decreased even more by removing the symbols from the query engine binary. E.g. on query-engine-debian-openssl-1.1.x using `strip` the size went from 22 to 16 MB.

**Comment by pantharshit00** [comment]
@Siilwyn query engine is downloaded in a postinstall hook so that won't affect the npm size

**Comment by Siilwyn** [comment]
Yes I understand @pantharshit00, it will help with the install speed though. But I guess this issue belongs in the engine repo instead of here.

**Comment by janpio** [comment]
We would appreciate if you could create that issue @Siilwyn 👍

**Comment by pantharshit00** [comment]
Closing as already done.
