### ISSUE TITLE
Runtime validation for Prisma client constructor parameters

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#889]
## Problem
If there is a typo/misuse in Prisma client's constructor parameters. We silently get a Prisma client object. 

## Suggested solution
It should fail with a runtime validation error like queries fail. 

## Additional context
I ran into this multiple time when using Prisma client in Javascript where I had either a typo or I was inadvertently using a param that didn't exist.

**Comment by kumaranshu72** [comment]
Can I pick this up?

**Comment by timsuchanek** [comment]
Thanks, @kumaranshu72 for asking! This needs to be defined clearer before someone can work on this.
We'll keep you posted in the issue once we have specified the behavior further, then you can pick this up.

**Comment by matthewmueller** [comment]
@divyenduz what were you trying to do when you ran into this? This feels a bit broad at the moment. I think it would help to be more specific about what properties need validating.

**Comment by divyenduz** [comment]
I was trying to add debug logs via client (which is not a feature) and I could add it. In the past I have missed typos because of this. 

As I understand, Prisma client parameters are static. What stops us from

1. Rejecting additional properties (to cover both my cases)
2. Reject a different type supplied for a parameter, Like number for string or object for string etc

**Comment by matthewmueller** [comment]
@timsuchanek do you know what needs to be done here?

I'm still a bit confused. Isn't `new PrismaClient(params)` type-safe? Are you doing this in JS?
