### ISSUE TITLE
Warn about provider array deprecation upon `prisma generate`

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma-client-js#898]
To reflect what was announced in https://github.com/prisma/prisma/issues/3834 we need to show a warning to users calling `prisma generate` whenever their schema is using a provider array, like `provider = ["sqlite", "postgres"]` or similar. 
The warning could link to the issue https://github.com/prisma/prisma/issues/3834 to provide more context.

Suggested copy:

> Warning: your schema is using the multiple datasource providers feature, which is now deprecated. We encourage you to use a single provider as this won't be supported in an upcoming release. You can read more about that in this issue: https://github.com/prisma/prisma/issues/3834

**Comment by timsuchanek** [comment]
I looked into it and in order to do this properly, we need to implement it in the engines, as we can't detect the array from TypeScript.
I suggest adding the warning to the `getConfig` method, as it also returns the datasources.

**Comment by Jolg42** [comment]
Engine will be merged with https://github.com/prisma/prisma/pull/4091 needs TS side after that

**Comment by matthewmueller** [comment]
This warning is implemented in 2.11.0
