### ISSUE TITLE
Segment Prisma Aggregation

### ISSUE THREAD

**Issue by Stevenje** [prisma/prisma-client-js#920]
I have some date like the following (in reality its much more complex) that has a main Report Type (representing 1 days data) and then Items is an array of a type called ReportItem

```
Report type {
Date: XX Oct
Items: [ReportItem, ReportItem]
}
```

**Example Data**
```
Report 1 {
Date: 21 Oct
Items: [{query: A, views: 20}, {query: B, views: 70 }]
}

Report 2 {
Date: 22 Oct
Items: [{query: A, views: 32}, {query: B, views: 27 }]
}

Report 3 {
Date: 23 Oct
Items: [{query: A, views: 13}, {query: B, views: 65 }]
}
```

I would like to aggregate the reports into a new report for the dates a user selects that displays the total views of each query for that time period. 

Eg **21 Oct -23 Oct.** 
{ query A: 65, query B: 162 }

Although when I use aggregate there's no way to split it up by query it just sums up all views.

```ts
const generated = await prisma.reportItem.aggregate({
        sum: {
          views: true,
        },
})
```

is there a way I can do this without having to map through each query individually and do separate DB requests for each query?

```ts
await Promise.all(
    reportItems.map(async (reportItem) => {
      const generated = await prisma.reportItem.aggregate({
        sum: {
          views: true,
        },

        where: {
          query: reportItem.query,
        },

      });
      console.log(reportItem.query, generated.sum );
    }),
  );
```

**Comment by laugharn** [comment]
It looks like the spec in #890 would support this, assuming they are doing all aggregates and not just count. Something like:

```js
const test = prisma.report.findMany({
  include: {
    Items:{
      aggregate: {
        sum: {
            views: true,
        }
       }
    }
})
```

So I'd keep an eye on that issue.

**Comment by Stevenje** [comment]
@laugharn That looks exactly what i was looking for. 

Thanks for sharing - I'll keep an eye on it!

**Comment by pantharshit00** [comment]
Closing in favor of #890
