### ISSUE TITLE
Unknown column name for "The provided value for the column is too long for the column's type

### ISSUE THREAD

**Issue by tre-dev** [prisma/prisma-client-js#944]
I'm using Prisma version 2.12.1. After changing `text` to `varchar(NUMBER)` for some columns and trying to fill those with data, I'm getting the following error:

```
The provided value for the column is too long for the column's type. Column: <unknown>
```

Problem is that I have no idea which column is meant since it's shown as `unknown`.

**Comment by pantharshit00** [comment]
Closing in favour of prisma/prisma/issues/4093
