### ISSUE TITLE
Generated types (index.d.ts) contains invalid expressions

### ISSUE THREAD

**Issue by johnpena** [prisma/prisma-client-js#949]
## Bug description

The generated types file (`node_modules/.prisma/client/index.d.ts`) generates type definitions with invalid signatures. These signatures seem to come from schema definitions that have multiple unique fields. Here's an example of an invalid signature from my code:

```
node_modules/.prisma/client/index.d.ts:4703:25 - error TS1005: '=' expected.

4703   export type MyModel.myFieldId_myOtherFieldId_uniqueCompoundUniqueInput = {
                             ~
```

## How to reproduce

I'm working to find minimal/exact steps to reproduce this. Thus far, it appears to happen with types that have multiple `@unique` fields or multiple unique together with `@@unique`. 

## Expected behavior

The types files that are being generated have syntax errors with the following pattern:

```
export type Model.field1Id_field2Id_uniqueCompoundUniqueInput = Prisma.Model.field1Id_field2Id_uniqueCompoundUniqueInput
```

Typescript won't compile with a dot in the name on the left hand side. 

## Prisma information

Will update this as soon as I can with a minimal schema, but once again multiple `@unique`s seem to be the culprit. 

## Environment & setup

- OS: MacOS Big Sur
- Database: PostgreSQL 13
- Node.js version: v15.0.1
- Prisma version: v2.13.0

**Comment by williamluke4** [comment]
Hey @johnpena, Thanks for reporting this. For the time being, you should be able to modify your `schema.prisma` to work around this. 
#### **`schema.prisma`**
```diff
- @@unique([myFieldId, myOtherFieldId], name: "MyModel.myFieldId_myOtherFieldId_uniqueCompoundUniqueInput")
+ @@unique([myFieldId, myOtherFieldId], name: "myFieldId_myOtherFieldId_uniqueCompoundUniqueInput")
```

**Comment by williamluke4** [comment]
After some digging, it appears that at its root this is an introspection engine issue.

#### **`Before Introspection`**
```prisma
model Test {
  name String
  path String

  @@unique([name, path])
}
```

#### **`After Introspection`**
```prisma
model Test {
  name String
  path String

  @@unique([name, path], name: "Test.name_path_unique")
}
```

**Comment by tomhoule** [comment]
This is tracked in https://github.com/prisma/prisma/issues/3193

**Comment by matthewmueller** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/3193
