### ISSUE TITLE
Starting a postgresql pool with 17 connections.

### ISSUE THREAD

**Issue by defucilis** [prisma/prisma-client-js#952]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v10.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.12.1             |

# Description
```
signalCode: null | exitCode: null | killed: false
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Exit code: undefined
Starting a postgresql pool with 17 connections.
```

## Logs
```
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  +4s
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  +1s
  prisma-client { clientVersion: '2.12.1' }  +2s
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  +8s
```

This was me running a big aggregation operation inside a `Promise.all` call inside a next.js API function, so it's very possible that I was just running too many queries at once...

**Comment by pantharshit00** [comment]
Can you please share logs with `export DEBUG=*` ran before the commands? Also, if you running very huge, batch, maybe adjust concurrency using this library: https://github.com/sindresorhus/p-map

**Comment by defucilis** [comment]
After having thought about how the code I was running works, I'm actually pretty sure that this isn't a bug, I wasn't closing connections correctly before running a huge amount of concurrent queries.

**Comment by pantharshit00** [comment]
Ok, then I am going to close this.
